"""Types for the compiled front end.

pyo3 gives Python no signatures, so a caller's type checker sees `Any` for
everything the extension returns - which is `Compiler`, `CompiledGrammar` and
`Matcher`, that is to say most of the library. Written by hand because the
alternative is a build step that generates it, and this surface is small and
changes rarely.
"""

from typing import Any

class CompileError(ValueError):
    """A grammar the compiler refused.

    `stage` is one of `lowering`, `lexer`, `productions`, `conflict` or `emit`,
    and is the answer to what to do about it: a budget can be raised and
    retried, a lowering failure cannot.
    """

    stage: str

class Matcher:
    """A host-side reference parser. The device is checked against this."""

    def accept_token(self, token: int) -> bool: ...
    def rollback(self, steps: int) -> None: ...
    def reset(self) -> None: ...
    def terminate(self) -> None: ...
    def is_terminated(self) -> bool: ...
    def can_terminate(self) -> bool: ...
    def fill_bitmask(self, buffer: Any) -> None: ...
    def allowed_tokens(self) -> list[int]: ...
    def admissible_groups(self) -> list[int]: ...
    def configurations(self) -> list[tuple[int, list[int]]]: ...
    def max_stack_depth(self) -> int: ...
    def num_configs(self) -> int: ...
    def lexer_state(self) -> int: ...
    def parser_state(self) -> int: ...
    def stack(self) -> list[int]: ...

class CompiledGrammar:
    """Tables for one grammar, against one vocabulary."""

    @property
    def relaxations(self) -> list[dict[str, str]]:
        """Exactly what this grammar does not enforce, and empty when nothing.

        One entry per finding, with `keyword` (the JSON Schema keyword
        responsible), `at` (a JSON pointer to the place in the schema),
        `effect` (what the mask now admits that the schema does not) and
        `remedy` (the edit that would enforce it, empty where no edit would).

        A mask may admit more than the grammar allows and never less, so a
        caller needing the grammar itself checks the finished document against
        what this lists.
        """

    @property
    def precision(self) -> str: ...
    @property
    def vocabulary_digest(self) -> int:
        """The vocabulary this was compiled against, as a digest.

        Two tokenizers of the same size are not the same tokenizer, and a
        grammar's groups are token ids, so one used against the wrong
        vocabulary gives a mask that is wrong token by token.
        """
    @property
    def bitset_words(self) -> int: ...
    @property
    def num_groups(self) -> int: ...
    @property
    def num_lexer_states(self) -> int: ...
    @property
    def num_parser_states(self) -> int: ...
    @property
    def num_terminals(self) -> int: ...
    def resident_bytes(self) -> int: ...
    def matcher(self, max_rollback: int = ...) -> Matcher: ...
    def device_arrays(self) -> dict[str, bytes]: ...
    def group_bitsets(self) -> Any: ...
    def lexer_transitions(self) -> Any: ...
    def lexer_accepting(self) -> Any: ...

class Compiler:
    """A vocabulary-bound compiler. Build one per model."""

    def __init__(self, vocabulary: list[bytes]) -> None: ...
    @property
    def vocab_size(self) -> int: ...
    @property
    def vocabulary_digest(self) -> int: ...
    def compile_json_schema(
        self,
        schema: str,
        lexer_states: int | None = ...,
        exact: bool = ...,
        max_digits: int | None = ...,
        max_string: int | None = ...,
        max_whitespace: int | None = ...,
    ) -> CompiledGrammar: ...
    def compile_regex(
        self, pattern: str, lexer_states: int | None = ...
    ) -> CompiledGrammar: ...
    def compile_ebnf(
        self, source: str, root: str, lexer_states: int | None = ...
    ) -> CompiledGrammar: ...

def pack_configurations(
    configurations: list[tuple[int, list[int]]], max_stack: int
) -> tuple[Any, Any, Any]: ...
