//! Static C++ emission — rung 3 of north-star-dsl.md.
//!
//! Walks a LOWERED class trace and writes the C++ the dumb interpreter
//! would execute: one statement per op, choices already made (they were
//! made at trace time; the emitter just spells them). This is the proof
//! of "statically convertible to C++": the generated file has no op
//! dispatch, no registry, no scan — the XQA prepare appears because the
//! emitter SAW the stated launch, the rope table build is a line because
//! the trace has the op, and layer weights are spelled `w.layers[17]`.
//!
//! What still appears as `if` in the generated code is exactly what the
//! interpreter also branches on: per-fire RUNTIME inputs
//! (`has_write_desc`, compact logits) and binding availability
//! (`gate_up_proj_fused`) — inputs of the launch, not choices between
//! kernels. Every such branch is a transliteration of the corresponding
//! interpreter arm in `declared_forward.cpp`, and the three-way parity
//! gate (hand-written ≡ interpreter ≡ generated) holds them together.
//!
//! Scope: the vocabulary the qwen3-class traces contain (pre-norm,
//! unpadded head dim, per-head qk-norm, fused QKV). Anything outside it
//! fails loudly — an emitter that silently skipped an op would be a
//! miscompile, not a fallback.

use crate::facts::{LlamaLikeCudaFacts, LlamaLikeFacts, NormPlacement, QkNorm};
use crate::family::llama_like_cuda;
use crate::trace::{FireClass, ForwardPlan, NormVariant, OpKind, RopeKind};

/// The digest naming what a generated TU was emitted FROM. The driver
/// composes the same string from its derived facts at model load
/// (`build_llama_like_declared_plan`) and runs the generated code only on
/// exact match — a config drift falls back to the interpreter, loudly.
/// One format, two printers (this and the C++ in declared_forward.cpp);
/// the live parity gate is what holds them together.
pub fn facts_digest(facts: &LlamaLikeFacts, cuda: &LlamaLikeCudaFacts) -> String {
    format!(
        "llama_like/h{}/l{}/qh{}/kvh{}/hd{}/i{}/v{}/rope{}/nv{}/np{}/qk{}/fq{}/te{}/xqa{}/dfp{}/rt{}/fpp{}",
        facts.hidden,
        facts.layers,
        facts.q_heads,
        facts.kv_heads,
        facts.head_dim,
        facts.intermediate,
        facts.vocab,
        match facts.rope {
            RopeKind::Standard => 0,
            RopeKind::Yarn => 1,
        },
        match facts.norm_variant {
            NormVariant::Plain => 0,
            NormVariant::Gemma => 1,
        },
        match facts.norm_placement {
            NormPlacement::Pre => 0,
            NormPlacement::Post => 1,
        },
        match facts.qk_norm {
            QkNorm::Off => 0,
            QkNorm::PerHead => 1,
            QkNorm::Global => 2,
        },
        u8::from(facts.fused_qkv),
        u8::from(facts.tied_embeddings),
        u8::from(cuda.xqa_decode),
        u8::from(cuda.decode_fused_post),
        u8::from(cuda.rope_table),
        u8::from(cuda.force_prefill_path),
    )
}

/// Emit the committed `.inc`: both class functions plus the digest
/// constant, ready for inclusion inside `declared_forward.cpp`'s
/// anonymous namespace (it uses the helpers and includes already there).
pub fn emit_llama_like_cuda_inc(facts: &LlamaLikeFacts, cuda: &LlamaLikeCudaFacts) -> String {
    let decode = llama_like_cuda(facts, cuda, FireClass::Decode);
    let prefill = llama_like_cuda(facts, cuda, FireClass::Prefill);
    let digest = facts_digest(facts, cuda);
    let mut out = String::new();
    out.push_str(&format!(
        "// GENERATED by `cargo run -p pie-forward --bin emit-cuda` — DO NOT EDIT.\n\
         // The static C++ form of the lowered llama_like class traces\n\
         // (north-star-dsl.md rung 3): one statement per traced op, choices\n\
         // already made at trace time. Included by declared_forward.cpp inside\n\
         // its anonymous namespace; regenerate after any change to the\n\
         // declaration, the facts below, or the emitter, and re-run the\n\
         // three-way parity gate.\n\
         //\n\
         // Emitted from: {digest}\n\n\
         constexpr const char* kGeneratedForDigest =\n    \"{digest}\";\n\n"
    ));
    out.push_str(&emit_class_fn(&decode, facts, "generated_llama_like_decode", true));
    out.push('\n');
    out.push_str(&emit_class_fn(&prefill, facts, "generated_llama_like_prefill", false));
    out
}

/// The parameter list shared with `llama_like_forward_declared`, minus the
/// plan (the whole point) and the inputs the class makes irrelevant.
const PARAMS: &str = "\
    const Qwen3Weights& w,\n\
    const HfConfig& cfg,\n\
    const LlamaLikeForwardCfg& fwd_cfg,\n\
    const LlamaLikePlanState& plan_state,\n\
    Workspace& ws,\n\
    KvCache& cache,\n\
    AttentionWorkspace& attn_ws,\n\
    ops::CublasHandle& cublas,\n\
    const std::int32_t* token_ids,\n\
    const std::int32_t* positions,\n\
    const std::uint32_t* qo_indptr,\n\
    const std::uint32_t* kv_page_indices,\n\
    const std::uint32_t* kv_page_indptr,\n\
    const std::uint32_t* kv_last_page_lens,\n\
    const std::uint32_t* qo_indptr_h,\n\
    const std::uint32_t* kv_page_indptr_h,\n\
    int total_tokens,\n\
    int num_requests,\n\
    const std::int32_t* logit_row_indices_d,\n\
    int num_logit_rows,\n\
    const std::uint32_t* w_page_d,\n\
    const std::uint32_t* w_off_d,\n\
    const std::uint8_t* row_valid_d,\n\
    bool has_write_desc";

fn emit_class_fn(
    plan: &ForwardPlan,
    facts: &LlamaLikeFacts,
    fn_name: &str,
    is_decode: bool,
) -> String {
    // The emitter's vocabulary is the qwen3 shape; refuse anything else
    // rather than miscompile (see module doc).
    assert!(
        facts.norm_placement == NormPlacement::Pre,
        "emitter: post-norm emission is a follow-up rung"
    );
    let mut b = Body::default();
    b.line(&format!("inline void {fn_name}(\n{PARAMS})\n{{"));
    b.line("    // Locals mirror the interpreter's preamble (unpadded shape:");
    b.line("    // the staging aliases are the plain buffers).");
    b.line("    const int N = total_tokens;");
    b.line("    const int R = num_requests;");
    b.line("    const int H = cfg.hidden_size;");
    b.line("    const int Hq = cfg.num_attention_heads * cfg.head_dim;");
    b.line("    const int Hk = cfg.num_key_value_heads * cfg.head_dim;");
    b.line("    const int I = cfg.intermediate_size;");
    b.line("    const int V = cfg.vocab_size;");
    b.line("    const int d = cfg.head_dim;");
    b.line("    const int num_q_heads = cfg.num_attention_heads;");
    b.line("    const int num_kv_heads = cfg.num_key_value_heads;");
    b.line("    const float eps = cfg.rms_norm_eps;");
    b.line("    cudaStream_t stream = cublas.stream();");
    b.line("    if (std::getenv(\"PIE_DECLARED_FORWARD_TRACE\")) {");
    b.line("        std::fprintf(stderr,");
    b.line(&format!(
        "                     \"[declared-forward-generated] N=%d R=%d decode={}\\n\",",
        i32::from(is_decode)
    ));
    b.line("                     N, R);");
    b.line("    }");
    b.line("");

    // A stated XQA launch obligates its fire-wide prepare — resolved HERE,
    // statically: the emitter saw the op, so the generated file has the
    // call and no scan.
    let states_xqa = plan.ops.iter().any(|op| {
        matches!(&op.kind, OpKind::Launch { kernel, .. }
                 if kernel == "launch_attention_xqa_decode_bf16_prepared")
    });
    if states_xqa {
        b.line("    // The trace states the XQA attention kernel; its fire-wide");
        b.line("    // prepare is that statement's obligation.");
        b.line("    ops::prepare_attention_xqa_decode_bf16(");
        b.line("        kv_page_indices, kv_page_indptr, kv_last_page_lens,");
        b.line("        R, cache.page_size(), plan_state.xqa_max_pages_per_seq,");
        b.line("        attn_ws, stream);");
        b.line("");
    }

    // Index walk: a Guard consumes its region ops into an emitted
    // `if`/`else` — the ONLY branch the declaration wrote, spelled as the
    // fixed condition its closed predicate names.
    let mut i = 0;
    while i < plan.ops.len() {
        let op = &plan.ops[i];
        if let OpKind::Guard {
            pred,
            then_ops,
            else_ops,
        } = &op.kind
        {
            let cond = match pred {
                crate::trace::GuardPred::HasWriteDesc => "has_write_desc",
            };
            b.stmt(&format!("if ({cond}) {{"));
            b.indent += 1;
            for j in (i + 1)..(i + 1 + *then_ops as usize) {
                emit_op(&mut b, &plan.ops[j], plan, facts, is_decode);
            }
            b.indent -= 1;
            b.stmt("} else {");
            b.indent += 1;
            let else_start = i + 1 + *then_ops as usize;
            for j in else_start..(else_start + *else_ops as usize) {
                emit_op(&mut b, &plan.ops[j], plan, facts, is_decode);
            }
            b.indent -= 1;
            b.stmt("}");
            i += 1 + (*then_ops + *else_ops) as usize;
            continue;
        }
        emit_op(&mut b, op, plan, facts, is_decode);
        i += 1;
    }
    b.line("}");
    b.out
}

#[derive(Default)]
struct Body {
    out: String,
    /// Extra indent levels while inside an emitted Guard region.
    indent: usize,
}

impl Body {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }
    fn stmt(&mut self, s: &str) {
        for l in s.lines() {
            self.out.push_str("    ");
            for _ in 0..self.indent {
                self.out.push_str("    ");
            }
            self.out.push_str(l);
            self.out.push('\n');
        }
    }
}

/// `layer.N.field` → (N, field); panics on anything else — the emitter's
/// weight vocabulary is family.rs's, same rule as the interpreter's
/// `parse_weight_name`, enforced at emission instead of at fire.
fn split_layer_weight(name: &str) -> Option<(u32, &str)> {
    let rest = name.strip_prefix("layer.")?;
    let dot = rest.find('.')?;
    let layer = rest[..dot].parse().ok()?;
    Some((layer, &rest[dot + 1..]))
}

fn require(layer: u32, member: &str, name: &str) -> String {
    format!("require(w.layers[{layer}].{member}, \"{name}\")->data()")
}

fn emit_op(b: &mut Body, op: &crate::trace::Op, plan: &ForwardPlan, facts: &LlamaLikeFacts, is_decode: bool) {
    let _ = plan;
    match &op.kind {
        OpKind::Embed { weight } => {
            assert_eq!(weight, "embed");
            b.stmt("kernels::launch_embed_bf16(");
            b.stmt("    token_ids, require(w.embed, \"embed\")->data(), ws.y.data(),");
            b.stmt("    N, H, V, stream);");
        }
        OpKind::Rmsnorm { weight, variant } => {
            assert_eq!(*variant, NormVariant::Plain, "emitter: Plain only");
            if weight == "final_norm" {
                // Deferred into the LmHead epilogue, exactly the
                // interpreter's arm (gather-then-norm ≡ norm-then-gather).
                b.stmt("// final_norm: deferred into the LmHead epilogue below.");
                return;
            }
            let (layer, field) = split_layer_weight(weight)
                .unwrap_or_else(|| panic!("emitter: unknown norm weight {weight}"));
            let (input, output) = match field {
                // Pre-norm routing, the interpreter's arm verbatim.
                "attn_norm" => ("ws.y.data()", "ws.norm_x.data()"),
                "mlp_norm" => ("ws.y.data()", "ws.norm_y.data()"),
                other => panic!("emitter: row-norm field {other} out of scope"),
            };
            b.stmt(&format!("kernels::launch_rmsnorm_bf16("));
            b.stmt(&format!(
                "    {input}, {},",
                require(layer, field, weight)
            ));
            b.stmt(&format!("    {output}, N, H, eps, stream);"));
        }
        OpKind::Matmul {
            weight,
            beta_one,
            selector,
        } => {
            assert!(selector.is_none(), "emitter: dyn matmul out of scope");
            let (layer, field) = split_layer_weight(weight)
                .unwrap_or_else(|| panic!("emitter: unknown matmul weight {weight}"));
            match (field, *beta_one) {
                ("qkv", false) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.norm_x.data(),");
                    b.stmt(&format!(
                        "    ops::WeightView(*require(w.layers[{layer}].qkv_proj_fused, \"{weight}\")),"
                    ));
                    b.stmt("    ws.qkv_fused.data(), N, Hq + 2 * Hk, H);");
                }
                ("o_proj", true) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.attn_out.data(),");
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].o_proj, \"{weight}\"), w.layers[{layer}].o_proj_quant),"
                    ));
                    b.stmt("    ws.y.data(), N, H, Hq, 1.f);");
                }
                ("gate_up", false) => {
                    // The binding dispatch, transliterated: fused when the
                    // deployment materialised the packed weight AND the
                    // workspace carries the buffer (the interpreter's
                    // `gate_up_used_fused`, which the Swiglu right after
                    // this reads — emitted as one combined block there).
                    b.stmt(&format!(
                        "const bool gate_up_fused_{layer} ="
                    ));
                    b.stmt(&format!(
                        "    w.layers[{layer}].gate_up_proj_fused != nullptr && !ws.gate_up_fused.empty();"
                    ));
                    b.stmt(&format!("if (gate_up_fused_{layer}) {{"));
                    b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("        ws.norm_y.data(),");
                    b.stmt(&format!(
                        "        ops::WeightView(*w.layers[{layer}].gate_up_proj_fused),"
                    ));
                    b.stmt("        ws.gate_up_fused.data(), N, 2 * I, H);");
                    b.stmt("} else {");
                    b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("        ws.norm_y.data(),");
                    b.stmt(&format!(
                        "        make_weight_view(require(w.layers[{layer}].gate_proj, \"{weight}\"), w.layers[{layer}].gate_proj_quant),"
                    ));
                    b.stmt("        ws.gate.data(), N, I, H);");
                    b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("        ws.norm_y.data(),");
                    b.stmt(&format!(
                        "        make_weight_view(require(w.layers[{layer}].up_proj, \"{weight}\"), w.layers[{layer}].up_proj_quant),"
                    ));
                    b.stmt("        ws.up.data(), N, I, H);");
                    b.stmt("}");
                }
                ("down", true) => {
                    b.stmt("ops::gemm_act_x_w(cublas.handle(),");
                    b.stmt("    ws.gate.data(),");
                    b.stmt(&format!(
                        "    make_weight_view(require(w.layers[{layer}].down_proj, \"{weight}\"), w.layers[{layer}].down_proj_quant),"
                    ));
                    b.stmt("    ws.y.data(), N, H, I, 1.f);");
                }
                (other, beta) => {
                    panic!("emitter: matmul field {other} (beta_one={beta}) out of scope")
                }
            }
        }
        OpKind::SplitQkv { .. } => {
            b.stmt("kernels::launch_split_qkv_bf16(");
            b.stmt("    ws.qkv_fused.data(),");
            b.stmt("    ws.q.data(), ws.k.data(), ws.v.data(),");
            b.stmt("    N, Hq, Hk, stream);");
        }
        OpKind::KvAppend { layer } => {
            // Unpadded shape: no pad staging. The write mechanism is a
            // per-fire RUNTIME input (Guard's territory, see
            // declared_forward.hpp); both branches are the interpreter's.
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    if (has_write_desc) {");
            b.stmt("        kernels::launch_write_kv_explicit_bf16(");
            b.stmt("            kv_view, ws.k.data(), ws.v.data(),");
            b.stmt("            w_page_d, w_off_d, N, stream, row_valid_d);");
            b.stmt("    } else {");
            b.stmt("        kernels::launch_write_kv_to_pages(");
            b.stmt("            kv_view, ws.k.data(), ws.v.data(),");
            b.stmt("            qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("            kv_last_page_lens,");
            b.stmt("            N, R, stream, row_valid_d);");
            b.stmt("    }");
            b.stmt("}");
        }
        OpKind::Swiglu { .. } => {
            // Paired with the gate_up binding dispatch emitted just above;
            // the flag name carries the layer, so nested blocks stay
            // scope-correct in the unrolled file.
            let layer = op
                .layer
                .expect("swiglu is a layer op in every llama_like trace");
            b.stmt(&format!("if (gate_up_fused_{layer}) {{"));
            b.stmt("    kernels::launch_chunked_swiglu_bf16(");
            b.stmt("        ws.gate_up_fused.data(), ws.gate.data(), N, I, stream);");
            b.stmt("} else {");
            b.stmt("    kernels::launch_swiglu_bf16(");
            b.stmt("        ws.gate.data(), ws.up.data(), ws.gate.data(),");
            b.stmt("        N * I, stream);");
            b.stmt("}");
        }
        OpKind::LmHead { weight } => {
            let member = match weight.as_str() {
                "embed" => "w.embed",
                "lm_head" => "w.lm_head",
                other => panic!("emitter: lm_head weight {other} out of scope"),
            };
            b.stmt("if (fwd_cfg.emit_logits) {");
            b.stmt("    // The hand-written epilogue, the interpreter's arm verbatim");
            b.stmt("    // (compact logits are a per-fire runtime input).");
            b.stmt("    const bool compact_logits =");
            b.stmt("        logit_row_indices_d != nullptr && num_logit_rows > 0 &&");
            b.stmt("        num_logit_rows < N;");
            b.stmt("    const void* lm_head_input = nullptr;");
            b.stmt("    int lm_head_rows = N;");
            b.stmt("    if (compact_logits) {");
            b.stmt("        kernels::launch_gather_bf16_rows(");
            b.stmt("            static_cast<const std::uint16_t*>(ws.y.data()),");
            b.stmt("            logit_row_indices_d,");
            b.stmt("            static_cast<std::uint16_t*>(ws.norm_x.data()),");
            b.stmt("            num_logit_rows, H, stream);");
            b.stmt("        kernels::launch_rmsnorm_bf16(");
            b.stmt("            ws.norm_x.data(), w.final_norm->data(),");
            b.stmt("            ws.norm_y.data(), num_logit_rows, H, eps, stream);");
            b.stmt("        lm_head_input = ws.norm_y.data();");
            b.stmt("        lm_head_rows = num_logit_rows;");
            b.stmt("    } else {");
            b.stmt("        kernels::launch_rmsnorm_bf16(");
            b.stmt("            ws.y.data(), w.final_norm->data(), ws.norm_y.data(),");
            b.stmt("            N, H, eps, stream);");
            b.stmt("        lm_head_input = ws.norm_y.data();");
            b.stmt("    }");
            b.stmt("    ops::gemm_act_x_w(cublas.handle(),");
            b.stmt(&format!(
                "        lm_head_input, ops::WeightView(*require({member}, \"{weight}\")),"
            ));
            b.stmt("        ws.logits.data(), lm_head_rows, V, H);");
            b.stmt("}");
        }
        OpKind::Launch {
            kernel,
            weights,
            state,
        } => emit_launch(b, kernel, weights, state.as_ref(), op, facts, is_decode),
        other => panic!("emitter: op kind {other:?} out of scope for the qwen3 classes"),
    }
}

fn emit_launch(
    b: &mut Body,
    kernel: &str,
    weights: &[String],
    state: Option<&crate::trace::StateRef>,
    op: &crate::trace::Op,
    facts: &LlamaLikeFacts,
    is_decode: bool,
) {
    match kernel {
        "launch_rope_standard_table" => {
            b.stmt("if (ws.rope_table.empty()) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: no rope table in workspace\");");
            b.stmt("}");
            b.stmt("kernels::launch_rope_standard_table(");
            b.stmt("    positions,");
            b.stmt("    static_cast<float*>(ws.rope_table.data()),");
            b.stmt("    N, d, cfg.rope_theta, stream);");
        }
        "launch_qkv_decode_qk_norm_rope_write_kv_bf16" => {
            let layer = state.expect("fused post addresses kv state").layer;
            let (q_norm, k_norm) = (&weights[0], &weights[1]);
            let (ql, _) = split_layer_weight(q_norm).expect("q_norm layer");
            // The trace says whether the table value exists (second input).
            let table = if op.inputs.len() >= 2 {
                "static_cast<const float*>(ws.rope_table.data())"
            } else {
                "nullptr"
            };
            b.stmt("kernels::launch_qkv_decode_qk_norm_rope_write_kv_bf16(");
            b.stmt("    ws.qkv_fused.data(),");
            b.stmt("    ws.q.data(),");
            b.stmt(&format!("    cache.k({layer}), cache.v({layer}),"));
            b.stmt(&format!("    {},", require(ql, "q_norm", q_norm)));
            b.stmt(&format!("    {},", require(ql, "k_norm", k_norm)));
            b.stmt("    positions,");
            b.stmt(&format!("    {table},"));
            b.stmt("    kv_page_indices, kv_page_indptr, kv_last_page_lens,");
            b.stmt("    has_write_desc ? w_page_d : nullptr,");
            b.stmt("    has_write_desc ? w_off_d : nullptr,");
            b.stmt("    row_valid_d,");
            b.stmt("    R, num_q_heads, num_kv_heads, d,");
            b.stmt("    cache.page_size(), cache.hnd_layout(),");
            b.stmt("    cfg.rope_theta, eps, stream);");
        }
        "launch_write_kv_explicit_bf16" => {
            let layer = state.expect("kv write addresses kv state").layer;
            b.stmt(&format!("{{"));
            b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
            b.stmt("    kernels::launch_write_kv_explicit_bf16(");
            b.stmt("        kv_view, ws.k.data(), ws.v.data(),");
            b.stmt("        w_page_d, w_off_d, N, stream, row_valid_d);");
            b.stmt("}");
        }
        "launch_write_kv_to_pages" => {
            let layer = state.expect("kv write addresses kv state").layer;
            b.stmt(&format!("{{"));
            b.stmt(&format!("    auto kv_view = cache.layer_view({layer});"));
            b.stmt("    kernels::launch_write_kv_to_pages(");
            b.stmt("        kv_view, ws.k.data(), ws.v.data(),");
            b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("        kv_last_page_lens,");
            b.stmt("        N, R, stream, row_valid_d);");
            b.stmt("}");
        }
        "launch_qk_rmsnorm_rope_bf16" => {
            let (q_norm, k_norm) = (&weights[0], &weights[1]);
            let (ql, _) = split_layer_weight(q_norm).expect("q_norm layer");
            b.stmt("kernels::launch_qk_rmsnorm_rope_bf16(");
            b.stmt("    ws.q.data(), ws.k.data(),");
            b.stmt(&format!("    {},", require(ql, "q_norm", q_norm)));
            b.stmt(&format!("    {},", require(ql, "k_norm", k_norm)));
            b.stmt("    positions, N, num_q_heads, num_kv_heads, d,");
            b.stmt("    cfg.rope_theta, eps, stream);");
        }
        "launch_attention_xqa_decode_bf16_prepared" => {
            let layer = state.expect("attention addresses kv state").layer;
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    ops::launch_attention_xqa_decode_bf16_prepared(");
            b.stmt("        ws.q.data(), kv_view.k_bf16_pages, kv_view.v_bf16_pages,");
            b.stmt("        ws.attn_out.data(),");
            b.stmt("        R, num_q_heads, num_kv_heads, d,");
            b.stmt("        cache.page_size(), plan_state.xqa_max_pages_per_seq,");
            b.stmt("        attn_ws, stream, /*sm_scale_override=*/-1.f);");
            b.stmt("}");
        }
        "launch_dequant_kv_cache_layer_to_bf16_active" => {
            let layer = state.expect("dequant addresses kv state").layer;
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    kernels::launch_dequant_kv_cache_layer_to_bf16_active(");
            b.stmt("        kv_view, kv_page_indices, kv_page_indptr_h[R], stream);");
            b.stmt("}");
        }
        "dispatch_attention_flashinfer_prefill_bf16" => {
            let layer = state.expect("attention addresses kv state").layer;
            // The class is static here: this function IS the prefill (or
            // the decode force_prefill fallback) — the plan-cache binding
            // the interpreter derives from `is_pure_decode` is a constant.
            let plan_cache = if is_decode {
                "plan_state.prefill_decode_plan"
            } else {
                "plan_state.prefill_plan"
            };
            b.stmt(&format!("if (!{plan_cache}) {{"));
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: prepare built no prefill plan\");");
            b.stmt("}");
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt("    ops::dispatch_attention_flashinfer_prefill_bf16(");
            b.stmt(&format!("        *{plan_cache},"));
            b.stmt("        ws.q.data(), kv_view.k_bf16_pages, kv_view.v_bf16_pages,");
            b.stmt("        ws.attn_out.data(),");
            b.stmt("        qo_indptr, kv_page_indices, kv_page_indptr,");
            b.stmt("        kv_last_page_lens,");
            b.stmt("        attn_ws, stream, /*logits_soft_cap=*/0.f,");
            b.stmt("        /*sm_scale_override=*/-1.f);");
            b.stmt("}");
        }
        "dispatch_attention_flashinfer_decode" => {
            let layer = state.expect("attention addresses kv state").layer;
            assert!(
                facts.norm_placement == NormPlacement::Pre,
                "window resolution below assumes the in-scope configs"
            );
            b.stmt("if (!plan_state.decode_plan) {");
            b.stmt("    throw std::runtime_error(");
            b.stmt("        \"generated forward: prepare built no decode plan\");");
            b.stmt("}");
            b.stmt(&format!("{{"));
            b.stmt(&format!(
                "    auto kv_view = cache.layer_view({layer});"
            ));
            b.stmt(&format!(
                "    const int layer_window_left ="
            ));
            b.stmt(&format!(
                "        (!fwd_cfg.per_layer_window_left.empty() &&"
            ));
            b.stmt(&format!(
                "         {layer} < static_cast<int>(fwd_cfg.per_layer_window_left.size()))"
            ));
            b.stmt(&format!(
                "            ? fwd_cfg.per_layer_window_left[{layer}]"
            ));
            b.stmt("            : fwd_cfg.sliding_window;");
            b.stmt("    ops::dispatch_attention_flashinfer_decode(");
            b.stmt("        *plan_state.decode_plan,");
            b.stmt("        ws.q.data(), kv_view, ws.attn_out.data(),");
            b.stmt("        kv_page_indices, kv_page_indptr, kv_last_page_lens,");
            b.stmt("        attn_ws, stream, layer_window_left,");
            b.stmt("        /*logits_soft_cap=*/0.f, /*sm_scale_override=*/-1.f);");
            b.stmt("}");
        }
        other => panic!("emitter: stated kernel {other} out of scope"),
    }
}
