package pie:plex@0.5.0;

interface policy {
    record invocation {
        context-json: string,
        state-json: string,
    }

    record policy-output {
        result-json: string,
        state-update-json: string,
    }

    route: func(input: invocation) -> result<policy-output, string>;
    admit: func(input: invocation) -> result<policy-output, string>;
    schedule: func(input: invocation) -> result<policy-output, string>;
    evict: func(input: invocation) -> result<policy-output, string>;
    feedback: func(input: invocation) -> result<policy-output, string>;
}
