//! The layers hold with no CUDA anywhere.
//!
//! This target runs with **no features**, which is the whole claim: layers 1
//! and 2 are a table and some text, so they compile and answer on a machine
//! with no toolkit, no driver and no device. That is not a convenience — it is
//! what lets `model-compiler` depend on this crate unconditionally and still
//! run in a container that has never seen a GPU.
//!
//! Everything here would also pass as a unit test inside the crate. It is a
//! separate target on purpose: a unit test compiles with whatever features the
//! rest of the build turned on, and an integration target compiled by
//! `cargo test -p kernels-cuda-new` with no flags is the only place the
//! feature-free build is actually EXERCISED rather than merely permitted.

use kernels_cuda_new::{device, execution, source, table, unit};

/// Layer 1 arrived, and a symbol names one row.
#[test]
fn the_table_is_readable_without_a_gpu() {
    assert!(!table::KERNELS.is_empty(), "the table did not come across");
    let row = &table::KERNELS[0];
    assert_eq!(table::sig(row.symbol).map(|r| r.symbol), Some(row.symbol));
}

/// Layer 2's text is in the binary, not on the disk.
///
/// The bytes are here at all only because [`include_str!`] put them here at
/// build time. A version of this crate that read `csrc/` at run time would
/// pass every other test in the tree and fail the one thing the design is
/// arranged around, so the assertion is on the CONTENT: the prelude has to
/// contain the type the rows instantiate at.
#[test]
fn the_device_sources_are_carried_in_the_binary() {
    let prelude = source::DEVICE_HEADERS
        .iter()
        .find(|h| h.name == "pie_device.cuh")
        .expect("the prelude is the one header every other entry includes");
    assert!(prelude.text.contains("bf16"), "the prelude does not define the rows' element type");

    assert!(source::roots::NORM_ALTUP_AUX.contains("__global__"));
    assert!(source::roots::NORM_ELEMENTWISE.contains("__global__"));
}

/// Every `#include` reachable from a unit resolves against the set.
///
/// NVRTC resolves against `headers[]`/`includeNames[]` and nothing else — there
/// is no include path — so a directive naming a header the set does not carry
/// compiles nowhere. Without this check that is an NVRTC error on a machine
/// with a GPU, which is the slowest possible place to find out.
///
/// **Reachability, not membership.** The set is generated by walking `csrc/`
/// and the sibling kernel tree, and that tree holds `.cuh` files belonging to
/// the ahead-of-time build — some of which include a host `.hpp` the JIT
/// deliberately does not carry. Those are harmless: NVRTC reads only what is
/// included, so a carried header no unit reaches is dead weight rather than a
/// defect. What must hold is that from a unit's root, every include resolves,
/// transitively — which is exactly what breaks a fire.
#[test]
fn every_include_reachable_from_a_unit_resolves() {
    let carried = |name: &str| source::DEVICE_HEADERS.iter().find(|h| h.name == name);

    for u in unit::UNITS {
        let mut seen: Vec<&str> = Vec::new();
        let mut queue: Vec<(&str, &str)> = vec![(u.name, u.root)];
        while let Some((from, text)) = queue.pop() {
            for included in source::quoted_includes(text) {
                let Some(header) = carried(included) else {
                    panic!("unit `{}` reaches `{included}` from `{from}`, uncarried", u.name);
                };
                if !seen.contains(&header.name) {
                    seen.push(header.name);
                    queue.push((header.name, header.text));
                }
            }
        }
    }
}

/// A unit's rows all claim the unit's own file.
///
/// The row states its file and the unit states its root; if the two can
/// disagree then a kernel is compiled by one unit and looked for in another,
/// and the symptom is a missing entry rather than anything that names the
/// mistake.
///
/// # A unit name is the file's stem, OR the stem plus a lattice suffix
///
/// Every unit was 1:1 with a `.cuh` until `crate::families::fa2`, which is 56
/// units over ONE root: `attn/fa2.cuh` compiled at 56 different points of a
/// four-axis instantiation lattice. The equality this test used to assert was
/// a proxy for the real property, and the real property is checked by
/// `a_symbol_belongs_to_one_unit` below — one symbol, at most one unit.
///
/// So the stem is derived from the ROW's file and the unit name must equal it
/// or extend it with `_`. That admits `attn/fa2.cuh` under
/// `attn/fa2_decode_hd128_g4` and still rejects a row from another file
/// entirely, which is the mistake the test was written for. It does NOT
/// admit a stem match by prefix alone: `attn/attention_flashinfer` matches its
/// own file exactly and is not confused with `attn/attention.cuh`, because
/// the stem comes from the file and not from splitting the name.
#[test]
fn a_row_lives_in_the_unit_that_compiles_it() {
    for u in unit::UNITS {
        for row in u.rows {
            let Some(file) = row.sig.file else {
                panic!("{} is in unit {} and claims no file", row.sig.symbol, u.name);
            };
            let stem = file.strip_suffix(".cuh").unwrap_or(file);
            let lattice = format!("{stem}_");
            assert!(
                u.name == stem || u.name.starts_with(&lattice),
                "{} is in unit {} and claims {:?}",
                row.sig.symbol,
                u.name,
                row.sig.file
            );
        }
    }
}

/// `unit_of` is a function: one symbol, at most one unit.
#[test]
fn a_symbol_belongs_to_one_unit() {
    for row in unit::rows() {
        let hosts: Vec<&str> =
            unit::UNITS.iter().filter(|u| u.hosts(row.sig.symbol)).map(|u| u.name).collect();
        assert_eq!(hosts.len(), 1, "{} is hosted by {hosts:?}", row.sig.symbol);

        let (index, found) = unit::unit_of(row.sig.symbol).expect("some unit hosts it");
        assert_eq!(found.name, hosts[0]);
        assert_eq!(unit::UNITS[index].name, found.name, "the index reaches the unit it named");
    }
    assert!(unit::unit_of("norm::a_kernel_nobody_wrote").is_none());
}

/// The cubin cache key spans everything that produced the cubin.
///
/// `driver-cuda/src/program/cache.rs` records this in the past tense: a cubin
/// keyed on less than what produced it is served after the thing it was not
/// keyed on changes. Under NVRTC the resolved text is the root plus every
/// header that can reach it, so both halves have to be in the key, and so does
/// the architecture.
#[test]
fn the_cache_key_spans_the_header_set_and_the_arch() {
    let u = &unit::UNITS[0];
    let base = u.cache_key("sm_89");

    assert_eq!(base, u.cache_key("sm_89"), "and is stable");
    assert_ne!(base, u.cache_key("sm_90"), "the architecture is in the key");

    let doctored = [source::Header { name: "pie_device.cuh", text: "// not what it was" }];
    assert_ne!(base, u.cache_key_with("sm_89", &doctored), "the header text is in the key");
}

/// Every symbol the dispatcher routes to the JIT is one some unit can compile.
///
/// A dispatched row with no unit has no launcher left to fall back to — that
/// was the point of deleting the `.cu` — so the failure is not a slow path, it
/// is a refusal reported as an unknown kernel. Catching it here costs nothing.
#[test]
fn every_dispatched_symbol_is_hosted() {
    for symbol in device::JIT_DISPATCHED {
        assert!(unit::unit_of(symbol).is_some(), "{symbol} is dispatched and hosted by no unit");
    }
}

/// The rows a unit names are instantiations C++ could actually spell.
///
/// `nvrtcAddNameExpression` takes this string verbatim and answers with a
/// mangled symbol; a malformed one fails at compile time on a GPU, with a
/// diagnostic about a name rather than about a row.
///
/// **Two shapes, and which one a row gets is not a judgement call**: a row
/// states `DeviceKernel::PLAIN` or it does not, and this asserts the exact
/// string either way rather than a substring of it. The earlier version of
/// this test asked only that the instantiation contain a `<` and end in `>`,
/// which was true of every row while every row was a template and is a
/// question that stops being answerable the moment one is not. Asserting the
/// whole string is strictly stronger — a prefix that drifted, an extra
/// qualification, a bracket in the wrong place all fail here rather than at
/// the first fire on a machine with a device.
#[test]
fn every_row_spells_a_qualified_instantiation() {
    let mut plain = 0;
    let mut templated = 0;
    for row in unit::rows() {
        let instantiation = row.instantiation();
        assert!(instantiation.starts_with("::"), "{instantiation} is not fully qualified");
        assert!(
            !instantiation.contains(device::DeviceKernel::PLAIN),
            "{} pasted the sentinel into a name expression: {instantiation}",
            row.sig.symbol
        );
        if row.is_plain() {
            plain += 1;
            assert_eq!(
                instantiation,
                format!("::pie_cuda_driver::kernels::{}", row.template_path),
                "{} names no template arguments, so its name is its path",
                row.sig.symbol
            );
            assert!(
                !instantiation.contains('<') && !instantiation.contains('>'),
                "{instantiation} carries an argument list a plain `__global__` cannot take"
            );
        } else {
            templated += 1;
            // The absolute-spelling escape: a `template_path` or `elem` that
            // already begins with `::` is spliced verbatim, because it names
            // something outside our namespace. `crate::families::fa2`'s 460
            // rows are the reason the field grew that reading — upstream's
            // `__global__` is `::flashinfer::BatchDecodeWithPagedKVCacheKernel`
            // with nine template arguments, and there is no wrapper that could
            // bring it under `::pie_cuda_driver::kernels::` (an alias template
            // aliases types, and a `__global__` cannot call a `__global__`).
            // See `device::DeviceKernel::instantiation` for the four
            // alternatives and why each was rejected.
            let qualify = |field: &str| {
                if field.starts_with("::") {
                    field.to_string()
                } else {
                    format!("::pie_cuda_driver::kernels::{field}")
                }
            };
            assert_eq!(
                instantiation,
                format!("{}<{}>", qualify(row.template_path), qualify(row.elem)),
                "{} is a template instantiation",
                row.sig.symbol
            );
            assert!(instantiation.contains('<') && instantiation.ends_with('>'));
            assert!(
                !row.elem.trim().is_empty(),
                "{} states an empty `elem`, which is an unfilled field and not a \
                 statement that the kernel takes no template arguments -- that is \
                 spelled `DeviceKernel::PLAIN`",
                row.sig.symbol
            );
        }
    }
    // Both arms are exercised, so neither is a branch nothing reaches.
    assert!(templated > 0, "no row is a template instantiation");
    assert!(
        plain > 0,
        "no row names a plain `__global__`, so the branch this test checks is dead \
         -- see `device::DeviceKernel::PLAIN`"
    );
}

// ─── The classification, with no CUDA anywhere ───────────────────────────
//
// `execution::Execution` is DATA — a name, not a call — and these assertions
// are the gate on that claim. If a service ever needed a cuBLAS handle to say
// which service it is, this target would stop compiling, because it is built
// with no features on a machine that need not have a toolkit.

/// A service is never a JIT row. This is the whole point of the distinction.
///
/// `Execution` has three arms and a symbol takes exactly one. The failure this
/// guards is not hypothetical: six rows left `Wall::Library` in the session
/// that introduced `SERVED`, and each was a row whose closure DID reach a
/// `__global__` of ours. If one of those had been left behind and then landed
/// as a unit, the table would say "library-served" and the runtime would JIT
/// it, and nothing else in the tree would notice.
#[test]
fn a_served_symbol_is_never_hosted() {
    for (symbol, service, evidence) in execution::SERVED {
        let row = table::sig(symbol).unwrap_or_else(|| {
            panic!("`{symbol}` is served by {service:?} and is not a row of `table::KERNELS`")
        });
        assert_eq!(row.symbol, *symbol);
        assert!(
            unit::unit_of(symbol).is_none(),
            "`{symbol}` is served by {service:?} AND hosted by a unit -- one of the \
             two is wrong, and the migration count is wrong either way"
        );
        assert!(
            evidence.len() > 40,
            "`{symbol}` is classified a service on {} characters of evidence. \
             `Wall::Library` was over-claimed ten times by reading a call site \
             instead of measuring; a citation short enough to be a guess is how",
            evidence.len()
        );
    }
}

/// The lookup answers the right ARM for every stated symbol, over the whole
/// table rather than over the fourteen rows that are interesting.
///
/// `None` is deliberate and is not a fifth arm: it means "an unmigrated
/// kernel", which is a fact about this migration's progress and not about how
/// the symbol executes.
#[test]
fn the_lookup_agrees_with_the_tables_it_reads() {
    let (mut jit, mut served, mut composed, mut pending) = (0usize, 0usize, 0usize, 0usize);
    for row in table::KERNELS {
        match execution::execution(row.symbol) {
            Some(execution::Execution::Jit(kernel)) => {
                jit += 1;
                assert_eq!(kernel.sig.symbol, row.symbol, "a unit hosts the wrong row");
                assert!(execution::service(row.symbol).is_none());
            }
            Some(execution::Execution::Service(_)) => {
                served += 1;
                assert!(
                    unit::unit_of(row.symbol).is_none(),
                    "{} answers `Service` and a unit hosts it",
                    row.symbol
                );
            }
            Some(execution::Execution::Composed(_)) => {
                composed += 1;
                assert!(
                    unit::unit_of(row.symbol).is_none(),
                    "{} answers `Composed` and a unit hosts it -- an op is a host program over \
                     kernels, so a symbol that is one launch of one kernel is not one",
                    row.symbol
                );
                assert!(
                    execution::service(row.symbol).is_none(),
                    "{} answers `Composed` and a service serves it",
                    row.symbol
                );
            }
            None => pending += 1,
        }
    }
    assert_eq!(served, execution::SERVED.len(), "a served row is not a table row");
    assert_eq!(composed, execution::COMPOSED.len(), "a composed row is not a table row");
    // `WALKED` AND ITS DENOMINATOR STOOD HERE. The list is gone with the
    // `Walk` type, so there is no fourth arm to count and no `statable_walks`
    // to compare it against. The comment that stood here explained why the
    // denominator was a FILTER (`driver_internal` rows are not statable) —
    // preserved in the record below `WALKED` in `execution.rs`, which is
    // where a reader looking for it will land.
    assert_eq!(
        jit + served + composed + pending,
        table::KERNELS.len(),
        "the lookup is not total"
    );
    assert!(
        jit > 100 && composed > 0 && pending > 0,
        "the arms are not all exercised: {jit} jit, {composed} composed, \
         {pending} pending"
    );
}

/// Every composition agrees with the rows it composes — **the gate, and it
/// needs no GPU.**
///
/// `Composition::agrees` is the composition half of what
/// `Specialisation::agrees` is for an arm: the step count, the arity of every
/// `take`, the type of every operand it lands on, the NAME of every operand it
/// lands on, and the citation. What it cannot check is whether the steps say
/// what the launcher says — that is `because`'s job and `tests/composition.rs`'s.
#[test]
fn every_composition_agrees_with_the_rows_it_composes() {
    assert!(!execution::COMPOSED.is_empty(), "no composition is stated, so this checks nothing");
    for composition in execution::COMPOSED {
        composition
            .agrees()
            .unwrap_or_else(|why| panic!("`{}` does not agree: {why}", composition.symbol));
    }

    // Stated and fireable are deliberately different, and the difference is
    // the honest half: a composition can be STATED before every step of it can
    // be FIRED. `gemm::act_x_wt_bias_bf16`'s first step is an unmigrated
    // kernel behind `Wall::HostChoice`.
    let fireable: Vec<&str> =
        execution::COMPOSED.iter().filter(|c| c.fireable()).map(|c| c.symbol).collect();
    assert_eq!(
        fireable,
        ["attn::compact_page_csr"],
        "the fireable set moved — if a step migrated, `tests/composition.rs` owes the new op a \
         byte-identical fire at two shapes and a reordering control before this line changes"
    );

    // The two numbers `Step`'s header quotes, counted rather than remembered.
    // Prose that counts a table is prose that goes stale the day the table
    // grows, and a rename count is exactly the fact a reader would use to
    // decide how much the name check is really doing.
    let takes: usize =
        execution::COMPOSED.iter().flat_map(|c| c.steps).map(|s| s.take().len()).sum();
    let renames: usize = execution::COMPOSED.iter().map(|c| c.renames.len()).sum();
    assert_eq!((renames, takes), (3, 26), "`Step`'s header says three renames across 26 takes");
}

/// A composition fills an operand from an operand of the same NAME, or says it
/// is renaming it.
///
/// The §21.14 answer for `take`, asserted rather than argued: `take` is a list
/// of INDICES and every same-typed operand is a legal value for one, so
/// `attn::compact_page_csr`'s three `U32s` inputs can be transposed and still
/// type-check. Perturbing the take fires; so does an unused rename, because a
/// rename is a licence and an unused licence widens what a later edit may do
/// in silence.
#[test]
fn a_take_that_transposes_two_same_typed_operands_is_refused() {
    use execution::{Composition, Step};
    use kernels_cuda_new::device::Take;

    // `attn::compact_page_csr`'s real step one, with `page_indptr_in` (op
    // operand 1) swapped for `page_indices_in` (op operand 0). Both are
    // `U32s`; every type check in the tree passes; the kernel would read a
    // page-id array as a CSR offset array and produce a plausible count.
    static TRANSPOSED: &[Step] = &[
        Step::Fire {
            symbol: "attn::count_kept",
            take: &[Take::From(0), Take::From(3), Take::From(5), Take::From(6), Take::From(4)],
        },
        Step::Fire {
            symbol: "attn::scan_and_scatter",
            take: &[
                Take::From(0), Take::From(1), Take::From(2), Take::From(3), Take::From(4),
                Take::From(5), Take::From(6), Take::From(8), Take::From(9), Take::From(7),
            ],
        },
    ];
    let transposed = Composition {
        symbol: "attn::compact_page_csr",
        steps: TRANSPOSED,
        renames: &[("scratch_counts", "counts")],
        because: "a deliberately transposed copy of `attn/page_compact.cu:42-51`, which must not agree",
    };
    let why = transposed.agrees().expect_err("a transposed take must not agree");
    assert!(
        why.contains("page_indptr_in") && why.contains("page_indices_in"),
        "the refusal must name both operands: {why}"
    );

    let unused = Composition {
        symbol: "attn::compact_page_csr",
        steps: execution::COMPOSED[0].steps,
        renames: &[("scratch_counts", "counts"), ("keep", "page_indices_out")],
        because: "the real composition with one rename nobody performs, which must not agree",
    };
    let why = unused.agrees().expect_err("an unused rename must not agree");
    assert!(why.contains("no step performs it"), "{why}");
}

/// A step may narrow a mutable buffer to a const one, and never the reverse.
///
/// The one relaxation `Composition::agrees` makes over
/// `Specialisation::agrees`, and it is forced rather than convenient:
/// `attn::compact_page_csr` hands `scratch_counts: U32sMut` to
/// `attn::scan_and_scatter`'s `counts: U32s`, which is a step READING what an
/// earlier step WROTE — the definitional shape of a composition. The reverse
/// would let a step write through an operand the op declared read-only, so it
/// is refused, and the refusal is measured here rather than left to the shape
/// of a lookup table.
#[test]
fn a_step_may_read_what_an_earlier_step_wrote_and_not_write_what_it_may_only_read() {
    use execution::{Composition, Step};
    use kernels_cuda_new::Ty;
    use kernels_cuda_new::device::Take;

    // The narrowing direction is in the shipped table and already checked by
    // `every_composition_agrees_with_the_rows_it_composes`; this pins WHICH
    // take performs it, so a later edit cannot quietly remove the case that
    // makes the relaxation necessary in the first place.
    let real = &execution::COMPOSED[0];
    assert_eq!(real.symbol, "attn::compact_page_csr");
    let op = table::sig(real.symbol).expect("the op is a row");
    let scan = execution::sig_of(real.steps[1].symbol()).expect("the step is a row");
    assert_eq!(op.operands[4].ty, Ty::U32sMut, "the op writes `scratch_counts`");
    assert_eq!(scan.operands[4].ty, Ty::U32s, "the step reads `counts`");

    // The widening direction, over the same two rows read the other way: the
    // op's `page_indices_in` is `U32s` and `scan_and_scatter`'s
    // `page_indices_out` is `U32sMut`, so a take that filled the output from
    // the input would be asking to write through a const operand.
    static WIDENED: &[Step] = &[
        Step::Fire {
            symbol: "attn::count_kept",
            take: &[Take::From(1), Take::From(3), Take::From(5), Take::From(6), Take::From(4)],
        },
        Step::Fire {
            symbol: "attn::scan_and_scatter",
            take: &[
                Take::From(0), Take::From(1), Take::From(2), Take::From(3), Take::From(4),
                Take::From(5), Take::From(6), Take::From(8), Take::From(9), Take::From(0),
            ],
        },
    ];
    let widened = Composition {
        symbol: "attn::compact_page_csr",
        steps: WIDENED,
        renames: &[("scratch_counts", "counts"), ("page_indices_in", "page_indices_out")],
        because: "a deliberately widened copy of `attn/page_compact.cu:48`, which must not agree",
    };
    let why = widened.agrees().expect_err("`const T*` -> `T*` must not agree");
    assert!(why.contains("page_indices_out"), "{why}");
}

/// No symbol composes itself, and the check can fail.
///
/// A step names a SYMBOL and a symbol may be composed, so this is the first
/// recursive edge in the table and the first place it can loop. The shipped
/// table is acyclic; the value of that statement is entirely in the three
/// perturbations below, because a check that has only ever been run against a
/// table known to be acyclic has proved nothing about the check.
#[test]
fn the_composition_graph_is_acyclic_and_the_assertion_can_fail() {
    use execution::{Composition, Step};
    use kernels_cuda_new::device::Take;

    execution::acyclic(execution::COMPOSED).expect("the shipped table is acyclic");

    // 1. The shortest cycle there is: a symbol whose step is itself.
    let itself = [Composition {
        symbol: "attn::compact_page_csr",
        steps: &[
            Step::Fire { symbol: "attn::compact_page_csr", take: &[] },
            Step::Fire { symbol: "attn::count_kept", take: &[] },
        ],
        renames: &[],
        because: "a deliberately self-firing composition, which must not be accepted as acyclic",
    }];
    let why = execution::acyclic(&itself).expect_err("a self-firing symbol is a cycle");
    assert!(why.contains("attn::compact_page_csr -> attn::compact_page_csr"), "{why}");

    // 2. The one a reader would NOT think of: two symbols that reach each
    //    other, so the walk has to distinguish "already visited" from "on the
    //    current path".
    let round_trip = [
        Composition {
            symbol: "attn::compact_page_csr",
            steps: &[
                Step::Fire { symbol: "norm::rmsnorm_bf16_with_fp16", take: &[] },
                Step::Fire { symbol: "gemm::act_x_wt_bias_bf16", take: &[] },
            ],
            renames: &[],
            because: "a deliberately cyclic table: this reaches the second, which reaches this",
        },
        Composition {
            symbol: "gemm::act_x_wt_bias_bf16",
            steps: &[
                Step::Fire { symbol: "attn::compact_page_csr", take: &[] },
                Step::Fire { symbol: "norm::add_bias_bf16", take: &[] },
            ],
            renames: &[],
            because: "the other half of the deliberately cyclic table above",
        },
    ];
    let why = execution::acyclic(&round_trip).expect_err("a two-symbol round trip is a cycle");
    assert!(
        why.contains("attn::compact_page_csr")
            && why.contains("gemm::act_x_wt_bias_bf16")
            && why.contains("->"),
        "the refusal must name the cycle in the order it was walked: {why}"
    );

    // 3. A DIAMOND is not a cycle, and this is the assertion that keeps the
    //    check from being "every re-visit is a loop". Both steps of the first
    //    reach the second; the second reaches nothing composed. Accepting this
    //    is what makes the two refusals above mean something.
    let diamond = [
        Composition {
            symbol: "attn::compact_page_csr",
            steps: &[
                Step::Fire { symbol: "gemm::act_x_wt_bias_bf16", take: &[] },
                Step::Fire { symbol: "gemm::act_x_wt_bias_bf16", take: &[] },
            ],
            renames: &[],
            because: "a diamond, not a cycle: one symbol reached twice on two different paths",
        },
        Composition {
            symbol: "gemm::act_x_wt_bias_bf16",
            steps: &[
                Step::Fire { symbol: "gemm::act_x_wt_bf16", take: &[Take::From(0)] },
                Step::Fire { symbol: "norm::add_bias_bf16", take: &[] },
            ],
            renames: &[],
            because: "the leaf of the diamond above, reaching nothing that is composed",
        },
    ];
    execution::acyclic(&diamond).expect("a diamond is not a cycle");
}

/// Every kind is reachable, so the `match` in `Execution::kind` is not three
/// arms two of which are dead.
///
/// All three now come from the shipped tables. The `Composed` arm used to be
/// constructed BY HAND here, because no row stated one; `attn::compact_page_csr`
/// does, so a hand-built value would be checking the test's own literal rather
/// than the crate's table.
#[test]
fn the_three_kinds_are_all_reachable() {
    use execution::{Execution, Kind};

    let jit = execution::execution("norm::rmsnorm_bf16").expect("a migrated row");
    assert_eq!(jit.kind(), Kind::Kernel);

    let service = execution::execution("dist::all_reduce_bf16").expect("a served row");
    assert_eq!(service.kind(), Kind::Service);
    assert!(matches!(service, Execution::Service(execution::Service::Nccl)));

    let op = execution::execution("attn::compact_page_csr").expect("a composed row");
    assert_eq!(op.kind(), Kind::Op);
    let Execution::Composed(steps) = op else { panic!("a composed row answers `Composed`") };
    assert_eq!(
        steps.iter().map(execution::Step::symbol).collect::<Vec<_>>(),
        ["attn::count_kept", "attn::scan_and_scatter"],
        "the ORDER is the sequence, and it is the one fact a row could not state"
    );

    // The whole point of the design, in one assertion: a step names a SYMBOL
    // and knows nothing about what executes it — so the executor can change
    // underneath a composition without the composition changing a byte.
    //
    // This assertion used to read `execution("gemm::act_x_wt_bf16").is_none()`
    // and called the first step *"an UNMIGRATED kernel — neither `Jit` nor
    // `Service`"*. It was true for four arcs and it is the thing that
    // changed: `gemm.cpp`'s dense autotuner is `driver-cuda/src/fire/gemm.rs`
    // now, the row was `Execution::Walk` and is `Service::DriverOp` today,
    // and `COMPOSED`'s entry for
    // `gemm::act_x_wt_bias_bf16` is byte-for-byte what it was. **That is the
    // information hiding working**, and it is a stronger demonstration than
    // the absence was: the step did not have to know, and it did not.
    let bias = execution::execution("gemm::act_x_wt_bias_bf16").expect("the demonstration case");
    assert_eq!(bias.kind(), Kind::Op);
    let first = execution::execution("gemm::act_x_wt_bf16")
        .expect("the demonstration case's first step is executed now");
    // THE §75 ARTEFACT THIS ASSERTION CARRIED, kept because it is the
    // clearest specimen in the file: the paragraph above once read *"the row
    // is `Execution::Walk`"*, a fact derived when `gemm.cpp`'s autotuner was
    // a driver-owned walk and left next to the demonstration after the walk
    // went. `gemm::act_x_wt_bf16` has not been in `WALKED` since `gemm`'s own
    // §5 step-5 crossing retracted its walks, so the assertion below was red
    // for several arcs and nothing said so — a walk is the one executor that
    // can be retracted without any list going empty, because `WALKED` losing
    // its last member is not a compile error.
    // WAS RED AT HEAD, AND NOT MADE RED BY THE `attn` CROSSING. Repaired
    // here because north star §6 owns it: the walk world and the row world
    // retire together, and `WALKED` is empty.
    //
    // Derived, not assumed, from `execution.rs`'s own lists rather than from
    // the paragraph above: `gemm::act_x_wt_bf16` is absent from `WALKED`
    // (which holds nothing at all), absent from `COMPOSED` and `RUST_SERVED`,
    // and present in `SERVED` as `Service::DriverOp` — with a `because` that
    // names the body: *"its bf16 arm is a direct Rust call to
    // `x::gemm::dense::act_x_wt_bf16` — the autotuner, the cuBLASLt plan
    // cache and the on-disk tactic cache."*
    //
    // So the answer changed from `Walk` to `Service(DriverOp)` and the
    // DEMONSTRATION IS UNHARMED — it is strictly better. The paragraph above
    // promises that a step "names a SYMBOL and knows nothing about what
    // executes it", and this symbol has now changed executor TWICE
    // (unmigrated -> walk -> driver op) while `COMPOSED`'s entry for
    // `gemm::act_x_wt_bias_bf16` stayed byte-for-byte identical. Asserting
    // the CURRENT executor by name would re-mint the coupling the assertion
    // exists to disprove, so what is asserted is that it HAS one and that
    // the composition did not have to know which.
    assert!(
        !matches!(first, Execution::Composed(_)),
        "`gemm::act_x_wt_bf16` is executed by something that is not itself a \
         composition -- it is `Service::DriverOp` today and was a driver-owned \
         host walk before that, and the point of this test is that \
         `COMPOSED`'s entry did not change when it moved"
    );
    assert_eq!(first.kind(), Kind::Op);
}
