//! The carried header set, generated by walking `csrc/` instead of listed by
//! hand.
//!
//! # Why this stopped being a hand-written array
//!
//! `src/source.rs` began with three `include_str!` entries and the rule that
//! *a header not in the set does not exist as far as a compile is concerned*.
//! Three is a list. The set now holds every kernel header this crate
//! compiles, the shims that replace NVIDIA's device headers, the two that
//! close the CCCL door, and a vendored FlashInfer closure of twenty-eight
//! files — and the moment a list of sixty entries has to be edited by hand to
//! add a file, the rule stops being enforced by the build and starts being
//! enforced by whoever remembers it.
//!
//! The failure mode is specific and unpleasant: a `.cuh` added to `csrc/` and
//! not added to the array is not a compile error anywhere. It is an NVRTC
//! *"could not open source file"* on a machine with a GPU, at the first fire
//! of whatever unit needed it, and the diagnostic names the include rather
//! than the omission.
//!
//! So the directory IS the set. Adding a file to `csrc/` adds it to the
//! binary, and removing one removes it.
//!
//! # The name is the path, because the name is what resolves
//!
//! NVRTC matches `includeNames[]` against the literal string in the `#include`
//! directive, so an entry's name has to be exactly what the includer writes.
//! Both trees are rooted so that this falls out:
//!
//! * `csrc/src/cuda/std/limits` is carried as `cuda/std/limits`, which is what
//!   FlashInfer's `#include <cuda/std/limits>` says.
//! * `csrc/vendor/flashinfer/attention/decode.cuh` is carried as
//!   `flashinfer/attention/decode.cuh`, which is what our own `.cu` files say.
//!
//! Impersonating a vendor header's spelling is deliberate where the includer
//! is source we do not own — `new-horizon.md` §13.4 is the rule — and the
//! directory layout is how that decision is expressed rather than configured.
//!
//! # Two groups, because a compile should not carry what it cannot need
//!
//! `LIBRARY` goes to every unit. `VENDOR` is 1.7 MB of somebody else's
//! attention library, and `nvrtcCreateProgram` copies every byte it is
//! handed, so a `norm` kernel does not get it. The split is by directory
//! because that is a fact a walk can see; which units want `VENDOR` is stated
//! by the units.
//!
//! # It was three walks until the `.cuh` files moved here
//!
//! The third walked `../kernels-cuda/csrc/src` for `*.cuh`, because that is
//! where the kernels were: the ahead-of-time crate authored them, this crate
//! compiled them, and `src/source.rs` argued the seam at length — one file is
//! one contract, and a copied `.cuh` is two contracts waiting to disagree.
//!
//! The argument was right and its conclusion flipped. Fifty-seven `.cuh`
//! files moved into `csrc/src`, so the walk that reached across is now the
//! walk that is already here — and the set it produced is unchanged, file for
//! file and byte for byte, because a move changes where text lives and not
//! what it says. What is left is the property that mattered: **one
//! definition of every kernel in the tree**, now held by the crate that
//! compiles it. `../kernels-cuda/csrc` keeps the `.cu` translation units and
//! the `.hpp` host interfaces, and finds these headers through an include
//! directory its CMake spells relative to its own manifest.
//!
//! # This needs no toolkit
//!
//! It walks a directory in this repository and writes a text file. That is the
//! whole of it — the same claim the rest of `build.rs` makes, and it is why
//! reading `$CUDA_HOME` here was rejected (§13.2).
//!
//! # Why it prints nothing
//!
//! It used to end with a `cargo:warning=` naming the two counts and the byte
//! total, which was harmless while this crate was a leaf that only a person
//! building it would see. It is not a leaf now: `model-compiler` depends on
//! `kernels-cuda`, `kernels-cuda` depends on this crate for the table, so a
//! line about header bytes appeared in every GPU-free `cargo check` of the
//! compiler. A warning that is always there is a warning nobody reads, and it
//! costs the next real one its audience.
//!
//! The counts moved into the generated file's own header, where they are one
//! `less $OUT_DIR/carried.rs` away and cannot go stale. What is left on the
//! interrupting channel is the one condition worth interrupting for — an
//! empty group, which is a mistyped tree — and that is an `assert!`, because
//! a build that carries no device text should stop rather than warn.

use std::path::{Path, PathBuf};

/// Files under `csrc/` that are documentation rather than source.
///
/// A licence is carried in the tree because vendoring requires it, and it must
/// not be carried in the BINARY as something an `#include` could resolve
/// against — a header set whose entries include a licence is a set whose rule
/// no longer means anything.
const NOT_SOURCE: &[&str] = &["LICENSE", "NOTICE", "MODIFICATIONS", "README", "README.md"];

/// Write `$OUT_DIR/carried.rs`.
pub fn generate(out: &Path) {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets it"));
    // The whole tree, not the individual files: a walk that reruns only when a
    // known file changes cannot notice a new one, which is the case this
    // module exists for.
    println!("cargo:rerun-if-changed=csrc");

    // `csrc/src` is the device text: every `__global__` template a unit
    // compiles, the prelude they are written over, and the shims that answer
    // the vendor spellings upstream source insists on. One tree, one walk --
    // it was two until the kernels moved here from `../kernels-cuda/csrc/src`,
    // and the second walk went with the reach.
    let library = collect(&root.join("csrc/src"));
    let vendor = collect(&root.join("csrc/vendor"));

    // An empty group is not a smaller set, it is a crate that carries no
    // device text at all — and it compiles. The failure surfaces as NVRTC
    // *"could not open source file"* at the first fire on a machine with a
    // GPU, which is the diagnostic this whole module exists to prevent, now
    // reading as if a header were missing rather than as if a directory were.
    //
    // The walk produces one for exactly one reason: it was pointed at a tree
    // that is not there. That was theoretical while the paths had been right
    // for years; it stopped being theoretical when the `.cuh` files moved
    // into `csrc/src` and one of the two walks changed what it names.
    for (group, tree, files) in
        [("LIBRARY", "csrc/src", &library), ("VENDOR", "csrc/vendor", &vendor)]
    {
        assert!(
            !files.is_empty(),
            "{group} is empty: nothing was found under {}. A walk of a \
             directory that does not exist returns no files rather than an \
             error, so this is what that looks like — check whether `{tree}` \
             still names the tree that holds the text.",
            root.join(tree).display()
        );
    }

    let mut text = String::new();
    let _ = std::fmt::Write::write_fmt(
        &mut text,
        format_args!(
            "// GENERATED by `build.rs`'s `carried` module -- do not edit.\n\
             //\n\
             // One entry per file under `csrc/`, named by its path relative to the\n\
             // tree it sits in, because that path is what an `#include` spells and\n\
             // what NVRTC matches `includeNames[]` against. Editing this is\n\
             // pointless: add or remove a FILE and the next build follows.\n\
             //\n\
             // {} device headers and {} vendored, {} bytes of text, carried into\n\
             // the binary by the `include_str!`s below.\n\n",
            library.len(),
            vendor.len(),
            library.iter().chain(&vendor).map(|(_, p)| file_len(p)).sum::<u64>()
        ),
    );
    emit(&mut text, "LIBRARY", &library, "csrc/src");
    emit(&mut text, "VENDOR", &vendor, "csrc/vendor");

    std::fs::write(out.join("carried.rs"), text).expect("write carried.rs");
}

/// Every source file under `tree`, as `(include name, absolute path)`, sorted.
///
/// # Why a file appears more than once
///
/// NVRTC matches `includeNames[]` against the **literal string in the
/// directive**, not against a path — there is no resolution, no search list,
/// no notion of "relative to the includer". So a file that two directives
/// reach by two spellings needs two entries, and a set that names each file
/// once cannot compile the tree it carries.
///
/// That is not hypothetical and it is not rare. FlashInfer's
/// `attention/decode.cuh` says `#include "../cp_async.cuh"`, and its
/// `attention/prefill.cuh` says `#include "mask.cuh"`; carried under their
/// paths alone, `flashinfer/cp_async.cuh` and `flashinfer/attention/mask.cuh`
/// are present and unreachable, and the compile stops at decode's first
/// relative directive. Thirty-two such spellings exist in the vendored tree.
///
/// So the walk collects the paths and then reads the carried text to find
/// **every spelling any directive uses**, resolving each against the
/// includer's directory and against the tree root the way a C preprocessor
/// would, and registers the file under each one that lands on it. Duplicated
/// text under two names costs a pointer; a missing spelling costs a compile on
/// a machine with a GPU.
///
/// # Why sorted
///
/// The set is hashed into a cubin cache key. A walk whose order depended on
/// the filesystem would produce a different digest on a different machine for
/// identical bytes, and every cache in the workspace would miss for a reason
/// nothing could see.
///
/// # Why there is no extension filter any more
///
/// There was one, and it took `Some("cuh")`: the walk reached into
/// `../kernels-cuda/csrc/src`, where `.cu`, `.cuh` and `.hpp` sit side by
/// side and only the middle one is device text a header set may carry. The
/// `.cuh` files live here now and the `.cu` and `.hpp` files did not come, so
/// the filter has nothing left to exclude — and a filter that excludes
/// nothing is a rule a reader has to check rather than one the directory
/// states.
fn collect(tree: &Path) -> Vec<(String, PathBuf)> {
    let mut found = Vec::new();
    walk(tree, tree, &mut found);
    found.sort();

    // The canonical name of each file, so a spelling can be resolved to one.
    let canonical: std::collections::HashMap<String, PathBuf> = found.iter().cloned().collect();

    let mut aliases: Vec<(String, PathBuf)> = Vec::new();
    for (name, path) in &found {
        let text = std::fs::read_to_string(path).unwrap_or_default();
        let directory = Path::new(name).parent().unwrap_or(Path::new(""));
        for spelling in includes(&text) {
            // Already reachable under this exact string.
            if canonical.contains_key(&spelling) {
                continue;
            }
            // Resolved the way a preprocessor would: beside the includer
            // first, then from the tree root.
            let beside = normalise(&directory.join(&spelling).to_string_lossy());
            let Some(target) = canonical.get(&beside).or_else(|| canonical.get(&spelling)) else {
                // Names a header this tree does not hold — another entry in
                // the set, or a directive inside an `#if` this compile never
                // takes. Either way not ours to resolve.
                continue;
            };
            aliases.push((spelling, target.clone()));
        }
    }

    aliases.sort();
    aliases.dedup();
    // One spelling must name one file. Two would be a set in which an
    // `#include` resolves to whichever entry NVRTC scanned first — a wrong
    // file, silently, which is worse than the missing one this fixes.
    for pair in aliases.windows(2) {
        assert!(
            !(pair[0].0 == pair[1].0 && pair[0].1 != pair[1].1),
            "the spelling `{}` reaches two different files, {} and {} -- NVRTC has \
             one flat namespace of include names, so this set would resolve it to \
             whichever came first",
            pair[0].0,
            pair[0].1.display(),
            pair[1].1.display()
        );
    }

    found.extend(aliases);
    found.sort();
    found.dedup();
    found
}

/// Every `#include` spelling in `source`, quoted or angled.
///
/// Both bracket styles, because NVRTC treats them the same against
/// `includeNames[]` — measured — and FlashInfer uses both to reach its own
/// files. Leading whitespace is allowed: NVIDIA's and FlashInfer's headers
/// both indent directives inside `#if` blocks.
fn includes(source: &str) -> Vec<String> {
    source
        .lines()
        .filter_map(|line| {
            let line = line.trim_start();
            let rest = line.strip_prefix('#')?.trim_start().strip_prefix("include")?;
            let rest = rest.trim_start();
            let (open, close) = match rest.chars().next()? {
                '"' => ('"', '"'),
                '<' => ('<', '>'),
                _ => return None,
            };
            rest.strip_prefix(open)?.split(close).next().map(str::to_string)
        })
        .collect()
}

/// `a/b/../c` -> `a/c`, without touching the filesystem.
///
/// Lexical, deliberately: the target may be a file this walk has already seen
/// by path, and `canonicalize` would resolve symlinks and produce an absolute
/// path that no longer matches the tree-relative names being compared.
fn normalise(path: &str) -> String {
    let mut parts: Vec<&str> = Vec::new();
    for part in path.split('/') {
        match part {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            other => parts.push(other),
        }
    }
    parts.join("/")
}

fn walk(tree: &Path, at: &Path, found: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(at) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        // A dot-directory is a scratch space or a VCS artifact; neither is a
        // header, and a walk that carried one would put it in the binary.
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            walk(tree, &path, found);
        } else if !NOT_SOURCE.contains(&name.as_ref()) {
            let relative = path
                .strip_prefix(tree)
                .expect("the walk started at the tree")
                .to_string_lossy()
                .replace('\\', "/");
            found.push((relative, path));
        }
    }
}

/// One `pub const NAME: &[Header]` over `files`.
fn emit(text: &mut String, constant: &str, files: &[(String, PathBuf)], tree: &str) {
    use std::fmt::Write as _;

    let _ = writeln!(
        text,
        "/// Every file under `{tree}`, carried in the binary.\n\
         ///\n\
         /// {} entries. Generated; see `build.rs`.\n\
         pub const {constant}: &[crate::source::Header] = &[",
        files.len()
    );
    for (name, path) in files {
        // `include_str!` rather than the bytes inline: a megabyte of escaped
        // string literal is slow for rustc to parse, and a real file in
        // OUT_DIR is something a person can open when a compile goes wrong.
        let _ = writeln!(
            text,
            "    crate::source::Header {{ name: {name:?}, text: include_str!({}) }},",
            format_args!("{:?}", path.to_string_lossy())
        );
    }
    text.push_str("];\n\n");
}

/// A file's length, or zero if it cannot be read — this is a log line, not a
/// decision.
fn file_len(path: &Path) -> u64 {
    std::fs::metadata(path).map(|m| m.len()).unwrap_or(0)
}
