pub mod forward;
pub mod import;
pub mod media;
pub mod model;
pub mod rotation;
pub mod template;
pub mod tokenizer;

use model::Model;
use poem_dsl::Dtype;

pub fn skus() -> Vec<crate::Sku> {
    crate::split_skus![
        (
            "qwen36-27b-mtp",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d27b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-27b-dflash",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d27b_dflash(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-27b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d27b_undrafted(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-27b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d27b_undrafted(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-tiny",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::tiny(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d0_8b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d0_8b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d2b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d2b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d2b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d2b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d4b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d4b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d4b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d4b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d9b-dflash",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d9b_dflash(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d9b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d9b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d9b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d9b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b-dflash",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b_dflash(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b-mtp",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b_mtp(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b-mini",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b_mini(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b-mini",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b_mini(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-35b-a3b-mini64",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b_mini64(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-27b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d27b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen36-27b",
            2,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d27b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen38-27b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen38-27b",
            2,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen38-27b-dflash2",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b_dflash2(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen38-27b-dspark",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b_dspark(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen38-27b-mtp",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen38-27b",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b_undrafted(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen38-27b",
            2,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38,
            || Model::d27b_undrafted(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-a3b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d3b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d3b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d3b",
            2,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d3b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b-eagle",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d0_8b_eagle(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d0_8b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b",
            2,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::d0_8b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-a3b",
            2,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT,
            || Model::a3b(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b-vision-eagle",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            || Model::d0_8b_vision_eagle(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen36-27b-vision",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            || Model::d27b_vision_undrafted(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen36-27b-vision",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            || Model::d27b_vision(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen38-27b-vision",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38_VISION,
            || Model::d27b_vision_undrafted(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen38-27b-vision",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml_interleaved,
            &tokenizer::CONTRACT_38_VISION,
            || Model::d27b_vision(Dtype::Bf16, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b-vision",
            1,
            [Dtype::U4g64],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            || Model::d0_8b_vision(Dtype::U4g64, Dtype::Bf16),
        ),
        (
            "qwen35-d0.8b-vision",
            1,
            [Dtype::Bf16],
            Dtype::Bf16,
            poem_dsl::trace_hybrid,
            template::chatml,
            &tokenizer::CONTRACT_VISION,
            || Model::d0_8b_vision(Dtype::Bf16, Dtype::Bf16),
        ),
    ]
}
