# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Context:
    
    @classmethod
    def create(cls) -> Self:
        """
        Creates a fresh empty context
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    @classmethod
    def open(cls, name: str) -> Self:
        """
        Opens a snapshot (implicit fork — snapshot stays immutable, working pages are copied)
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    @classmethod
    def take(cls, name: str) -> Self:
        """
        Takes ownership of a snapshot (snapshot is deleted, GPU pages transfer without copy)
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    @classmethod
    def delete(cls, name: str) -> None:
        """
        Deletes a saved snapshot by name
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def fork(self) -> Self:
        """
        Forks into a new anonymous context (working pages are copied via GPU D2D or CPU H2D)
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def save(self, name: str) -> None:
        """
        Named save — snapshots committed chain + working pages under a user-chosen name
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def snapshot(self) -> str:
        """
        Anonymous save — snapshots committed chain + working pages, returns runtime-generated name
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def destroy(self) -> None:
        """
        Force-destroys immediately
        """
        raise NotImplementedError
    def tokens_per_page(self) -> int:
        """
        Number of tokens per page
        """
        raise NotImplementedError
    def committed_page_count(self) -> int:
        """
        Number of committed KV pages in the context
        """
        raise NotImplementedError
    def working_page_count(self) -> int:
        """
        Number of working KV pages (based on buffered tokens in the resource handle)
        """
        raise NotImplementedError
    def commit_working_pages(self, num_pages: int) -> None:
        """
        Commit working KV pages to the context
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def reserve_working_pages(self, num_pages: int) -> None:
        """
        Reserve additional working GPU pages for the context
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def release_working_pages(self, num_pages: int) -> None:
        """
        Release working GPU pages from the context
        """
        raise NotImplementedError
    def working_page_token_count(self) -> int:
        """
        Number of tokens in working pages (filled via forward pass but not yet committed)
        """
        raise NotImplementedError
    def truncate_working_page_tokens(self, num_tokens: int) -> None:
        """
        Remove the last N tokens from working pages (for rollback, e.g. speculative rejection)
        """
        raise NotImplementedError
    def suspend(self) -> None:
        """
        Suspend this context (release GPU pages, offload to CPU).
        Restoration is system-driven under FCFS: suspended contexts are
        restored oldest-launched first as memory frees up.
        
        Raises: `wit_world.types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



