# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def name() -> str:
    """
    The engine serves exactly one model; these are global functions over
    that single bound model (no `model`/`tokenizer` resource handles).
    Returns the name of the bound model
    """
    raise NotImplementedError
def architecture() -> str:
    """
    Returns the model architecture identifier (e.g. "gemma4", "qwen3_6")
    """
    raise NotImplementedError
def default_system_speculation() -> bool:
    """
    Whether the bound model enables system speculation by default
    """
    raise NotImplementedError
def encode(text: str) -> List[int]:
    """
    Converts input text into a list of token IDs
    """
    raise NotImplementedError
def decode(tokens: List[int]) -> str:
    """
    Converts token IDs back into a decoded string
    
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def vocabs() -> Tuple[List[int], List[bytes]]:
    """
    Returns the model's vocabulary as a list of byte sequences (tokens)
    """
    raise NotImplementedError
def split_regex() -> str:
    """
    Returns the split regular expression used by the tokenizer
    """
    raise NotImplementedError
def special_tokens() -> Tuple[List[int], List[bytes]]:
    """
    Returns the special tokens recognized by the model
    """
    raise NotImplementedError
