# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def version() -> str:
    """
    Returns the runtime version string
    """
    raise NotImplementedError
def instance_id() -> str:
    """
    Returns a unique identifier for the running instance
    """
    raise NotImplementedError
def username() -> str:
    """
    Returns the username of the user who invoked the inferlet
    """
    raise NotImplementedError
def models() -> List[str]:
    """
    Get a list of all available model names
    """
    raise NotImplementedError
def metadata_put(namespace: str, key: str, value: bytes) -> None:
    """
    Store or overwrite engine-lifetime inferlet metadata under a namespace.
    
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def metadata_get(namespace: str, key: str) -> Optional[bytes]:
    """
    Retrieve engine-lifetime inferlet metadata from a namespace.
    
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
def metadata_delete(namespace: str, key: str) -> bool:
    """
    Delete engine-lifetime inferlet metadata from a namespace.
    
    Raises: `wit_world.types.Err(wit_world.imports.str)`
    """
    raise NotImplementedError
