//! Bench-program generator (lane L3 / delta, WS6).
//!
//! Emits the MVP sampler catalog as PSIR v2 bytecode at the benchmark vocab and
//! writes a C++ header of byte arrays for the CUDA bench harness
//! (`driver/cuda/tests/bench_sampling_ir.cpp`). Run:
//!
//!   cargo run -p sampling-edsl --example gen_bench_programs -- \
//!       driver/cuda/tests/bench_programs.h
//!
//! Authoritative path: the same EDSL → `pie-sampling-ir` encoder the SDK uses,
//! so the bench compiles *genuine* programs (not hand-rolled kernels). Vocab is
//! baked into the program (a const generic), matching production where a fixed
//! model vocab keys the program cache.

use std::io::Write;

use sampling_edsl::prelude::*;
use sampling_edsl::Built;

// Benchmark vocabulary (Qwen3 vocab, per WS6 spec).
const V: usize = 151_936;

fn argmax() -> Built {
    let g = Graph::new(V as u32);
    let logits = g.intrinsic_logits::<V>();
    g.output_token(&logits.argmax());
    g.build().expect("argmax builds")
}

fn temperature() -> Built {
    let g = Graph::new(V as u32);
    let logits = g.intrinsic_logits::<V>();
    let temp = g.host_scalar::<f32>(HostAvailability::SubmitBound);
    let seed = g.host_scalar::<u32>(HostAvailability::SubmitBound);
    let scaled = temperature_scale(&logits, &temp);
    g.output_token(&gumbel_argmax(&scaled, &seed));
    g.build().expect("temperature builds")
}

fn min_p() -> Built {
    let g = Graph::new(V as u32);
    let logits = g.intrinsic_logits::<V>();
    let temp = g.host_scalar::<f32>(HostAvailability::SubmitBound);
    let p = g.host_scalar::<f32>(HostAvailability::SubmitBound);
    let seed = g.host_scalar::<u32>(HostAvailability::SubmitBound);
    let scaled = temperature_scale(&logits, &temp);
    let keep = min_p_mask(&logits, &p);
    let score = mask_to_score(&keep, &scaled);
    g.output_token(&gumbel_argmax(&score, &seed));
    g.build().expect("min-p builds")
}

fn top_k() -> Built {
    let g = Graph::new(V as u32);
    let logits = g.intrinsic_logits::<V>();
    let temp = g.host_scalar::<f32>(HostAvailability::SubmitBound);
    let seed = g.host_scalar::<u32>(HostAvailability::SubmitBound);
    let scaled = temperature_scale(&logits, &temp);
    let keep = top_k_mask(&logits, 50);
    let score = mask_to_score(&keep, &scaled);
    g.output_token(&gumbel_argmax(&score, &seed));
    g.build().expect("top-k builds")
}

fn top_p() -> Built {
    let g = Graph::new(V as u32);
    let logits = g.intrinsic_logits::<V>();
    let temp = g.host_scalar::<f32>(HostAvailability::SubmitBound);
    let p = g.host_scalar::<f32>(HostAvailability::SubmitBound);
    let seed = g.host_scalar::<u32>(HostAvailability::SubmitBound);
    let scaled = temperature_scale(&logits, &temp);
    let probs = softmax(&scaled);
    let keep = top_p_mask(&probs, &p);
    let score = mask_to_score(&keep, &scaled);
    g.output_token(&gumbel_argmax(&score, &seed));
    g.build().expect("top-p builds")
}

fn emit(out: &mut impl Write, name: &str, b: &Built) {
    let lowered = b.lower();
    let bytes = &lowered.bytecode;
    // Host-input keys, in declaration order, so the bench knows which scalars to
    // supply each fire (temp/p/seed) — all submit-bound.
    let keys: Vec<u32> = b.host_inputs.iter().map(|h| h.key).collect();
    writeln!(
        out,
        "// {} — {} bytes, {} host inputs {:?}",
        name,
        bytes.len(),
        keys.len(),
        keys
    )
    .unwrap();
    writeln!(out, "static const unsigned char {}[] = {{", name).unwrap();
    for chunk in bytes.chunks(16) {
        write!(out, "  ").unwrap();
        for byte in chunk {
            write!(out, "0x{byte:02x},").unwrap();
        }
        writeln!(out).unwrap();
    }
    writeln!(out, "}};").unwrap();
}

fn main() {
    let path = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "driver/cuda/tests/bench_programs.h".to_string());
    let mut out = Vec::new();
    writeln!(
        out,
        "// AUTO-GENERATED by `cargo run -p sampling-edsl --example gen_bench_programs`."
    )
    .unwrap();
    writeln!(
        out,
        "// PSIR v2 bytecode for the WS6 sampler bench at vocab={V}. DO NOT hand-edit."
    )
    .unwrap();
    writeln!(out, "#pragma once\n").unwrap();
    writeln!(out, "static const unsigned int BENCH_VOCAB = {V};\n").unwrap();
    emit(&mut out, "BENCH_ARGMAX", &argmax());
    emit(&mut out, "BENCH_TEMP", &temperature());
    emit(&mut out, "BENCH_MINP", &min_p());
    emit(&mut out, "BENCH_TOPK", &top_k());
    emit(&mut out, "BENCH_TOPP", &top_p());
    // A program with a batched-unsupported op (`gather`), for the backend's
    // M=1-fallback test: mirostat lowers M=1 but not batched.
    let (mirostat, _keys) =
        sampling_edsl::program::mirostat(V as u32).expect("mirostat builds");
    emit(&mut out, "BENCH_MIROSTAT", &mirostat);
    std::fs::write(&path, &out).expect("write header");
    eprintln!("wrote {} ({} bytes)", path, out.len());
}
