#pragma once

/* Generated by pie-loader-cbindgen (cbindgen). Do not edit by hand. Regenerate: cargo run -p pie-loader-cbindgen */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

namespace pie_loader {

/// Sentinel for "no buffer", mirroring the C++ `numeric_limits<uint32_t>::max()`
/// defaults on `PieLoaderStorageInstrView::buffer_id` and `slab_file_id`.
constexpr static const uint32_t PIE_LOADER_NO_BUFFER = UINT32_MAX;

/// The LOW IR version. A driver that reads a plan with a different version is
/// reading a layout it was not compiled against.
constexpr static const uint32_t PIE_LOADER_PLAN_VERSION = 5;

constexpr static const uint32_t PIE_LOADER_TILE_MAP_CAST = (1 << 0);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_DECODE = (1 << 1);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_ENCODE = (1 << 2);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_TRANSCODE = (1 << 3);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_REBLOCK = (1 << 4);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_REORDER = (1 << 5);

constexpr static const uint32_t PIE_LOADER_TILE_MAP_REPACK = (1 << 6);

enum class PieLoaderStatus : uint32_t {
  Ok = 0,
  /// The request was malformed: a null pointer, a non-UTF-8 path, an
  /// out-of-range enum. The caller built the request wrong.
  InvalidRequest = 1,
  /// The checkpoint could not be read or does not say what the request claims.
  InvalidCheckpoint = 2,
  /// The plan was rejected against its contract. Only `pie_loader_verify`
  /// returns this.
  ContractViolation = 3,
  /// The compiler failed on input it should have handled. A bug in the loader.
  Internal = 4,
  /// A panic was caught at the boundary. Also a bug in the loader, but
  /// distinguished because the diagnostic is a panic payload rather than a
  /// structured error.
  Panic = 5,
};

/// Which on-disk format a checkpoint file uses.
enum class PieLoaderCheckpointFormat : uint32_t {
  Safetensors = 0,
  Gguf = 1,
  Unknown = 2,
};

enum class PieLoaderDType : uint32_t {
  F32 = 0,
  F16 = 1,
  BF16 = 2,
  F8E4M3 = 3,
  F8E5M2 = 4,
  I32 = 5,
  I16 = 6,
  I8 = 7,
  U32 = 8,
  U16 = 9,
  U8 = 10,
  Bool = 11,
};

enum class PieLoaderEncodingKind : uint32_t {
  Raw = 0,
  Quant = 1,
};

/// Discriminants follow `crate::types::QuantScheme` declaration order, which is
/// *not* the order of the hand-written C++ enum this replaces (`MlxAffineU4` is
/// eighth here and last there). The mismatch was invisible while the boundary
/// was JSON, because the C++ parser mapped by name. Now that the two sides share
/// integers, the generated header must be the only definition — deleting the
/// hand-written enum is part of the same change, not a follow-up.
enum class PieLoaderQuantScheme : uint32_t {
  None = 0,
  Fp8E4M3 = 1,
  Fp8E5M2 = 2,
  Int8Symmetric = 3,
  Int8Asymmetric = 4,
  AwqInt4 = 5,
  GptqInt4 = 6,
  Mxfp4E2M1E8M0 = 7,
  MlxAffineU4 = 8,
  GgufQ4_0 = 9,
  GgufQ4K = 10,
  GgufQ5_0 = 11,
  GgufQ5K = 12,
  GgufQ8_0 = 13,
};

enum class PieLoaderStorageInstrKind : uint32_t {
  Allocate = 0,
  ExtentWrite = 1,
  TileMap = 2,
  CreateView = 3,
  Attach = 4,
  Release = 5,
  Finalize = 6,
  BulkExtentWrite = 7,
  SlabScatter = 8,
};

/// `None` is the resting value for instructions that carry no tile map, so it
/// sorts last rather than first — matching the C++ enum and the default on
/// `PieLoaderStorageInstrView::tile_kind`.
enum class PieLoaderTileMapKind : uint32_t {
  Cast = 0,
  Decode = 1,
  Encode = 2,
  Transcode = 3,
  Reblock = 4,
  Reorder = 5,
  Repack = 6,
  None = 7,
};

/// A transform chain the backend collapsed into a single kernel.
///
/// `None` is the resting value, so the driver's `switch` needs no separate
/// "is there a fusion" test.
enum class PieLoaderTransformFusion : uint32_t {
  None = 0,
  /// Encode an FP8 source straight to MXFP4, skipping the BF16 HBM
  /// round-trip. Bit-identical to the two-step path.
  Fp8ToMxfp4 = 1,
};

enum class PieLoaderRepackLayout : uint32_t {
  None = 0,
  MarlinMxfp4Weight = 1,
  MarlinMxfp4Scale = 2,
  DenseRowGather = 3,
};

enum class PieLoaderRowMap : uint32_t {
  Identity = 0,
  Even = 1,
  Odd = 2,
};

enum class PieLoaderBackendKind : uint32_t {
  Cuda = 0,
  Metal = 1,
  Unknown = 255,
};

enum class PieLoaderMxfp4MoePolicy : uint32_t {
  RoutedDecode = 0,
  NativeGemm = 1,
  EagerBf16 = 2,
};

/// How a scale tensor's entries map onto the tensor they scale.
enum class PieLoaderQuantGranularity : uint32_t {
  PerChannel = 0,
  PerGroup = 1,
};

/// What the driver's kernels expect a scale tensor to hold when they read it.
///
/// Not derivable from the scale tensor: its dtype says how the bytes are stored,
/// not how the kernel wants them. The driver used to infer this from
/// `group_size == 32`.
enum class PieLoaderScaleForm : uint32_t {
  /// Raw E8M0 exponent bytes, consumed as-is.
  RawE8M0 = 0,
  /// F32 multipliers; expand before the GEMM sees them.
  F32Factors = 1,
};

enum class PieLoaderSeverity : uint32_t {
  /// The plan is still usable. Emitted so a compile can report a suboptimal
  /// choice without failing.
  Warning = 0,
  Error = 1,
};

/// Which part of a multimodal checkpoint to load.
///
/// `Full` and `Text` load every tensor the ABI declares; `Encode` narrows the
/// plan to the vision/audio towers so an encoder-only rank does not materialize
/// the language model.
enum class PieLoaderComponent : uint32_t {
  Full = 0,
  Text = 1,
  Encode = 2,
};

enum class PieLoaderMxfp4MoeRequest : uint32_t {
  /// Let the loader pick from the target's capabilities.
  Auto = 0,
  RoutedDecode = 1,
  NativeGemm = 2,
  EagerBf16 = 3,
};

/// A borrowed UTF-8 string. Not NUL-terminated: plan strings come from Rust
/// `String`s, and copying them only to append a NUL would double the arena for
/// no reader that needs it. C++ consumers build a `string_view` from the pair.
struct PieLoaderBytes {
  const uint8_t *ptr;
  size_t len;
};

/// The device-measured half of a request.
///
/// Every field is a fact only the driver can state: what the device is, how wide
/// the TP group is, and which transforms this backend's kernels implement. The
/// loader never guesses any of it, which is what makes a plan reproducible from
/// a recorded spec on a machine with no GPU (§2 P2).
///
/// `backend` is a plain `uint32_t` rather than `PieLoaderBackendKind`, and the
/// same goes for the enum-valued fields of [`PieLoaderRequest`]. C++ lets a
/// caller store any integer in an enum-typed field, and reading such a field as
/// a Rust enum is undefined behaviour that happens *before* any check could
/// reject it. Assign `static_cast<uint32_t>(PieLoaderBackendKind::Cuda)`; the
/// loader validates the value and answers `PieLoaderStatus::InvalidRequest` if
/// it is not one of them.
struct PieLoaderTargetSpec {
  uint32_t backend;
  uint32_t tp_rank;
  uint32_t tp_size;
  uint64_t max_tile_bytes;
  uint32_t preferred_alignment;
  uint32_t tile_map_mask;
  bool fp8_native;
  bool native_mxfp4_moe;
  /// Whether this build has the fused transform kernels and wants them used.
  ///
  /// The opt-out that used to be `PIE_CUDA_DISABLE_FUSED_TRANSCODE`, read
  /// inside the executor. As a request field it changes the *plan*, so two
  /// settings produce two artifacts instead of one plan that runs two ways
  /// (§8.1). Backends with no fused kernels pass `false`.
  bool fused_transcode;
};

/// The model facts the storage compile keys off.
///
/// The driver has already parsed `config.json` to build its own model, so the
/// loader reading it a second time was duplicated work that could disagree.
/// The driver states these; the loader never opens the file.
struct PieLoaderModelSpec {
  /// HF `model_type`, from the text tower when the checkpoint nests one.
  PieLoaderBytes model_type;
  /// `quantization_config.quant_method`, or empty for an unquantized
  /// checkpoint.
  PieLoaderBytes quant_method;
  uint32_t num_hidden_layers;
  /// HF `num_local_experts` / `num_experts` / `n_routed_experts`. Zero on a
  /// dense model.
  uint32_t num_experts;
  uint32_t num_experts_per_tok;
};

struct PieLoaderI64Slice {
  const int64_t *ptr;
  size_t len;
};

/// One tensor the driver promises to bind after the load.
///
/// This is the driver's half of the contract (§10.2.1). Today the loader's
/// `arch/` passes decide *both* what the model needs and how to build it, so a
/// pass that invents an output name the driver never binds — or computes a shape
/// the driver disagrees with — is caught by nothing. Declaring the demand makes
/// `pie_loader_verify` a real check rather than a self-comparison.
///
/// State only what you know. `shape.len == 0` means "do not check the shape",
/// which is the honest answer for a tensor whose runtime layout the driver reads
/// off the loaded tensor rather than predicting. The encoding is deliberately
/// absent from this struct: it is the loader's choice under the runtime quant
/// policy, and binders probe it afterwards.
struct PieLoaderTensorDemand {
  PieLoaderBytes name;
  /// The shape *this rank* expects, already divided by the TP size. Empty to
  /// demand presence without a shape.
  PieLoaderI64Slice shape;
  /// Absence is not a violation, e.g. `lm_head.weight` under
  /// `tie_word_embeddings`.
  bool optional;
};

struct PieLoaderTensorDemandSlice {
  const PieLoaderTensorDemand *ptr;
  size_t len;
};

/// A compile request.
///
/// Strings are pointer + length and are borrowed for the duration of the call;
/// the loader copies anything it keeps.
struct PieLoaderRequest {
  PieLoaderBytes snapshot_dir;
  PieLoaderTargetSpec target;
  PieLoaderModelSpec model;
  /// The runtime's own quantization request (e.g. `"fp8"`), not a checkpoint
  /// fact. Empty means "whatever the checkpoint is". Ignored when the target
  /// reports no native support for the requested format.
  PieLoaderBytes runtime_quant;
  /// A `PieLoaderMxfp4MoeRequest` value, as `uint32_t`. See
  /// [`PieLoaderTargetSpec::backend`] for why this is not the enum type.
  uint32_t mxfp4_moe;
  /// A `PieLoaderComponent` value, as `uint32_t`.
  uint32_t component;
  /// What the driver promises to bind. Borrowed for the call.
  ///
  /// Empty means the driver declares nothing, and `pie_loader_verify` checks
  /// only the plan's internal consistency — which is where every caller
  /// started. A driver that fills this in gets its shapes checked against the
  /// plan by code that did not compute them.
  PieLoaderTensorDemandSlice demands;
};

/// One file the plan reads from. `PieLoaderSourceTensorView::file_id` indexes
/// `PieLoaderPlan::files`, so the driver no longer has to re-derive the file
/// order for itself (§6).
struct PieLoaderCheckpointFileView {
  uint32_t id;
  PieLoaderBytes path;
  uint64_t size_bytes;
  PieLoaderCheckpointFormat format;
};

struct PieLoaderCheckpointFileSlice {
  const PieLoaderCheckpointFileView *ptr;
  size_t len;
};

struct PieLoaderSourceTensorView {
  uint32_t id;
  PieLoaderBytes name;
  uint32_t file_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  uint8_t quant_bits_per_element;
  uint32_t quant_group_size;
  PieLoaderI64Slice shape;
};

struct PieLoaderSourceTensorSlice {
  const PieLoaderSourceTensorView *ptr;
  size_t len;
};

struct PieLoaderTensorDeclView {
  uint32_t id;
  PieLoaderBytes name;
  PieLoaderDType dtype;
  PieLoaderEncodingKind encoding_kind;
  PieLoaderQuantScheme quant_scheme;
  uint8_t quant_bits_per_element;
  uint32_t quant_group_size;
  PieLoaderI64Slice shape;
  uint32_t alignment;
};

struct PieLoaderTensorDeclSlice {
  const PieLoaderTensorDeclView *ptr;
  size_t len;
};

struct PieLoaderBufferDeclView {
  uint32_t id;
  uint32_t tensor_id;
  bool has_tensor;
  uint64_t bytes;
  uint32_t alignment;
  bool temporary;
  bool has_persistent_offset;
  uint64_t persistent_offset;
};

struct PieLoaderBufferDeclSlice {
  const PieLoaderBufferDeclView *ptr;
  size_t len;
};

struct PieLoaderDimSpecView {
  int64_t count;
  int64_t src_stride;
  int64_t dst_stride;
};

struct PieLoaderDimSpecSlice {
  const PieLoaderDimSpecView *ptr;
  size_t len;
};

struct PieLoaderStridedExtentView {
  uint64_t base_offset;
  uint32_t element_bytes;
  PieLoaderDimSpecSlice dims;
};

struct PieLoaderSourceExtentView {
  uint32_t file_id;
  uint32_t tensor_id;
  uint64_t file_offset;
  uint64_t span_bytes;
  PieLoaderStridedExtentView stride;
};

struct PieLoaderDestExtentView {
  uint32_t buffer_id;
  uint64_t offset;
  PieLoaderStridedExtentView stride;
};

struct PieLoaderU32Slice {
  const uint32_t *ptr;
  size_t len;
};

struct PieLoaderSlabPlacementView {
  uint64_t src_offset;
  uint64_t dest_offset;
  uint64_t bytes;
};

struct PieLoaderSlabPlacementSlice {
  const PieLoaderSlabPlacementView *ptr;
  size_t len;
};

/// The flattened instruction. Rust's `StorageInstr` is a sum type whose variants
/// carry disjoint payloads; C has no such thing, so this is the union of all
/// variants with `kind` as the tag and `has_source`/`has_dest` marking which
/// optional members are live. Members a given `kind` does not use keep their
/// resting values.
struct PieLoaderStorageInstrView {
  uint32_t id;
  PieLoaderStorageInstrKind kind;
  uint32_t buffer_id;
  PieLoaderSourceExtentView source;
  bool has_source;
  PieLoaderDestExtentView dest;
  bool has_dest;
  PieLoaderU32Slice input_buffers;
  PieLoaderU32Slice output_buffers;
  PieLoaderTileMapKind tile_kind;
  /// Rows of the output to transform per launch; `0` means the whole tensor in
  /// one pass.
  ///
  /// This is where the driver's `max_tile_bytes` budget ends up. The budget
  /// itself does not cross the boundary: the driver stated it in the request,
  /// the loader answered with a row count in `backend::lower`, and sending the
  /// question back alongside the answer would only invite the executor to
  /// re-derive it (§8.1).
  uint32_t rows_per_tile;
  /// A transform chain the backend collapsed into one kernel.
  PieLoaderTransformFusion transform_fusion;
  PieLoaderQuantScheme transform_from;
  PieLoaderQuantScheme transform_to;
  PieLoaderRepackLayout repack_layout;
  PieLoaderRowMap row_map;
  uint32_t transform_batch;
  uint32_t transform_source_rows;
  uint32_t transform_source_row_offset;
  uint32_t transform_target_rows;
  uint32_t transform_valid_rows;
  uint32_t transform_source_stride_cols;
  uint32_t transform_source_col_offset;
  uint32_t transform_source_cols;
  uint32_t transform_target_cols;
  uint64_t transform_scratch_bytes;
  PieLoaderBytes name;
  uint32_t slab_file_id;
  uint64_t slab_file_offset;
  uint64_t slab_span_bytes;
  PieLoaderSlabPlacementSlice slab_placements;
};

struct PieLoaderStorageInstrSlice {
  const PieLoaderStorageInstrView *ptr;
  size_t len;
};

struct PieLoaderMemoryPlanView {
  uint64_t persistent_bytes;
  uint64_t temporary_peak_bytes;
  uint64_t transform_scratch_peak_bytes;
  uint64_t checkpoint_read_bytes;
  uint64_t device_write_bytes;
};

struct PieLoaderOptimizerPassStatsView {
  PieLoaderBytes name;
  uint64_t exprs_before;
  uint64_t exprs_after;
  uint64_t rewrites;
};

struct PieLoaderOptimizerPassStatsSlice {
  const PieLoaderOptimizerPassStatsView *ptr;
  size_t len;
};

struct PieLoaderOptimizerReportView {
  PieLoaderOptimizerPassStatsSlice passes;
};

/// The target the plan was compiled against. The driver reads it back to assert
/// the plan it received is the plan it asked for — the same fields it supplied
/// in the request, plus the rank identity that makes a TP shard distinguishable
/// from its siblings (§6.2).
struct PieLoaderTargetView {
  PieLoaderBackendKind backend;
  uint32_t tp_rank;
  uint32_t tp_size;
  uint64_t max_tile_bytes;
  uint32_t preferred_alignment;
  uint32_t tile_map_mask;
  PieLoaderMxfp4MoePolicy mxfp4_moe;
  bool native_mxfp4_moe;
  bool fused_transcode;
};

/// A quantized tensor paired with the tensor holding its scales.
///
/// Both are entries in [`PieLoaderPlan::tensors`], named by `id`. The driver has
/// to know the pairing in order to attach the quant metadata its kernels read;
/// it used to rediscover it by matching name suffixes over the tensor list,
/// which guessed at something the loader states here (`load_plan.rs`'s
/// `derive_quant_attachments`).
struct PieLoaderQuantAttachmentView {
  uint32_t tensor_id;
  uint32_t scale_tensor_id;
  PieLoaderQuantGranularity granularity;
  uint32_t group_size;
  uint32_t channel_axis;
  PieLoaderScaleForm scale_form;
};

struct PieLoaderQuantAttachmentSlice {
  const PieLoaderQuantAttachmentView *ptr;
  size_t len;
};

/// How much of the caller's declared contract the plan delivers.
///
/// `covered < demanded` means the loader did not build something the driver said
/// it would bind. An absent *optional* demand is dropped from both counts rather
/// than only from `covered`, so a tied-embedding checkpoint that legitimately
/// has no `lm_head.weight` still reports full coverage.
///
/// A driver that declared nothing gets `0 / 0`, which passes — the declaration
/// is opt-in per model family, not a flag day.
struct PieLoaderContractCoverageView {
  size_t covered;
  size_t demanded;
};

/// The compiled plan, as the driver sees it.
///
/// The leading members reproduce the old `LoadPlanView` in order, so an executor
/// written against that view compiles unchanged against this struct. `target`
/// and `compiler_version` fold in the accessors `loaded_model.cpp` reached
/// through `LoadPlan` methods (`backend()`, `mxfp4_moe()`, `native_mxfp4_moe()`,
/// `preferred_alignment()`, `max_tile_bytes()`, `tile_map_mask()`,
/// `compiler_version()`), which have no method syntax to hide behind once the
/// type is POD.
///
/// `owner` is the opaque handle to the arena keeping every slice above alive. It
/// is consumed by `pie_loader_release`; the driver must not dereference it.
struct PieLoaderPlan {
  uint32_t version;
  PieLoaderCheckpointFileSlice files;
  PieLoaderSourceTensorSlice sources;
  PieLoaderTensorDeclSlice tensors;
  PieLoaderBufferDeclSlice buffers;
  PieLoaderStorageInstrSlice instrs;
  PieLoaderU32Slice schedule;
  PieLoaderMemoryPlanView memory;
  PieLoaderOptimizerReportView optimizer;
  uint64_t compiler_version;
  PieLoaderTargetView target;
  PieLoaderQuantAttachmentSlice attachments;
  /// Measured against `PieLoaderRequest::demands` at compile time.
  PieLoaderContractCoverageView coverage;
  /// The name of the materialized weights this plan produces, as 16 hex
  /// digits. Stable for as long as nothing that decides the bytes changes, so
  /// a driver can use it to key an artifact cache.
  PieLoaderBytes cache_key;
  /// One line describing the plan, for a boot log.
  PieLoaderBytes summary;
  /// The plan's counts and instruction histograms as JSON, for an operator
  /// dump. Rendered by the loader so no driver keeps a second table of
  /// instruction names to fall out of step with this one.
  PieLoaderBytes stats_json;
  void *owner;
};

/// One diagnostic record.
///
/// `message` is borrowed from the owning [`PieLoaderDiagnostics`] and is valid
/// until it is released.
struct PieLoaderDiagnostic {
  PieLoaderSeverity severity;
  PieLoaderBytes message;
};

/// A flat array of diagnostics plus the storage backing their messages.
///
/// Returned through an out-param by both entry points, including on success when
/// the compile produced warnings. A null out-pointer means the caller does not
/// want them; a non-null pointer left null means there were none.
struct PieLoaderDiagnostics {
  const PieLoaderDiagnostic *items;
  size_t len;
  void *owner;
};

extern "C" {

/// Compile a checkpoint into a plan.
///
/// On success `*out_plan` receives a plan the caller must free with
/// [`pie_loader_release`]. On failure `*out_plan` is left null.
///
/// # Safety
///
/// `req` must point at a valid [`PieLoaderRequest`] whose borrowed strings are
/// live for the call. `out_plan` must be a writable slot. `out_diags` is either
/// null or a writable slot.
PieLoaderStatus pie_loader_compile(const PieLoaderRequest *req,
                                   PieLoaderPlan **out_plan,
                                   PieLoaderDiagnostics **out_diags);

/// Check a plan against the contract it claims to satisfy.
///
/// Verification reports *every* violation it finds rather than the first, so the
/// diagnostics array is the result and the status only says whether the array is
/// empty.
///
/// # Safety
///
/// `plan` must point at a live plan from [`pie_loader_compile`]. `req` must point
/// at the request the plan was compiled from. `out_diags` is either null or a
/// writable slot.
PieLoaderStatus pie_loader_verify(const PieLoaderPlan *plan,
                                  const PieLoaderRequest *req,
                                  PieLoaderDiagnostics **out_diags);

/// Free a plan returned by [`pie_loader_compile`].
///
/// # Safety
///
/// `plan` is null or a pointer from [`pie_loader_compile`] that has not already
/// been released.
void pie_loader_release(PieLoaderPlan *plan);

/// Free diagnostics returned through an out-param.
///
/// # Safety
///
/// `diags` is null or a pointer produced by this module that has not already been
/// released.
void pie_loader_release_diagnostics(PieLoaderDiagnostics *diags);

}  // extern "C"

}  // namespace pie_loader
