#!/usr/bin/env bash
# Regenerates src/pjrt/sys.rs from the vendored pjrt_c_api.h.
#
# The header is openxla/xla xla/pjrt/c/pjrt_c_api.h at 6f094faf0fad (PJRT C API
# 0.115, what libtpu 0.0.48 serves). Run by hand after bumping it; the build
# never runs bindgen. Needs bindgen-cli and a libclang (LIBCLANG_PATH).
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
builtin="$(ls -d /usr/lib/gcc/x86_64-linux-gnu/*/include 2>/dev/null | tail -1)"
{
  echo '// @generated by pjrt/bindgen.sh from pjrt/pjrt_c_api.h; do not edit.'
  echo '#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code, clippy::all)]'
  bindgen "$here/pjrt_c_api.h" \
    --allowlist-type 'PJRT_.*' \
    --allowlist-var 'PJRT_.*' \
    --default-enum-style consts \
    --no-prepend-enum-name \
    --no-doc-comments \
    -- ${builtin:+-I"$builtin"}
} > "$here/../src/pjrt/sys.rs"
