"""
Byte-identity of the Python ETA port against the Rust SDK.

`goldens/eta_containers.txt` holds, per program, the FNV-1a identity hash and
the canonical container bytes as the Rust `eta-dsl` `Builder` emits them
(regenerated by `crates/eta-dsl/tests/sdk_goldens.rs`). Each test below
rebuilds the same program through the Python `Builder` and compares bytes —
the whole point of the port is that a Python inferlet and a Rust inferlet
tracing the same pass share one container hash and one program-cache entry.

These drive the neutral `Builder` directly, so no WIT stubs are needed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from inferlet.eta import intrinsics
from inferlet.eta.builder import Builder, DslChannel
from inferlet.eta.ir import Dtype, Port, Stage, dtype, fnv1a64
from inferlet.eta.value import (
    Tensor,
    abs_,
    and_,
    cast,
    causal_mask,
    const_data,
    cummass_le,
    cumprod,
    cumsum,
    entropy,
    entropy_from_logprobs,
    eq,
    exp,
    gather,
    ge,
    gt,
    gumbel,
    gumbel_max,
    indptr,
    iota,
    l2norm,
    le,
    log,
    log_softmax,
    lt,
    mask_apply,
    masked_argmax,
    matmul,
    max_elem,
    min_elem,
    ne,
    neg,
    not_,
    nucleus_sample,
    or_,
    pivot_threshold,
    prob_ge,
    rank_le,
    recip,
    reduce_argmax,
    reduce_max,
    reduce_min,
    reduce_sum,
    rem,
    reshape,
    rng,
    row_membership,
    scalar_gather,
    scatter_add,
    scatter_set,
    select,
    sign,
    sink_window_mask,
    sliding_window_mask,
    softmax,
    sort_desc,
    top_k,
    transpose,
)

VOCAB = 151_936
PAGE = 32

GOLDENS = {}
for line in (Path(__file__).parent / "goldens" / "eta_containers.txt").read_text().splitlines():
    name, h, hexbytes = line.split()
    GOLDENS[name] = (int(h), bytes.fromhex(hexbytes))


def ch_from(v, dt=None, name=None):
    c = DslChannel.from_const(const_data(v, dt))
    return c.named(name) if name else c


def ch_new(shape, dt, name=None):
    c = DslChannel.new(shape, dt)
    return c.named(name) if name else c


def host_put(ch: DslChannel, v, dt=None):
    const_data(v, dt)  # validates shape/dtype the way a real put would
    ch.note_host_put()


def check(name: str, traced) -> None:
    want_hash, want_bytes = GOLDENS[name]
    got = traced.encode()
    assert got == want_bytes, f"{name}: container bytes differ from the Rust encoder"
    assert traced.identity_hash() == want_hash
    assert fnv1a64(got) == want_hash


def test_s3_matches_lowering_rs_golden():
    """`crates/eta-dsl/tests/lowering.rs::build_s3` — its hash is pinned
    there as GOLDEN_S3, so this checks the Rust golden directly too."""
    vocab = 32_000
    ctr1 = Tensor.constant([0, 1], Dtype.U32)
    tok = ch_new([1], dtype.i32, "tok")
    indptr_ch = ch_from([0, 1], dtype.u32, "indptr")
    out = ch_new([1], dtype.i32, "out")
    mask = ch_new([vocab], dtype.bool, "mask")
    length = ch_from([1], dtype.u32, "len")
    rng_ch = ch_from([7, 0], dtype.u32, "rng")
    host_put(tok, [1], dtype.i32)

    b = Builder(vocab, 16)
    b.bind_port(Port.EMBED_TOKENS, tok)
    b.bind_port(Port.EMBED_INDPTR, indptr_ch)
    b.bind_port(Port.KV_LEN, length)

    def epilogue():
        logits = intrinsics.logits()
        r = rng_ch.take()
        g = gumbel(r, [intrinsics.vocab()])
        t = reduce_argmax(mask_apply(logits, mask.take()) + g)
        rng_ch.put_tensor(r + ctr1)
        tok.put_tensor(t)
        length.put_tensor(length.take() + 1)
        out.put_tensor(t)

    b.stage(Stage.EPILOGUE, epilogue)
    host_put(mask, [True] * vocab)
    traced = b.build()
    assert traced.identity_hash() == 4213522552817221928
    check("s3", traced)


def test_text_completion_decode():
    n = 5
    page_size = PAGE
    tok_in = ch_from([42], dtype.i32, "tok_in")
    embed_indptr = ch_from([0, 1], dtype.u32, "embed_indptr")
    positions = ch_from([n], dtype.u32, "positions")
    pages = ch_from(list(range(3)), dtype.u32, "pages")
    page_indptr = ch_from([0, -(-(n + 1) // page_size)], dtype.u32, "page_indptr")
    w_slot = ch_from([n // page_size], dtype.u32, "w_slot")
    w_off = ch_from([n % page_size], dtype.u32, "w_off")
    kv_len = ch_from([n + 1], dtype.u32, "kv_len")
    tok_out = ch_new([1], dtype.i32, "tok_out")

    b = Builder(VOCAB, PAGE)
    for port, c in [
        (Port.EMBED_TOKENS, tok_in),
        (Port.EMBED_INDPTR, embed_indptr),
        (Port.KV_LEN, kv_len),
        (Port.PAGES, pages),
        (Port.PAGE_INDPTR, page_indptr),
        (Port.W_SLOT, w_slot),
        (Port.W_OFF, w_off),
        (Port.POSITIONS, positions),
    ]:
        b.bind_port(port, c)

    def epilogue():
        length = kv_len.take()
        next_length = length + 1
        page_count = next_length.div_ceil(page_size)
        kv_len.put_tensor(next_length)
        positions.put_tensor(length)
        w_slot.put_tensor(length // page_size)
        w_off.put_tensor(length % page_size)
        page_indptr.put_tensor(indptr(1, page_count))
        tok_out.put_tensor(reshape(reduce_argmax(intrinsics.logits()), [1]))

    b.stage(Stage.EPILOGUE, epilogue)
    tok_out.note_host_take()
    check("text_completion_decode", b.build())


def test_naive_decode():
    n = 7
    page_size = PAGE
    temperature = 0.7
    cap = 8
    tok_in = ch_from([3], dtype.i32, "tok_in")
    rng_ch = ch_from([0x7CE1 ^ 0x5BD1, 0], dtype.u32, "rng")
    tok_out = ch_new([1], dtype.i32, "tok_out").capacity(cap)
    s1_out = ch_new([1], dtype.f32, "s1_out").capacity(cap)
    s2_out = ch_new([1], dtype.f32, "s2_out").capacity(cap)
    lane1 = ch_from([0, 1], dtype.u32, "embed_indptr")
    positions = ch_from([n], dtype.u32, "positions")
    pages = ch_from(list(range(4)), dtype.u32, "pages")
    page_indptr = ch_from([0, -(-(n + 1) // page_size)], dtype.u32, "page_indptr")
    w_slot = ch_from([n // page_size], dtype.u32, "w_slot")
    w_off = ch_from([n % page_size], dtype.u32, "w_off")
    kv_len = ch_from([n + 1], dtype.u32, "kv_len")

    b = Builder(VOCAB, PAGE)
    for port, c in [
        (Port.EMBED_TOKENS, tok_in),
        (Port.EMBED_INDPTR, lane1),
        (Port.KV_LEN, kv_len),
        (Port.PAGES, pages),
        (Port.PAGE_INDPTR, page_indptr),
        (Port.W_SLOT, w_slot),
        (Port.W_OFF, w_off),
        (Port.POSITIONS, positions),
    ]:
        b.bind_port(port, c)

    def epilogue():
        length = kv_len.take()
        r = rng_ch.take()
        logits = intrinsics.logits()
        scaled = logits / temperature
        token = gumbel_max(scaled, r)
        r_next = r + iota(2)
        next_length = length + 1
        page_count = next_length.div_ceil(page_size)
        tok_in.put_tensor(token)
        kv_len.put_tensor(next_length)
        positions.put_tensor(length)
        w_slot.put_tensor(length // page_size)
        w_off.put_tensor(length % page_size)
        page_indptr.put_tensor(indptr(1, page_count))
        tok_out.put_tensor(token)
        mirror = reshape(cast(token, dtype.f32), [1])
        s1_out.put_tensor(mirror)
        s2_out.put_tensor(mirror)
        rng_ch.put_tensor(r_next)

    b.stage(Stage.EPILOGUE, epilogue)
    tok_out.note_host_take()
    s1_out.note_host_take()
    s2_out.note_host_take()
    check("naive_decode", b.build())


def test_coverage():
    k = 8
    tok = ch_from([1], dtype.i32, "tok")
    indptr_ch = ch_from([0, 1], dtype.u32, "indptr")
    rng_ch = ch_from([1, 2], dtype.u32, "rng")
    top_p = ch_from([0.9], dtype.f32, "top_p")
    bias = ch_from([0.0, -1.5, 2.25, 0.0], dtype.f32, "bias")
    out = ch_new([1], dtype.i32, "out")
    stat = ch_new([1], dtype.f32, "stat")
    stat2 = ch_new([4], dtype.f32, "stat2")
    flag = ch_new([1], dtype.bool, "flag")

    b = Builder(VOCAB, PAGE)
    b.bind_port(Port.EMBED_TOKENS, tok)
    b.bind_port(Port.EMBED_INDPTR, indptr_ch)

    def epilogue():
        logits = intrinsics.logits()
        r = rng_ch.take()
        p = softmax(logits)
        lp = log_softmax(logits)
        h = entropy(p)
        h2 = entropy_from_logprobs(p, lp)
        tv, ti = top_k(logits, k)
        keep = pivot_threshold(p, cummass_le(top_p.read()))
        keep2 = pivot_threshold(p, rank_le(Tensor.constant(40, Dtype.U32)))
        keep3 = pivot_threshold(p, prob_ge(0.01))
        both = and_(and_(keep, keep2), not_(keep3))
        masked = mask_apply(logits, or_(both, lt(logits, 0.0)))
        t1 = nucleus_sample(masked, top_p.read(), r)
        t2 = masked_argmax(logits, keep)
        t3 = gumbel_max(logits, r)
        g = gather(logits, cast(ti, dtype.u32))
        g2 = scalar_gather(logits, cast(t1, dtype.u32))
        ssum = reduce_sum(tv) + reduce_max(tv) - reduce_min(tv)
        cs = cumsum(tv) * cumprod(exp(tv))
        sv, _si = sort_desc(logits)
        l2 = l2norm(reshape(sv, [VOCAB]))
        m = matmul(reshape(tv, [1, k]), transpose(reshape(tv, [1, k])))
        sel = select(gt(t1, t2), t1, t3)
        sc = scatter_set(logits, cast(t2, dtype.u32), -1.0)
        sa = scatter_add(sc, cast(t3, dtype.u32), 1.0)
        ge_ = ge(sa, 0.5)
        cm = causal_mask(iota(4), 8)
        sw = sliding_window_mask(iota(4), 8, 3)
        sk = sink_window_mask(iota(4), 8, 1, 3)
        mem = row_membership(reshape(iota(8), [2, 4]), iota(3))
        u = rng(r, [4])
        bb = bias.read() + u
        extra = (
            abs_(recip(sign(neg(bb))))
            + log(exp(bb))
            + max_elem(bb, 1.0)
            - min_elem(bb, 2.0)
            + rem(bb, 3.0)
        )
        flag_v = (
            reduce_sum(cast(cm, dtype.u32))
            + reduce_sum(cast(sw, dtype.u32))
            + reduce_sum(cast(sk, dtype.u32))
            + reduce_sum(cast(mem, dtype.u32))
            + reduce_sum(cast(ge_, dtype.u32))
        )
        total = (
            h
            + h2
            + ssum
            + reduce_sum(cs)
            + reduce_sum(l2)
            + reduce_sum(reshape(m, [1]))
            + reduce_sum(g)
            + g2
            + reduce_sum(extra)
            + cast(flag_v, dtype.f32)
            + cast(eq(t1, t2), dtype.f32)
            + cast(ne(t1, t3), dtype.f32)
            + cast(le(t2, t3), dtype.f32)
        )
        stat.put_tensor(reshape(total, [1]))
        stat2.put_tensor(extra)
        flag.put_tensor(reshape(gt(total, 0.0), [1]))
        out.put_tensor(reshape(sel, [1]))
        rng_ch.put_tensor(r + iota(2))

    b.stage(Stage.EPILOGUE, epilogue)
    out.note_host_take()
    stat.note_host_take()
    stat2.note_host_take()
    flag.note_host_take()
    check("coverage", b.build())


def test_sinks():
    tok = ch_from([1], dtype.i32, "tok")
    indptr_ch = ch_from([0, 1], dtype.u32, "indptr")
    a = ch_new([2, 4, 8], dtype.f32, "a")
    bch = ch_new([2, 8, 4], dtype.f32, "b")
    out = ch_new([1], dtype.i32, "out")
    host_put(a, [0.0] * 64)
    host_put(bch, [0.0] * 64)

    b = Builder(VOCAB, PAGE)
    b.bind_port(Port.EMBED_TOKENS, tok)
    b.bind_port(Port.EMBED_INDPTR, indptr_ch)

    def prologue():
        intrinsics.kernel.lora(a.read(), bch.read(), Tensor.constant(1 | 4, Dtype.U32))
        intrinsics.kernel.attn_page_mask(iota(4))

    def on_attn_proj():
        intrinsics.query(16)
        intrinsics.kernel.envelope_dot(4)
        intrinsics.kernel.attn_page_mask(
            cast(gt(intrinsics.kernel.envelope_dot(4), 0.0), dtype.u32) + intrinsics.layer()
        )

    def epilogue():
        out.put_tensor(reshape(reduce_argmax(intrinsics.logits()), [1]))

    b.stage(Stage.PROLOGUE, prologue)
    b.stage(Stage.ON_ATTN_PROJ, on_attn_proj)
    b.stage(Stage.EPILOGUE, epilogue)
    out.note_host_take()
    check("sinks", b.build())


def test_bulk_constant_is_refused():
    from inferlet.eta.trace import TraceError

    tok = ch_from([1], dtype.i32, "tok")
    indptr_ch = ch_from([0, 1], dtype.u32, "indptr")
    out = ch_new([4], dtype.f32, "out")
    b = Builder(VOCAB, PAGE)
    b.bind_port(Port.EMBED_TOKENS, tok)
    b.bind_port(Port.EMBED_INDPTR, indptr_ch)
    b.stage(Stage.EPILOGUE, lambda: out.put_tensor(Tensor.constant([1.0, 2.0, 5.0, 7.0]) + 0.0))
    out.note_host_take()
    with pytest.raises(TraceError, match="bulk data"):
        b.build()


def test_readiness_lint():
    from inferlet.eta.trace import TraceError

    tok = ch_from([1], dtype.i32, "tok")
    indptr_ch = ch_from([0, 1], dtype.u32, "indptr")
    never = ch_new([1], dtype.f32, "never")
    out = ch_new([1], dtype.f32, "out")
    b = Builder(VOCAB, PAGE)
    b.bind_port(Port.EMBED_TOKENS, tok)
    b.bind_port(Port.EMBED_INDPTR, indptr_ch)
    b.stage(Stage.EPILOGUE, lambda: out.put_tensor(never.take() + 1.0))
    out.note_host_take()
    with pytest.raises(TraceError, match="never produced"):
        b.build()


def _epilogue_bytes(body) -> bytes:
    vocab = 32_000
    tok = ch_new([1], dtype.i32, "tok")
    indptr_ch = ch_from([0, 1], dtype.u32, "indptr")
    out = ch_new([vocab], dtype.bool, "out")
    host_put(tok, [1], dtype.i32)
    b = Builder(vocab, 16)
    b.bind_port(Port.EMBED_TOKENS, tok)
    b.bind_port(Port.EMBED_INDPTR, indptr_ch)
    b.stage(Stage.EPILOGUE, lambda: out.put_tensor(body(intrinsics.logits())))
    return b.build().encode()


def test_comparison_operators_are_the_free_functions():
    """`t < x` etc. emit exactly what `lt(t, x)` emits, in both operand
    orders (Python reflects `x < t` into `t.__gt__(x)`)."""
    assert _epilogue_bytes(lambda l: l < 0.5) == _epilogue_bytes(lambda l: lt(l, 0.5))
    assert _epilogue_bytes(lambda l: l >= 0.5) == _epilogue_bytes(lambda l: ge(l, 0.5))
    assert _epilogue_bytes(lambda l: 0.5 < l) == _epilogue_bytes(lambda l: gt(l, 0.5))
    assert _epilogue_bytes(lambda l: 0.5 >= l) == _epilogue_bytes(lambda l: le(l, 0.5))
    # `==` stays identity, so a Tensor can key a dict / sit in a set.
    t = Tensor.constant(1)
    assert {t: "x"}[t] == "x" and t != Tensor.constant(1)
