#!/usr/bin/env python3
"""Writes src/star/ops.rs: a Starlark binding for every op of src/ops/*.rs
whose parameters and result a package can spell.

Run it, then `cargo fmt`, after adding or changing an op; the test
`every_op_a_package_can_spell_is_bound` fails until it has been run.
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODULES = ["attn", "collective", "elemwise", "layout", "linear", "spatial"]

# Rust parameter type -> (the type it is unpacked as, how the op is passed it)
PARAMS = {
    "&Value": ("Value", "&{}"),
    "&Weight": ("Weight", "&{}"),
    "ValueId": ("Cache", "{}.0"),
    "Option<ValueId>": ("Option<Cache>", "{}.map(|c| c.0)"),
    "&Input": ("Input", "&{}"),
    "u32": ("u32", "{}"),
    "f32": ("f32", "{}"),
    "bool": ("bool", "{}"),
    "Dtype": ("Dtype", "{}"),
    "Option<u32>": ("Option<u32>", "{}"),
    "Option<f32>": ("Option<f32>", "{}"),
    "Option<&Value>": ("Option<Value>", "{}.as_ref()"),
    "Option<&Weight>": ("Option<Weight>", "{}.as_ref()"),
    "Option<(u32, f32)>": ("Option<(u32, f32)>", "{}"),
    "[u32; 3]": ("[u32; 3]", "{}"),
    "[u32; 4]": ("[u32; 4]", "{}"),
    "[f32; 4]": ("[f32; 4]", "{}"),
    "&[u64]": ("Vec<u64>", "&{}"),
    "&[Value]": ("Vec<Value>", "&{}"),
    "&[&Value]": ("Vec<Value>", "&{}.iter().collect::<Vec<_>>()"),
    "GateActivation": ("GateActivation", "{}"),
    "RopeForm": ("RopeForm", "{}"),
    "MropeForm": ("MropeForm", "{}"),
    "ModulateForm": ("ModulateForm", "{}"),
    "Option<Yarn>": ("Option<Yarn>", "{}"),
    "GridRule": ("GridRule", "{}"),
    "Conv": ("Conv", "{}"),
    "VoxelSegment": ("VoxelSegment", "{}"),
    "RaggedMask": ("RaggedMask", "{}"),
}
RESULTS = {"Value", "(Value, Value)", "(Value, Value, Value)", "()", "RaggedMask"}


def split(params):
    depth, cur, out = 0, "", []
    for ch in params:
        if ch in "<([":
            depth += 1
        if ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [" ".join(p.split()) for p in out]


def ops():
    pattern = re.compile(
        r"^pub fn (\w+)\((.*?)\)\s*(?:->\s*([^{]*?))?\s*\{", re.S | re.M
    )
    for module in MODULES:
        text = (ROOT / "src/ops" / f"{module}.rs").read_text()
        for m in pattern.finditer(text):
            name, params, result = m.group(1), split(m.group(2)), (m.group(3) or "()").strip()
            yield module, name, [tuple(p.split(": ", 1)) for p in params], result


def main():
    bound, skipped = [], []
    for module, name, params, result in ops():
        unspelled = [t for _, t in params if t not in PARAMS]
        if unspelled or result not in RESULTS:
            skipped.append(f"{module}::{name}")
            continue
        names = ", ".join(f'"{p}"' for p, _ in params)
        takes = "".join(
            f"        let {p}: {PARAMS[t][0]} = a.next()?;\n" for p, t in params
        )
        passes = ", ".join(PARAMS[t][1].format(p) for p, t in params)
        bound.append(
            f"    Op {{\n"
            f'        module: "{module}",\n'
            f'        name: "{name}",\n'
            f"        params: &[{names}],\n"
            f"        call: |a, heap| {{\n"
            f"{takes}"
            f'            result(heap, dsl("{module}.{name}", || ops::{module}::{name}({passes}))?)\n'
            f"        }},\n"
            f"    }},\n"
        )
    takes_fix = []
    for b in bound:
        takes_fix.append(b.replace("        let ", "            let "))
    out = (
        "//! Generated by `tools/bind_ops.py` from `src/ops/*.rs`; do not edit.\n"
        "//!\n"
        "//! Every op a package can spell the arguments and result of. Not bound:\n"
        + "".join(f"//! `{s}`\n" for s in skipped)
        + "\n"
        "use crate::ops;\n"
        "use crate::star::bind::{Cache, Op, dsl, result};\n"
        "use crate::star::bind::spelled::*;\n\n"
        "pub(crate) static OPS: &[Op] = &[\n" + "".join(takes_fix) + "];\n"
    )
    (ROOT / "src/star/ops.rs").write_text(out)
    print(f"bound {len(bound)}, not bound {len(skipped)}: {', '.join(skipped)}")


if __name__ == "__main__":
    main()
