package pie:plex@0.5.0;

interface host {
    type action-id = u64;

    query: func(method: string, args-json: string) -> result<string, string>;
    action: func(method: string, args-json: string) -> result<action-id, string>;
}
