//! Do the `mlp` and `sample` units compile under NVRTC, and does every row
//! they state resolve to a mangled symbol?
//!
//! # The question this answers
//!
//! A row is three strings — a template path, an element type, and the symbol a
//! trace names — and nothing in the type system connects them to the `.cuh`
//! that has to hold the template. A row can name a kernel that was renamed, a
//! template that takes two arguments where the row supplies one, or a header
//! that stopped compiling under NVRTC the day someone reached for `<cstdint>`.
//! Every one of those is a clean `cargo build` and a fire that fails at run
//! time, on a machine with a GPU, in a process serving tokens.
//!
//! So this compiles each unit the way `runtime::cache` will — against the
//! header set carried in the binary, with the same float flags, one
//! `nvrtcAddNameExpression` per row — and refuses to be satisfied by anything
//! less than a lowered name for EVERY row and a non-empty cubin.
//!
//! ```text
//! cargo run -p kernels-cuda-new --features cuda-13 --example unit_probe_mlp
//! ```
//!
//! # Why `sample` is in a probe called `mlp`
//!
//! One migration, one probe. `mlp/swiglu`, `mlp/gaussian_topk` and
//! `sample/argmax` were split out of their `.cu`s in the same pass and share
//! every risk this file measures; a second file would duplicate two hundred
//! lines of FFI to report three more rows. `gemm` and `adapter` are absent
//! because they declare no unit — `families::gemm` and `families::adapter`
//! each say why, and neither reason is one a compile could test.
//!
//! # The second table: the kernels no row names
//!
//! Eleven templates in these headers are reachable only through an
//! ahead-of-time launcher, because their geometry fits no rule
//! [`kernels_cuda_new::runtime::launch`] evaluates — a half-width grid, a
//! block of 1024 or of 32, a `dim3(rows, tiles)`, a grid off an occupancy
//! query, or a choice made at run time from a pointer's alignment. Each
//! `.cuh` says which and why beside the kernel.
//!
//! NVRTC PARSES an uninstantiated template and does not instantiate it, and a
//! template that only fails when instantiated is exactly what a parse does not
//! find. `mlp/swiglu`'s vectorised kernels reinterpret their operands as
//! `bf16x2` and `sample/argmax`'s fused GEMVs load `char4` and `uint4` — none
//! of which a header this crate carries declares, so whether NVRTC knows those
//! vector types WITHOUT `<vector_types.h>` was an open question when this file
//! was written. So the second table instantiates them anyway, through rows the
//! probe owns and nothing fires. They live here rather than in
//! [`kernels_cuda_new::families::mlp`] because a `Unit` with rows in it is a
//! claim that the rows can be LAUNCHED, and these cannot.
//! `LaunchRule::Unstated` is the honest spelling of that: the row has not said.
//!
//! Two are left out and stay parse-only here: `select_lm_head_argmax_pairs`
//! and `argmax_finalize` are not templates — there is no element type in
//! either, only packed pairs and floats — and
//! [`kernels_cuda_new::device::DeviceKernel::instantiation`] spells exactly
//! one template argument. They need no instantiation to be checked: a plain
//! `__global__` is code-generated by every compile of the unit that holds it,
//! so the first table already compiles them.

#[cfg(feature = "_cuda")]
fn main() {
    imp::main();
}

/// `cargo test -p kernels-cuda-new` with no features builds every example, and
/// `cudarc` is only in the dependency graph under `_cuda`. The clean fix is a
/// `[[example]]` entry with `required-features = ["_cuda"]` in `Cargo.toml`;
/// this file may not add one — `Cargo.toml` belongs to another migration — so
/// it gates itself and leaves a `main` that explains the absence rather than a
/// link error that does not.
#[cfg(not(feature = "_cuda"))]
fn main() {
    println!(
        "unit_probe_mlp needs NVRTC. Re-run with `--features cuda-13` (or \
         `cuda-12`): the probe's whole content is a compile, and there is \
         nothing to report without a compiler."
    );
}

#[cfg(feature = "_cuda")]
mod imp {
    use std::ffi::{CStr, CString};

    use cudarc::nvrtc::sys as nv;
    use kernels::KernelSig;
    use kernels::LaunchRule;
    use kernels::kernel;
    use kernels::operands;
    use kernels_cuda_new::device::DeviceKernel;
    use kernels_cuda_new::source::{self, DEVICE_HEADERS};
    use kernels_cuda_new::unit::Unit;

    /// The vectorised SwiGLU kernels, instantiated by nothing else.
    ///
    /// Same root as `families::mlp::SWIGLU`, different rows: this is the
    /// unrowed half of the same file, and compiling it is how the `bf16x2`
    /// reinterpretation gets checked under NVRTC at all.
    const SWIGLU_UNROWED: Unit = Unit {
        name: "mlp/swiglu",
        root: include_str!("../csrc/src/mlp/swiglu.cuh"),
        rows: SWIGLU_UNROWED_ROWS,
        options: &[],
    };

    /// The ten argmax kernels whose launchers ask the device how big their
    /// grid should be, minus the two that are not templates.
    const ARGMAX_UNROWED: Unit = Unit {
        name: "sample/argmax",
        root: include_str!("../csrc/src/sample/argmax.cuh"),
        rows: ARGMAX_UNROWED_ROWS,
        options: &[],
    };

    static SWIGLU_UNROWED_ROWS: &[DeviceKernel] = &[
        DeviceKernel {
            sig: &UNROWED_SIGS[0],
            template_path: "mlp::device::chunked_swiglu_vec2",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[1],
            template_path: "mlp::device::chunked_swiglu_vec2_gate_second",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[2],
            template_path: "mlp::device::chunked_swiglu_strided_vec2",
            elem: "device::bf16",
        },
    ];

    static ARGMAX_UNROWED_ROWS: &[DeviceKernel] = &[
        DeviceKernel {
            sig: &UNROWED_SIGS[3],
            template_path: "sample::device::argmax_vec2",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[4],
            template_path: "sample::device::argmax_compact_scatter_vec2",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[5],
            template_path: "sample::device::masked_embedding_argmax",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[6],
            template_path: "sample::device::topk_centroids",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[7],
            template_path: "sample::device::masked_embedding_tile_argmax_pairs",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[8],
            template_path: "sample::device::argmax_accumulate",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[9],
            template_path: "sample::device::lm_head_gemv_argmax_int8",
            elem: "device::bf16",
        },
        DeviceKernel {
            sig: &UNROWED_SIGS[10],
            template_path: "sample::device::lm_head_gemv_argmax",
            elem: "device::bf16",
        },
    ];

    /// Sigs for the unrowed rows, and every one of them is a placeholder.
    ///
    /// `LaunchRule::Unstated` and no operands: the probe never launches these
    /// and must not appear to describe how to. What it needs from a
    /// [`KernelSig`] is the symbol — which is only ever printed — and what it
    /// needs from a [`DeviceKernel`] is the instantiation.
    #[rustfmt::skip]
    static UNROWED_SIGS: [KernelSig; 11] = [
        kernel!(chunked_swiglu_vec2 "mlp::chunked_swiglu_vec2_bf16",
            file = Some("mlp/swiglu.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(chunked_swiglu_vec2_gate_second "mlp::chunked_swiglu_vec2_gate_second_bf16",
            file = Some("mlp/swiglu.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(chunked_swiglu_strided_vec2 "mlp::chunked_swiglu_strided_vec2_bf16",
            file = Some("mlp/swiglu.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(argmax_vec2 "sample::argmax_vec2_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(argmax_compact_scatter_vec2 "sample::argmax_compact_scatter_vec2_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(masked_embedding_argmax "sample::masked_embedding_argmax_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(topk_centroids "sample::topk_centroids_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(masked_embedding_tile_argmax_pairs "sample::masked_embedding_tile_argmax_pairs_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(argmax_accumulate "sample::argmax_accumulate_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(lm_head_gemv_argmax_int8 "sample::lm_head_gemv_argmax_int8",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
        kernel!(lm_head_gemv_argmax "sample::lm_head_gemv_argmax_bf16",
            file = Some("sample/argmax.cuh"), launch = LaunchRule::Unstated, operands = operands![]),
    ];

    /// What one unit's compile produced.
    struct Report {
        rows: usize,
        /// Rows that came back from `nvrtcGetLoweredName`. Anything less than
        /// `rows` is a row naming a template its unit does not hold.
        lowered: usize,
        millis: f64,
        cubin_bytes: usize,
    }

    pub fn main() {
        let arch = kernels_cuda_new::runtime::cache::arch().unwrap_or("sm_89");
        println!("NVRTC version: {}", version());
        println!("architecture:  {arch}");
        println!("headers:       {} carried\n", DEVICE_HEADERS.len());

        let declared: Vec<&Unit> = kernels_cuda_new::families::mlp::UNITS
            .iter()
            .chain(kernels_cuda_new::families::sample::UNITS)
            .collect();

        println!("the units these families declare");
        let mut failed = report(&declared, arch);

        println!("\nthe kernels no row names, instantiated so the probe compiles them");
        failed += report(&[&SWIGLU_UNROWED, &ARGMAX_UNROWED], arch);

        println!();
        let rows: usize = declared.iter().map(|u| u.rows.len()).sum();
        if failed == 0 {
            println!(
                "{} declared units, {rows} rows: every unit compiled and every \
                 row got a lowered name.\nThe cubins are proof the templates \
                 exist and instantiate; they are NOT proof\nthat any row's \
                 LaunchRule reproduces its C++ launcher's grid.",
                declared.len()
            );
        } else {
            println!("{failed} unit(s) did not answer.");
            std::process::exit(1);
        }
    }

    /// Compile each unit, print a row of the table for it, and answer with how
    /// many did not compile or did not resolve every name.
    fn report(units: &[&Unit], arch: &str) -> usize {
        println!(
            "{:<28} {:>5} {:>8} {:>10} {:>12}",
            "unit", "rows", "lowered", "ms", "cubin bytes"
        );
        println!("{}", "-".repeat(74));

        let mut failed = 0usize;
        for unit in units {
            match compile(unit, arch) {
                Ok(report) => {
                    let ok = report.lowered == report.rows && report.cubin_bytes > 0;
                    if !ok {
                        failed += 1;
                    }
                    println!(
                        "{:<28} {:>5} {:>8} {:>10.0} {:>12}  {}",
                        unit.name,
                        report.rows,
                        report.lowered,
                        report.millis,
                        report.cubin_bytes,
                        if ok { "OK" } else { "MISSING NAMES" }
                    );
                }
                Err(log) => {
                    failed += 1;
                    println!(
                        "{:<28} {:>5} {:>8} {:>10} {:>12}  FAILED",
                        unit.name,
                        unit.rows.len(),
                        0,
                        "-",
                        "-"
                    );
                    for line in log.lines().take(12) {
                        println!("    {line}");
                    }
                }
            }
        }
        failed
    }

    /// Compile one unit exactly as `runtime::nvrtc` does — same headers, same
    /// float flags, same name expressions.
    ///
    /// The flags are copied rather than called because `runtime::nvrtc`'s
    /// compile is private to the fire path. They are not decoration:
    /// `--fmad=false`, `--prec-div=true` and `--prec-sqrt=true` are in
    /// `Unit::cache_key` because the arithmetic a cubin was built under is
    /// part of what it answers, and a probe compiling without them would be
    /// measuring a different cubin than the one the driver serves.
    fn compile(unit: &Unit, arch: &str) -> Result<Report, String> {
        let (texts, names) = source::as_nvrtc_arrays(DEVICE_HEADERS)?;
        let text_ptrs: Vec<*const i8> = texts.iter().map(|t| t.as_ptr()).collect();
        let name_ptrs: Vec<*const i8> = names.iter().map(|n| n.as_ptr()).collect();

        let src = CString::new(unit.root).map_err(|_| "a NUL in the root".to_string())?;
        let root_name = CString::new(format!("{}.cuh", unit.name)).unwrap();
        let mut program: nv::nvrtcProgram = std::ptr::null_mut();
        // SAFETY: every string outlives the call, and the two arrays are
        // `DEVICE_HEADERS.len()` long, which is the count passed.
        let code = unsafe {
            nv::nvrtcCreateProgram(
                &raw mut program,
                src.as_ptr(),
                root_name.as_ptr(),
                i32::try_from(text_ptrs.len()).unwrap(),
                text_ptrs.as_ptr(),
                name_ptrs.as_ptr(),
            )
        };
        if code != nv::nvrtcResult::NVRTC_SUCCESS {
            return Err(format!("nvrtcCreateProgram: {code:?}"));
        }

        // One name expression per row, added BEFORE the compile: NVRTC only
        // instantiates a template it was asked for by name, and a row added
        // after the fact gets no mangled symbol and no code.
        let instantiations = unit.instantiations();
        let expressions: Vec<CString> = instantiations
            .iter()
            .map(|i| CString::new(i.as_str()).expect("no NULs in an instantiation"))
            .collect();
        for expression in &expressions {
            // SAFETY: `program` is live and the string outlives the call.
            let code = unsafe { nv::nvrtcAddNameExpression(program, expression.as_ptr()) };
            if code != nv::nvrtcResult::NVRTC_SUCCESS {
                return Err(format!("nvrtcAddNameExpression: {code:?}"));
            }
        }

        let gpu = CString::new(format!("--gpu-architecture={arch}")).unwrap();
        let mut options = vec![
            gpu.as_ptr(),
            c"-std=c++17".as_ptr(),
            c"--fmad=false".as_ptr(),
            c"--prec-div=true".as_ptr(),
            c"--prec-sqrt=true".as_ptr(),
        ];
        let extra: Vec<CString> = unit
            .options
            .iter()
            .map(|o| CString::new(*o).expect("no NULs in an option"))
            .collect();
        options.extend(extra.iter().map(|o| o.as_ptr()));

        let started = std::time::Instant::now();
        // SAFETY: `program` came from a successful create; the options outlive it.
        let code = unsafe {
            nv::nvrtcCompileProgram(
                program,
                i32::try_from(options.len()).unwrap(),
                options.as_ptr(),
            )
        };
        let millis = started.elapsed().as_secs_f64() * 1e3;

        if code != nv::nvrtcResult::NVRTC_SUCCESS {
            let log = log_of(program);
            // SAFETY: destroyed exactly once, and not used after.
            unsafe { nv::nvrtcDestroyProgram(&raw mut program) };
            return Err(log);
        }

        // The lowered names, one per row. Asked for BEFORE the program is
        // destroyed, because NVRTC owns the strings it returns.
        let mut lowered = 0usize;
        for (at, expression) in expressions.iter().enumerate() {
            let mut name: *const i8 = std::ptr::null();
            // SAFETY: `program` is live and compiled; `name` is an out-parameter
            // NVRTC fills with a pointer it owns.
            let code =
                unsafe { nv::nvrtcGetLoweredName(program, expression.as_ptr(), &raw mut name) };
            if code == nv::nvrtcResult::NVRTC_SUCCESS && !name.is_null() {
                lowered += 1;
            } else {
                println!("    row {at} has no lowered name: {}", instantiations[at]);
            }
        }

        let mut size = 0;
        // SAFETY: `program` is live and `size` is a live out-parameter.
        unsafe { nv::nvrtcGetCUBINSize(program, &raw mut size) };
        let mut cubin = vec![0u8; size.max(1)];
        // SAFETY: the buffer is `size` bytes, which is what NVRTC just asked for.
        unsafe { nv::nvrtcGetCUBIN(program, cubin.as_mut_ptr().cast()) };
        // SAFETY: destroyed exactly once, and not used after.
        unsafe { nv::nvrtcDestroyProgram(&raw mut program) };

        Ok(Report {
            rows: unit.rows.len(),
            lowered,
            millis,
            cubin_bytes: size,
        })
    }

    /// The program log, as a `String`.
    fn log_of(program: nv::nvrtcProgram) -> String {
        let mut size = 0;
        // SAFETY: `program` is live and `size` is a live out-parameter.
        unsafe { nv::nvrtcGetProgramLogSize(program, &raw mut size) };
        let mut log = vec![0u8; size.max(1)];
        // SAFETY: the buffer is `size` bytes, which is what NVRTC just asked for.
        unsafe { nv::nvrtcGetProgramLog(program, log.as_mut_ptr().cast()) };
        CStr::from_bytes_until_nul(&log)
            .map_or_else(|_| String::new(), |s| s.to_string_lossy().into_owned())
    }

    /// `libnvrtc`'s own version, so a report says which compiler answered.
    fn version() -> String {
        let (mut major, mut minor) = (0, 0);
        // SAFETY: both are live out-parameters for the call's duration.
        let code = unsafe { nv::nvrtcVersion(&raw mut major, &raw mut minor) };
        if code == nv::nvrtcResult::NVRTC_SUCCESS {
            format!("{major}.{minor}")
        } else {
            format!("unavailable ({code:?})")
        }
    }
}
