"""Pixel animals for the chat banner: 16 columns by 16 rows of art, drawn at 16x6 with quadrant blocks."""

ANIMALS = {
    "bear": (
        {"K": (24, 24, 28), "b": (139, 90, 43), "t": (214, 172, 120)},
        [
            "................",
            "..KKK......KKK..",
            ".KbbbK....KbbbK.",
            ".KbtbKKKKKKbtbK.",
            ".KbbbbbbbbbbbbK.",
            ".KbbbbbbbbbbbbK.",
            ".KbbKKbbbbKKbbK.",
            ".KbbKKbbbbKKbbK.",
            ".KbbbbttttbbbbK.",
            ".KbbbttKKttbbbK.",
            ".KbbbtKttKtbbbK.",
            ".KbbbbttttbbbbK.",
            "..KbbbbbbbbbbK..",
            "...KKbbbbbbKK...",
            ".....KKKKKK.....",
            "................",
        ],
    ),
    "frog": (
        {
            "d": (28, 88, 32),
            "g": (120, 192, 60),
            "l": (185, 228, 115),
            "W": (255, 255, 255),
            "K": (24, 24, 28),
        },
        [
            "..dddd....dddd..",
            ".dWWWWd..dWWWWd.",
            ".dWKKWd..dWKKWd.",
            ".dWKKWddddWKKWd.",
            "dggggggggggggggd",
            "dggggggggggggggd",
            "dggKKKKKKKKKKggd",
            "dggggggggggggggd",
            ".dgggllllllgggd.",
            ".dggllllllllggd.",
            ".dggllllllllggd.",
            ".dgdgllllllgdgd.",
            "dggddggggggddggd",
            "dddd.dddddd.dddd",
            "................",
            "................",
        ],
    ),
    "cat": (
        {
            "K": (24, 24, 28),
            "o": (245, 140, 40),
            "d": (205, 100, 22),
            "p": (250, 182, 170),
        },
        [
            ".K............K.",
            ".KK..........KK.",
            ".KoK........KoK.",
            ".KpoK......KopK.",
            ".KppoKKKKKKoppK.",
            ".KooooooooooooK.",
            ".KooooooooooooK.",
            ".KooKKooooKKooK.",
            ".KooKKooooKKooK.",
            "KKooooooooooooKK",
            ".KoooooKKoooooK.",
            "KKooooKooKooooKK",
            ".KooooooooooooK.",
            "..KooooooooooK..",
            "..KoddooooddoK..",
            "..KKKKKKKKKKKK..",
        ],
    ),
    "fox": (
        {"K": (24, 24, 28), "o": (240, 120, 30), "c": (255, 236, 205)},
        [
            ".K............K.",
            ".KK..........KK.",
            ".KoK........KoK.",
            ".KcoK......KocK.",
            ".KccoKKKKKKoccK.",
            ".KooooooooooooK.",
            ".KooooooooooooK.",
            ".KooKKooooKKooK.",
            "KccooooooooooccK",
            ".KcccccKKcccccK.",
            "..KccccKKccccK..",
            "...KccccccccK...",
            "..KoKccccccKoK..",
            "..KooccccccooK..",
            "..KoKccccccKoK..",
            "..KKKKKKKKKKKK..",
        ],
    ),
    "chick": (
        {
            "K": (24, 24, 28),
            "y": (250, 215, 50),
            "s": (222, 176, 28),
            "r": (220, 40, 40),
            "o": (245, 110, 30),
        },
        [
            ".......rr.......",
            "......rrrr......",
            ".....KKKKKK.....",
            "....KyyyyyyK....",
            "...KyyyyyyyyK...",
            "..KyyKyyyyKyyK..",
            "..KyyKyyyyKyyK..",
            "..KyyyyooyyyyK..",
            "..KyyyooooyyyK..",
            ".KyyyyyooyyyyyK.",
            "KsyyyyyyyyyyyysK",
            "KssyyyyyyyyyyssK",
            ".KsyyyyyyyyyysK.",
            "..KsyyyyyyyysK..",
            "...KKKKKKKKKK...",
            "....oo....oo....",
        ],
    ),
    "sheep": (
        {
            "K": (24, 24, 28),
            "w": (250, 250, 250),
            "l": (205, 205, 210),
            "g": (130, 130, 136),
            "d": (78, 78, 84),
        },
        [
            "...KK.KKKK.KK...",
            "..KwwKwwwwKwwK..",
            ".KwwwwwwwwwwwwK.",
            "KwwwwwwwwwwwwwwK",
            "KddKggggggggKddK",
            "KdddggggggggdddK",
            ".KwwgKggggKgwwK.",
            ".KwwgKggggKgwwK.",
            "KwwwggggggggwwwK",
            "KwwwgggddgggwwwK",
            "KwwwwggggggwwwwK",
            "KwlwwwwwwwwwwlwK",
            ".KwllwwwwwwllwK.",
            "..KKKKKKKKKKKK..",
            "...Kd......dK...",
            "...KK......KK...",
        ],
    ),
    "raccoon": (
        {
            "g": (120, 118, 118),
            "l": (176, 172, 170),
            "s": (90, 88, 88),
            "d": (36, 34, 36),
            "w": (236, 232, 228),
            "n": (30, 28, 28),
        },
        [
            "................",
            "................",
            "..ddd......ddd..",
            ".ddlld.gg.dlldd.",
            ".dllggllllgglld.",
            "..dgllllllllgd..",
            "..dddddddddddd..",
            "..dddwwdddwwdd..",
            ".gddddddddddddg.",
            ".gggggwwwwggggg.",
            "..gggwwnnwwggg..",
            "..ggwwwwwwwwgg..",
            "...gwwwddwwwg...",
            "....swwwwwws....",
            ".......ss.......",
            "................",
        ],
    ),
}
