#pragma once

/* Generated by pie-forward-cbindgen (cbindgen). Do not edit by hand. Regenerate: cargo run -p pie-forward-cbindgen */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

namespace pie_forward {

/// `PieForwardOp::weight_name` when the op references no weight.
constexpr static const uint32_t PIE_FORWARD_NO_NAME = UINT32_MAX;

/// `PieForwardOp::selector` when the op selects no per-token weights —
/// every op except the expert-indexed `Matmul`s of an MoE trace.
constexpr static const uint32_t PIE_FORWARD_NO_VALUE = UINT32_MAX;

/// `PieForwardOp::layer` for prologue/epilogue ops (embed, final norm,
/// lm_head). Signed so the resting value cannot collide with a real layer.
constexpr static const int32_t PIE_FORWARD_NO_LAYER = -1;

/// Inline dim capacity of [`PieForwardValue`]. The tracer emits rank-2
/// shapes plus the MoE trace's rank-3 route-expanded `[Tokens, k, d]`
/// values; 4 leaves headroom without an arena run per value.
constexpr static const size_t PIE_FORWARD_MAX_DIMS = 4;

enum class PieForwardStatus : uint32_t {
  Ok = 0,
  /// The request was malformed: a null pointer or an out-of-range enum.
  /// The caller built the request wrong.
  InvalidArgument = 1,
};

/// The tag of one [`PieForwardDim`]: which extent a dim is symbolic in, or
/// that it is a load-time constant. Mirrors [`crate::trace::Dim`].
enum class PieForwardDimKind : uint32_t {
  /// The fire's token rows (`N`).
  Tokens = 0,
  /// The fire's request rows (`R`).
  Requests = 1,
  /// A load-time constant; the extent is [`PieForwardDim::value`].
  Const = 2,
};

/// Mirrors [`crate::trace::DType`]; same appended-only discriminant rule as
/// [`PieForwardOpKind`].
enum class PieForwardDType : uint32_t {
  BF16 = 0,
  F32 = 1,
  I32 = 2,
};

/// The op vocabulary, as stable wire values.
///
/// Discriminants are the ABI, not a declaration order: append new kinds
/// after the last value and never renumber, exactly the discipline
/// `loader/src/ffi/types.rs` states on `PieLoaderDType`.
enum class PieForwardOpKind : uint32_t {
  Embed = 0,
  Matmul = 1,
  Rmsnorm = 2,
  RmsnormPerHead = 3,
  SplitQkv = 4,
  Rope = 5,
  KvAppend = 6,
  Attention = 7,
  Swiglu = 8,
  LmHead = 9,
  /// `residual += x` (post-norm placement's separate landing). Appended
  /// per the discipline above — the nine kinds before it keep their
  /// wire values.
  ResidualAdd = 10,
  /// Router top-k + softmax + renormalize (one launch in the hand-written
  /// MoE pass). First of the `dyn` kinds — the declared executors do NOT
  /// consume these; their op-kind switches throw on them via the loud
  /// default arm, which is the intended v0 behaviour (the grouped-GEMM
  /// emission is a later, much larger lift).
  TopK = 11,
  /// Per-token combine of the k routed expert outputs.
  WeightedSum = 12,
  /// `out = base + sigmoid(gate) * x` (shared-expert landing).
  SigmoidGateAdd = 13,
  /// Two-way GDN split (`[rows, w0 + w1]` → two results). First of the
  /// GDN kinds (the `pie_forward_trace_qwen3_5_gdn` fragment) — like the
  /// dyn kinds above, the declared executors do NOT consume these; their
  /// op-kind switches throw on them via the loud default arm.
  SplitGdn = 14,
  /// Depthwise causal conv1d + fused SiLU against the layer's implicit
  /// PER-REQUEST conv state.
  CausalConv1d = 15,
  /// Post-conv GDN prep: q/k/v/g/beta from the packed conv output and
  /// the a/b projections plus the a_log/dt_bias parameters (five
  /// results; the one kind that names TWO weights — see the op table).
  GdnPrep = 16,
  /// The gated-delta recurrence against the layer's implicit PER-REQUEST
  /// recurrent state. Opaque like `Attention`.
  GatedDelta = 17,
  /// Per-head gated RMSNorm: `w * rmsnorm(x) * silu(gate)`, plain fold.
  RmsnormGated = 18,
};

/// Mirrors [`crate::trace::NormVariant`].
enum class PieForwardNormVariant : uint32_t {
  Plain = 0,
  Gemma = 1,
};

/// Mirrors [`crate::trace::RopeKind`].
enum class PieForwardRopeKind : uint32_t {
  Standard = 0,
  /// Llama3/YaRN-style frequency scaling.
  Yarn = 1,
};

/// Mirrors [`crate::facts::NormPlacement`].
enum class PieForwardNormPlacement : uint32_t {
  Pre = 0,
  /// OLMo-2/3: norm the sub-layer OUTPUT, then a separate residual add.
  Post = 1,
};

/// Mirrors [`crate::facts::QkNorm`]. `Off`/`PerHead` keep the wire values
/// the field had as a bool (0/1), so a caller that treated it as "non-zero
/// is per-head qk-norm" still states the same facts.
enum class PieForwardQkNorm : uint32_t {
  Off = 0,
  PerHead = 1,
  /// One RMSNorm over the flattened `[heads * head_dim]` q/k projection
  /// (OLMo-2) — different arithmetic from per-head.
  Global = 2,
};

/// The llama_like facts, as C states them. Mirrors
/// [`crate::facts::LlamaLikeFacts`] field for field.
///
/// `rope` and `norm_variant` are plain `uint32_t` rather than their enum
/// types for the input-side rule `loader/src/ffi/entry.rs` states on
/// `PieLoaderTargetSpec`: C++ lets a caller store any integer in an
/// enum-typed field, and reading such a field as a Rust enum is undefined
/// behaviour *before* any check could reject it. Assign
/// `static_cast<uint32_t>(PieForwardRopeKind::Standard)`; the tracer
/// validates the value and answers [`PieForwardStatus::InvalidArgument`] if
/// it is not one of them. The bools are `uint8_t` (zero is false) for the
/// same reason C ABIs avoid `bool` in input structs: every bit pattern is a
/// valid `u8`.
struct PieForwardLlamaLikeFacts {
  uint32_t hidden;
  uint32_t layers;
  uint32_t q_heads;
  uint32_t kv_heads;
  uint32_t head_dim;
  uint32_t intermediate;
  uint32_t vocab;
  /// A [`super::types::PieForwardRopeKind`] value.
  uint32_t rope;
  /// A [`super::types::PieForwardNormVariant`] value.
  uint32_t norm_variant;
  /// A [`super::types::PieForwardNormPlacement`] value.
  uint32_t norm_placement;
  /// A [`super::types::PieForwardQkNorm`] value. (Formerly a 0/1 bool;
  /// `Off`/`PerHead` keep those wire values.)
  uint32_t qk_norm;
  /// The deployment bound one packed QKV projection; non-zero is true.
  uint8_t fused_qkv;
  /// The lm_head weight is the embedding table; non-zero is true.
  uint8_t tied_embeddings;
};

/// One symbolic extent. `value` is meaningful only under
/// [`PieForwardDimKind::Const`] and rests at zero otherwise.
struct PieForwardDim {
  PieForwardDimKind kind;
  uint32_t value;
};

/// One SSA value of the traced form. Dims are inline rather than an arena
/// run because rank is tiny and bounded ([`PIE_FORWARD_MAX_DIMS`]); slots at
/// `rank` and beyond hold [`PieForwardDim::default`].
struct PieForwardValue {
  uint32_t rank;
  PieForwardDim dims[PIE_FORWARD_MAX_DIMS];
  PieForwardDType dtype;
};

template<typename T>
struct PieForwardSlice {
  const T *ptr;
  size_t len;
};

using PieForwardValueSlice = PieForwardSlice<PieForwardValue>;

/// A run of value ids inside [`PieForwardPlan::value_ids`].
///
/// An {offset, len} pair rather than a pointer slice so an op stays a plain
/// record over one flat array — the driver walks
/// `plan.value_ids.ptr[range.offset .. range.offset + range.len]`.
struct PieForwardIdRange {
  uint32_t offset;
  uint32_t len;
};

/// One operation of the traced form, flattened.
///
/// The two `param` fields carry what the corresponding
/// [`crate::trace::OpKind`] variant carries; everything a kind does not use
/// rests at zero:
///
/// | `kind`           | `weight_name`        | `param0`                     | `param1`   |
/// |------------------|----------------------|------------------------------|------------|
/// | `Embed`          | embedding table      | —                            | —          |
/// | `Matmul`         | weight               | `beta_one` (0/1)             | —          |
/// | `Rmsnorm`        | weight               | [`PieForwardNormVariant`]    | —          |
/// | `RmsnormPerHead` | weight               | `head_dim`                   | —          |
/// | `SplitQkv`       | none                 | `q_width`                    | `kv_width` |
/// | `Rope`           | none                 | [`PieForwardRopeKind`]       | —          |
/// | `KvAppend`       | none                 | cache layer                  | —          |
/// | `Attention`      | none                 | cache layer                  | —          |
/// | `Swiglu`         | none                 | `inter`                      | —          |
/// | `LmHead`         | weight               | —                            | —          |
/// | `ResidualAdd`    | none                 | —                            | —          |
/// | `TopK`           | none                 | `k`                          | —          |
/// | `WeightedSum`    | none                 | `k`                          | —          |
/// | `SigmoidGateAdd` | none                 | —                            | —          |
/// | `SplitGdn`       | none                 | `width0`                     | `width1`   |
/// | `CausalConv1d`   | conv (weight + bias) | state layer                  | `kernel`   |
/// | `GdnPrep`        | a_log                | dt_bias NAME index           | —          |
/// | `GatedDelta`     | none                 | state layer                  | —          |
/// | `RmsnormGated`   | weight               | —                            | —          |
///
/// `KvAppend`/`Attention` restate the layer their kind addresses even though
/// `layer` carries the bracketing layer, because the trace states both
/// separately and the flattening does not get to decide they coincide; the
/// GDN state ops (`CausalConv1d`, `GatedDelta`) restate theirs for the same
/// reason — param0 is the layer of the implicit PER-REQUEST conv/recurrent
/// slab the op reads and advances (the trace crate's `OpKind::state_ref`
/// marking, pie-application-plan.md §5.4). `GdnPrep` is the one kind whose
/// launch reads two parameter tensors, so its param0 is a SECOND
/// [`PieForwardPlan::names`] index (the dt_bias name), not a width.
struct PieForwardOp {
  PieForwardOpKind kind;
  /// The layer this op belongs to, or [`PIE_FORWARD_NO_LAYER`] for
  /// prologue/epilogue — so the driver can bracket its layer loop without
  /// re-deriving structure from names.
  int32_t layer;
  /// Index into [`PieForwardPlan::names`], or [`PIE_FORWARD_NO_NAME`].
  uint32_t weight_name;
  uint32_t param0;
  uint32_t param1;
  /// The per-token selector: for an expert-indexed `Matmul` (whose
  /// `weight_name` is then a template, `layer.0.expert.{e}.gate_up`) the
  /// value id of the `TopK` index output that resolves `{e}` per token;
  /// [`PIE_FORWARD_NO_VALUE`] for every other op. The selector is also
  /// the op's last input, so a dataflow walk needs no special case; this
  /// field states which input selects rather than flows. The dyn marker
  /// crosses the ABI only here and as the producing `TopK` op — a
  /// per-value flag would duplicate what these two already state.
  uint32_t selector;
  /// Values consumed, in operand order.
  PieForwardIdRange inputs;
  /// Values produced (`SplitQkv` produces three, `KvAppend` none).
  PieForwardIdRange outputs;
};

using PieForwardOpSlice = PieForwardSlice<PieForwardOp>;

using PieForwardU32Slice = PieForwardSlice<uint32_t>;

/// One entry of the name table: a substring of
/// [`PieForwardPlan::name_bytes`]. Names are interned, so ops that share a
/// weight (tied embeddings name `embed` twice) share an entry.
struct PieForwardName {
  uint32_t offset;
  uint32_t len;
};

using PieForwardNameSlice = PieForwardSlice<PieForwardName>;

/// A borrowed byte run. Not NUL-terminated, for the reason
/// `loader/src/ffi/types.rs` gives on `PieLoaderBytes`: the bytes come from
/// Rust `String`s and C++ consumers build a `string_view` from the pair.
struct PieForwardBytes {
  const uint8_t *ptr;
  size_t len;
};

/// The traced form of one family's forward pass, as the driver sees it.
///
/// Read-only by construction: the driver walks `ops` in order, resolves
/// weight names against its own tensor store, and never writes back.
///
/// `owner` is the opaque handle to the arena keeping every slice alive. It
/// is consumed by `pie_forward_release`; the driver must not dereference it.
struct PieForwardPlan {
  /// The family that traced this, as a name-table index — a cache key, and
  /// the first thing a mismatch report prints.
  uint32_t family;
  PieForwardValueSlice values;
  PieForwardOpSlice ops;
  /// The flat operand array every [`PieForwardIdRange`] indexes; ids index
  /// `values`.
  PieForwardU32Slice value_ids;
  /// The name table; entries substring `name_bytes`.
  PieForwardNameSlice names;
  /// The UTF-8 blob behind the name table.
  PieForwardBytes name_bytes;
  /// The tracer's content hash ([`crate::ffi::compiler_version`]), so two
  /// plans compare as stale-vs-fresh without re-tracing.
  uint64_t compiler_version;
  void *owner;
};

/// The qwen3_5_moe MLP-block facts, as C states them. Mirrors
/// [`crate::facts::Qwen35MoeMlpFacts`] field for field; same input-side
/// rules as [`PieForwardLlamaLikeFacts`].
struct PieForwardQwen35MoeMlpFacts {
  uint32_t hidden;
  uint32_t num_experts;
  uint32_t top_k;
  uint32_t moe_intermediate;
  /// 0 means no shared expert (the qwen3_moe shape).
  uint32_t shared_expert_intermediate;
  /// A [`super::types::PieForwardNormVariant`] value.
  uint32_t norm_variant;
};

/// The qwen3_5 GDN-block facts, as C states them. Mirrors
/// [`crate::facts::Qwen35GdnFacts`] field for field; same input-side rules
/// as [`PieForwardLlamaLikeFacts`].
struct PieForwardQwen35GdnFacts {
  uint32_t hidden;
  uint32_t key_heads;
  uint32_t value_heads;
  uint32_t key_head_dim;
  uint32_t value_head_dim;
  uint32_t conv_kernel;
  /// The deployment bound the fused `in_proj_qkvz`/`in_proj_ba` banks
  /// (`PIE_QWEN35_FUSED_GDN_PROJ`); non-zero is true.
  uint8_t fused_in_proj;
  /// A [`super::types::PieForwardNormVariant`] value.
  uint32_t norm_variant;
};

extern "C" {

/// Trace the llama_like family against `facts` and publish the traced form
/// into `*out_plan`.
///
/// The header is written into caller-owned storage; the slices inside it are
/// owned by Rust and must be reclaimed with [`pie_forward_release`]. On any
/// failure `*out_plan` (if writable) is left empty, never dangling.
///
/// # Safety
///
/// `facts` is null or points at a readable [`PieForwardLlamaLikeFacts`];
/// `out_plan` is null or a writable slot.
PieForwardStatus pie_forward_trace_llama_like(const PieForwardLlamaLikeFacts *facts,
                                              PieForwardPlan *out_plan);

/// Trace the qwen3_5_moe MoE MLP-block FRAGMENT against `facts` and publish
/// the traced form into `*out_plan`.
///
/// The result is the first traced form carrying `dyn` ops (`TopK`,
/// expert-selecting `Matmul`s, `WeightedSum`, `SigmoidGateAdd`). The
/// declared executors do NOT consume these — their op-kind switches throw
/// on any kind past their vocabulary — so this entry point exists for the
/// toolchain side (planning, tests, cross-language pinning), not for
/// emission; the grouped-GEMM emission is a later, much larger lift.
///
/// # Safety
///
/// `facts` is null or points at a readable [`PieForwardQwen35MoeMlpFacts`];
/// `out_plan` is null or a writable slot.
PieForwardStatus pie_forward_trace_qwen3_5_moe_mlp(const PieForwardQwen35MoeMlpFacts *facts,
                                                   PieForwardPlan *out_plan);

/// Trace the qwen3_5 GDN (gated-deltanet) linear-attention block FRAGMENT
/// against `facts` and publish the traced form into `*out_plan`.
///
/// The result carries the GDN vocabulary (`SplitGdn`, `CausalConv1d`,
/// `GdnPrep`, `GatedDelta`, `RmsnormGated`) — and the first ops that
/// address PER-REQUEST state (the conv/recurrent slabs, implicit behind
/// `CausalConv1d`/`GatedDelta`'s layer, exactly as the KV cache is behind
/// `KvAppend`'s). The declared executors do NOT consume these — their
/// op-kind switches throw on any kind past their vocabulary — so this
/// entry point exists for the toolchain side (planning, tests,
/// cross-language pinning), not for emission.
///
/// # Safety
///
/// `facts` is null or points at a readable [`PieForwardQwen35GdnFacts`];
/// `out_plan` is null or a writable slot.
PieForwardStatus pie_forward_trace_qwen3_5_gdn(const PieForwardQwen35GdnFacts *facts,
                                               PieForwardPlan *out_plan);

/// Free the storage behind a plan header filled by
/// [`pie_forward_trace_llama_like`], [`pie_forward_trace_qwen3_5_moe_mlp`]
/// or [`pie_forward_trace_qwen3_5_gdn`], and reset the header to empty.
///
/// Safe to call with null, with a header that was never filled, or twice
/// with the same header (the first call empties it).
///
/// # Safety
///
/// `plan` is null, or points at a writable header that is empty or was
/// filled by [`pie_forward_trace_llama_like`].
void pie_forward_release(PieForwardPlan *plan);

}  // extern "C"

}  // namespace pie_forward
