use crate::device::DeviceKernel;
use kernels::KernelSig;

/// The prefix every generated entry point carries.
pub const PREFIX: &str = "pie_k_";

/// The `extern "C"` name for a row: the prefix, then the symbol with its
pub fn entry_name(symbol: &str) -> String {
    format!("{PREFIX}{}", symbol.replace("::", "_"))
}

/// The rows this module can emit — those that have stated their operands.
fn stated(table: &[&'static [KernelSig]]) -> Vec<&'static KernelSig> {
    table
        .iter()
        .flat_map(|t| t.iter())
        .filter(|k| !k.operands.is_empty())
        .collect()
}

/// The C++ namespace a symbol names, under this crate's root.
fn cpp_path(symbol: &str) -> String {
    format!("::pie_cuda_driver::kernels::{symbol}")
}

/// Emit the `extern "C"` forwarding shims for every stated row in `tables`.
pub fn emit_c_shim(
    tables: &[&'static [KernelSig]],
    includes: &[&str],
    jit: &[&'static crate::device::DeviceKernel],
) -> Result<String, String> {
    let rows: Vec<&'static KernelSig> = stated(tables)
        .into_iter()
        .filter(|k| !jit.iter().any(|d| d.sig.symbol == k.symbol))
        .filter(|k| !crate::execution::RUST_SERVED.contains(&k.symbol))
        .collect();
    let mut seen: Vec<(String, &str)> = Vec::new();
    let mut out = String::new();

    out.push_str(
        "// GENERATED by kernels_cuda_new::abi::emit_c_shim -- do not edit.\n\
         //\n\
         // Each body forwards to the launcher its row describes, through a\n\
         // function pointer of the row's exact type. A function-pointer\n\
         // initialisation admits NO parameter conversions, which is why it is\n\
         // written this way rather than as a direct call: a direct call is\n\
         // checked by overload resolution, and overload resolution accepts\n\
         // `void*` where the callee takes `const void*`. That is the one\n\
         // direction a shim can be wrong in and still compile -- a row\n\
         // claiming a read-only operand is written -- and it is exactly the\n\
         // fact the table exists to carry.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\
         #include <cstdio>\n\
         #include <cstdlib>\n\
         #include <exception>\n\
         #include <cuda_runtime.h>\n\n\
         // Every body is wrapped, and the reason is worth stating because the\n\
         // wrapper looks like belt-and-braces and is not. A launcher reports a\n\
         // capability it lacks by THROWING -- FlashInfer's dispatch macros end\n\
         // in `throw std::invalid_argument(...)` for an unsupported head dim or\n\
         // GQA group size. An exception crossing the C ABI boundary is\n\
         // undefined behaviour, and what it does in practice is unwind through\n\
         // Rust frames until the runtime aborts -- SIGABRT, no message, and a\n\
         // backtrace pointing at whatever destructor ran last. Twice that cost\n\
         // a debugger session to learn one sentence the launcher had already\n\
         // written down.\n\
         //\n\
         // So the process still dies, because these signatures have nowhere to\n\
         // put a failure -- but it dies SAYING WHY.\n\
         #define PIE_K_GUARD(expr)                                             \\\n\
             try { expr; } catch (const ::std::exception& e) {                 \\\n\
                 ::std::fprintf(stderr, \"[pie_k] %s: %s\\n\", __func__, e.what()); \\\n\
                 ::std::fflush(stderr);                                        \\\n\
                 ::std::abort();                                               \\\n\
             } catch (...) {                                                   \\\n\
                 ::std::fprintf(stderr, \"[pie_k] %s: unknown C++ exception\\n\", \\\n\
                                __func__);                                     \\\n\
                 ::std::fflush(stderr);                                        \\\n\
                 ::std::abort();                                               \\\n\
             }\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for k in rows {
        let entry = entry_name(k.symbol);
        if let Some((_, other)) = seen.iter().find(|(e, _)| *e == entry) {
            return Err(format!(
                "entry point `{entry}` is claimed by both `{}` and `{other}`",
                k.symbol
            ));
        }
        seen.push((entry.clone(), k.symbol));

        let params = k
            .operands
            .iter()
            .map(|o| format!("    {} {}", o.ty.cpp(), o.name))
            .collect::<Vec<_>>()
            .join(",\n");
        let types = k
            .operands
            .iter()
            .map(|o| o.ty.cpp())
            .collect::<Vec<_>>()
            .join(", ");
        let args = k
            .operands
            .iter()
            .map(|o| o.name)
            .collect::<Vec<_>>()
            .join(", ");

        out.push_str(&format!(
            "extern \"C\" void {entry}(\n{params}) {{\n    \
             static void (*const fwd)({types}) = &{};\n    \
             PIE_K_GUARD(fwd({args}))\n}}\n\n",
            cpp_path(k.symbol),
        ));
    }
    Ok(out)
}

/// Emit the Rust `extern "C"` block matching [`emit_c_shim`].
pub fn emit_rust_bindings(tables: &[&'static [KernelSig]]) -> String {
    bindings(tables, "emit_rust_bindings", false)
}

/// [`emit_rust_bindings`] restricted to rows ANY crate can declare.
pub fn emit_rust_bindings_portable(tables: &[&'static [KernelSig]]) -> String {
    bindings(tables, "emit_rust_bindings_portable", true)
}

fn bindings(tables: &[&'static [KernelSig]], by: &str, portable_only: bool) -> String {
    let mut out = format!(
        "// GENERATED by kernels_cuda_new::abi::{by} -- do not edit.\n\
         //\n\
         // The other half of the same rows the C++ shim is generated from.\n\
         // A `nullable` operand is documented, not typed: making it an\n\
         // `Option<NonNull<_>>` here would change the calling convention of\n\
         // an `extern \"C\"` declaration for a fact the callee checks itself.\n\n\
         unsafe extern \"C\" {{\n"
    );
    for k in stated(tables) {
        if portable_only && k.operands.iter().any(|o| o.ty.needs_mirror()) {
            continue;
        }
        if crate::execution::RUST_SERVED.contains(&k.symbol) {
            continue;
        }
        out.push_str(&format!("    /// `{}`\n", k.symbol));
        out.push_str(&format!("    pub unsafe fn {}(\n", entry_name(k.symbol)));
        for o in k.operands {
            let note = if o.nullable { "  // may be null" } else { "" };
            out.push_str(&format!("        {}: {},{note}\n", o.name, o.ty.rust()));
        }
        out.push_str("    );\n");
    }
    out.push_str("}\n");
    out
}

/// Where the emitted assertions are going to sit.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Site {
    /// A translation unit of its own: it includes the templates it checks.
    Standalone,
    /// Appended to the source that already holds the templates.
    Appendix,
}

/// Whether a row's operands may be spelled from its `Ty` tags and its
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Elem {
    /// Every tag spells its `Ty::cpp`, with `Buf`/`BufMut` resolved to a
    Resolve,
    /// Only a tag that determines a C++ type on its own may be spelled; a row
    Opaque,
}

/// One emitted typecheck, and how much of the row set it actually covers.
#[derive(Debug)]
pub struct DeviceTypecheck {
    /// The C++.
    pub text: String,
    /// Rows every operand of which is asserted. Arity is asserted on all of
    pub checked: usize,
    /// Operand positions carrying a type assertion.
    pub asserted: usize,
    /// Operand positions in total, so `asserted` has a denominator.
    pub positions: usize,
    /// The rows not fully checked, and why: `(symbol, reason)`. Their arity
    pub skipped: Vec<(&'static str, String)>,
    /// Rows whose instantiation another row already asserted: a second NAME
    /// for one entry point, asserted once.
    pub aliased: usize,
}

/// Emit the translation unit that PROVES the rows.
pub fn device_typecheck(
    rows: &[&DeviceKernel],
    site: Site,
    elem: Elem,
) -> Result<DeviceTypecheck, String> {
    let mut out = String::new();
    out.push_str(
        "// GENERATED by kernels_cuda_new::abi::device_typecheck -- do not edit.\n\
         //\n\
         // One assertion per row, comparing the type of the `__global__` the\n\
         // row names against a function pointer built from the row's own\n\
         // operand list. Type identity admits NO parameter conversions, so a\n\
         // row that has drifted from the kernel -- in arity, order, constness,\n\
         // width or numeric format -- does not compile. That is the property\n\
         // `emit_c_shim` bought with a forwarding call, kept after the call is\n\
         // gone.\n\
         //\n\
         // THIS TEXT IS COMPILED BY NVRTC, as the tail of the unit whose\n\
         // templates it checks -- `unit::Unit::source`, once per unit, on the\n\
         // compile that produces the cubin. It used to be an nvcc translation\n\
         // unit emitted by hand over one row list, and its own header said so;\n\
         // nvcc reached zero in this tree and the sentence outlived it.\n\
         //\n\
         // Every row's ARITY is asserted. Every operand whose C++ type is in\n\
         // its row tag is asserted in its own position. An operand whose C++\n\
         // type is NOT in its tag is listed below rather than dropped: a file\n\
         // with no assertions in it compiles exactly like one that checks\n\
         // everything, so what is unchecked is written down, and counted.\n\n",
    );

    let mut files: Vec<&str> = Vec::new();
    for &k in rows {
        let file = k
            .sig
            .file
            .ok_or_else(|| format!("`{}` states no file to find its template in", k.sig.symbol))?;
        if !files.contains(&file) {
            files.push(file);
        }
    }
    out.push_str(
        "// The fixed-width spellings `Ty::cpp` shares with the C shim, and the\n\
         // trait the assertions are written with. Under NVRTC all three are\n\
         // `csrc/shim` entries in the carried header set; under any other\n\
         // compiler they are the standard library's.\n\
         #include <cstddef>\n#include <cstdint>\n#include <type_traits>\n\n",
    );
    match site {
        Site::Standalone => {
            out.push_str("// The templates. Nothing else is included, because nothing else is.\n");
            for f in &files {
                out.push_str(&format!("#include \"{f}\"\n"));
            }
            out.push('\n');
        }
        Site::Appendix => {
            out.push_str(&format!(
                "// The templates are above: this is the tail of `{}`.\n\n",
                files.first().copied().unwrap_or("the unit's root")
            ));
        }
    }
    if rows.iter().any(|k| k.sig.operands.iter().any(|o| o.ty == kernels::Ty::Fp8Kind)) {
        out.push_str(
            "// `Ty::Fp8Kind` crosses as four bytes. See `kernels::Ty::Fp8Kind`.\n\
             static_assert(sizeof(::__nv_fp8_interpretation_t) == 4,\n    \
             \"__nv_fp8_interpretation_t is not four bytes: `emit::crossing` \
             marshals `Ty::Fp8Kind` as `Crossing::U32`, and a narrower enum \
             shifts every argument after it\");\n\n",
        );
    }
    out.push_str(
        "namespace {\n\n\
         // Parameter N of a function pointer's type, and its arity. See\n\
         // `abi::device_typecheck`.\n\
         //\n\
         // The primary template ANSWERS rather than failing to match, and\n\
         // that is the whole care here: a row whose arity is wrong indexes\n\
         // past the end, and an incomplete type would report that as a\n\
         // diagnostic about a generated line no one wrote. `pie_absent` makes\n\
         // it report as the row's own `static_assert` instead.\n\
         struct pie_absent {};\n\
         template <::std::size_t N, class... A>\n\
         struct pie_pick {\n    \
         using type = pie_absent;\n\
         };\n\
         template <class H, class... T>\n\
         struct pie_pick<0, H, T...> {\n    \
         using type = H;\n\
         };\n\
         template <::std::size_t N, class H, class... T>\n\
         struct pie_pick<N, H, T...> : pie_pick<N - 1, T...> {};\n\n\
         template <class F>\n\
         struct pie_sig {\n    \
         static constexpr ::std::size_t arity = 0;\n    \
         template <::std::size_t N>\n    \
         using at = pie_absent;\n\
         };\n\
         template <class R, class... A>\n\
         struct pie_sig<R (*)(A...)> {\n    \
         static constexpr ::std::size_t arity = sizeof...(A);\n    \
         template <::std::size_t N>\n    \
         using at = typename pie_pick<N, A...>::type;\n\
         };\n\n",
    );

    let mut checked = 0usize;
    let mut asserted = 0usize;
    let mut positions = 0usize;
    let mut skipped: Vec<(&'static str, String)> = Vec::new();
    let mut aliased = 0usize;
    let mut seen: Vec<(String, &DeviceKernel)> = Vec::new();
    for &k in rows {
        let inst = k.instantiation();
        if let Some((_, other)) = seen.iter().find(|(i, _)| *i == inst) {
            // Two symbols may name one instantiation -- they are one kernel
            // launched with different arguments, and the fire path resolves a
            // SYMBOL, so both rows must exist. What cannot be true is one
            // entry point under two contracts; that is what is refused.
            if other.sig.operands != k.sig.operands {
                return Err(format!(
                    "instantiation `{inst}` is claimed by `{}` with {} operands and by \
                     `{}` with {}; one entry point cannot have two contracts",
                    k.sig.symbol,
                    k.sig.operands.len(),
                    other.sig.symbol,
                    other.sig.operands.len()
                ));
            }
            aliased += 1;
            continue;
        }
        seen.push((inst.clone(), k));

        if let Some(o) = k
            .sig
            .operands
            .iter()
            .find(|o| matches!(o.ty, kernels::Ty::Stream | kernels::Ty::CublasHandle))
        {
            let why = if o.ty == kernels::Ty::Stream {
                "a stream is a launch argument rather than a kernel's"
            } else {
                "a cuBLAS handle is the service's rather than the statement's, and \
                 `cublasHandle_t` is a host library's type that no `__global__` takes \
                 and no header under `csrc/` declares"
            };
            return Err(format!("`{}` takes `{}` as an operand, and {why}", k.sig.symbol, o.name));
        }
        let checker = format!(
            "check_{}",
            k.sig
                .symbol
                .replace("::", "_")
                .replace(|c: char| !c.is_ascii_alphanumeric() && c != '_', "_")
        );
        let types = operand_types(k, elem);
        out.push_str(&format!("// `{}`\n", k.sig.symbol));
        out.push_str(&format!("using {checker} = pie_sig<decltype(&{inst})>;\n"));
        out.push_str(&format!(
            "static_assert({checker}::arity == {},\n    \
             \"{}: the row states {} operands and the __global__ takes a \
             different number\");\n",
            k.sig.operands.len(),
            k.sig.symbol,
            k.sig.operands.len()
        ));
        let mut unspellable: Vec<String> = Vec::new();
        for (n, o) in k.sig.operands.iter().enumerate() {
            positions += 1;
            match &types[n] {
                Ok(cpp) => {
                    out.push_str(&format!(
                        "static_assert(::std::is_same_v<{checker}::at<{n}>, {cpp}>,\n    \
                         \"{}: operand {n} `{}` is not `{cpp}`\");\n",
                        k.sig.symbol, o.name
                    ));
                    asserted += 1;
                }
                Err(why) => unspellable.push(why.clone()),
            }
        }
        if unspellable.is_empty() {
            checked += 1;
        } else {
            let why = unspellable.join("; ");
            out.push_str(&format!("// `{}` is not FULLY checked: {why}\n", k.sig.symbol));
            skipped.push((k.sig.symbol, why));
        }
        out.push('\n');
    }
    out.push_str("}  // namespace\n");
    out.push_str(&format!(
        "\n// {checked} of {} rows fully checked; {asserted} of {positions} operand \
         positions asserted.\n",
        rows.len()
    ));
    Ok(DeviceTypecheck { text: out, checked, asserted, positions, skipped, aliased })
}

/// A standalone translation unit over `rows`, with `Buf`/`BufMut` resolved
pub fn emit_device_typecheck(rows: &[DeviceKernel]) -> Result<String, String> {
    let rows: Vec<&DeviceKernel> = rows.iter().collect();
    device_typecheck(&rows, Site::Standalone, Elem::Resolve).map(|tu| tu.text)
}

/// The C++ parameter list `row` states, or why it cannot be recovered.
fn operand_types(k: &DeviceKernel, elem: Elem) -> Vec<Result<String, String>> {
    let head = k.elem.split(',').next().unwrap_or(k.elem).trim();
    let storage = if k.is_plain() {
        Err(format!(
            "`{}` names a `__global__` with no template parameter list, so it \
             has no element type for a `Ty::Buf`/`Ty::BufMut` operand to be a \
             buffer of",
            k.sig.symbol
        ))
    } else if head.is_empty() {
        Err(format!(
            "`{}` states an element type of `{}`, whose first template \
             argument is empty -- a row's `elem` may carry a list, but its \
             head is the storage type every buffer operand is spelled in",
            k.sig.symbol, k.elem
        ))
    } else if head.starts_with(|c: char| c.is_ascii_digit())
        || head == "true"
        || head == "false"
        || head.contains('(')
        || head.ends_with("::value")
    {
        Err(format!(
            "`{}` states an element type of `{}`, whose head `{head}` is a \
             VALUE rather than a type -- a buffer operand is spelled as a \
             pointer to the head of `elem`, and a non-type there becomes a \
             pointer declarator the compiler rejects in the generated file \
             rather than in the row",
            k.sig.symbol, k.elem
        ))
    } else {
        Ok(format!("::pie_cuda_driver::kernels::{head}"))
    };

    let mut types: Vec<Result<String, String>> = Vec::with_capacity(k.sig.operands.len());
    for o in k.sig.operands {
        match elem {
            Elem::Resolve => match o.ty {
                kernels::Ty::Buf | kernels::Ty::BufMut => match &storage {
                    Ok(storage) => types.push(Ok(device_cpp_ty(o.ty, storage))),
                    Err(why) => types.push(Err(why.clone())),
                },
                _ => types.push(Ok(device_cpp_ty(o.ty, ""))),
            },
            Elem::Opaque => {
                if self_describing(o.ty) {
                    types.push(Ok(o.ty.cpp().to_string()));
                } else {
                    types.push(Err(format!(
                        "`{}` is a `{:?}`, whose C++ type is NOT in the tag -- \
                         `Ty::cpp` spells it `{}`, and in this population that \
                         is a projection rather than the parameter",
                        o.name,
                        o.ty,
                        o.ty.cpp()
                    )));
                }
            }
        }
    }
    types
}

/// Whether a `Ty` alone determines the C++ parameter, in a population that
pub fn self_describing(ty: kernels::Ty) -> bool {
    use kernels::Ty;
    match ty {
        Ty::I32
        | Ty::U32
        | Ty::I64
        | Ty::F32
        | Ty::Bool
        | Ty::Usize
        | Ty::I32s
        | Ty::I32sMut
        | Ty::I64s
        | Ty::I8s
        | Ty::I8sMut
        | Ty::U8s
        | Ty::U8sMut
        | Ty::U16s
        | Ty::U16sMut
        | Ty::U32s
        | Ty::U32sMut
        | Ty::F32s
        | Ty::F32sMut
        | Ty::U8Array
        | Ty::I32Array
        | Ty::Bf16s
        | Ty::F16s
        | Ty::Bf16sMut
        | Ty::F16sMut
        | Ty::KvScheme
        | Ty::KvDType
        | Ty::StructuredMasks
        | Ty::Fp8Kind => true,

        Ty::Buf
        | Ty::BufMut
        | Ty::BufArray
        | Ty::BufArrayMut
        | Ty::BufArrayOut
        | Ty::BufArrayOutMut
        | Ty::InPacked
        | Ty::Dtype
        | Ty::MoeActivation
        | Ty::Mxfp4RowSelect
        | Ty::CustomAllReduce
        | Ty::YarnOriginalParams
        | Ty::AttentionWorkspaceView
        | Ty::KvCacheLayerView
        | Ty::MlaCacheLayerView
        | Ty::DecodePlanCache
        | Ty::PrefillPlanCache
        | Ty::MlaPlanCache
        | Ty::HopperPrefillPlan
        | Ty::CublasHandle
        | Ty::Stream => false,
    }
}

/// How a device row's operand is spelled in C++, given the element type its
fn device_cpp_ty(ty: kernels::Ty, storage: &str) -> String {
    match ty {
        kernels::Ty::Buf => format!("const {storage}*"),
        kernels::Ty::BufMut => format!("{storage}*"),
        other => other.cpp().to_string(),
    }
}

/// One record whose Rust mirror claims to have the C++ type's layout.
pub struct Record {
    /// The fully-qualified C++ type.
    pub cpp: &'static str,
    /// `size_of` the Rust mirror.
    pub size: usize,
    /// `align_of` the Rust mirror.
    pub align: usize,
    /// Every field, in declaration order, with the Rust mirror's offset.
    pub fields: Vec<(&'static str, usize)>,
}

/// Build a [`Record`] from a `#[repr(C)]` mirror and the C++ type it claims.
#[macro_export]
macro_rules! record {
    ($rust:ty => $cpp:literal { $($field:ident),* $(,)? }) => {
        $crate::abi::Record {
            cpp: $cpp,
            size: ::core::mem::size_of::<$rust>(),
            align: ::core::mem::align_of::<$rust>(),
            fields: ::std::vec![
                $((stringify!($field), ::core::mem::offset_of!($rust, $field))),*
            ],
        }
    };
}

/// Emit a translation unit that asserts each mirror's layout against the C++.
pub fn emit_layout_assertions(records: &[Record], includes: &[&str]) -> String {
    let mut out = String::from(
        "// GENERATED by kernels_cuda_new::abi::emit_layout_assertions -- do not edit.\n\
         //\n\
         // The offsets are what the RUST mirrors compute for themselves. They\n\
         // are checked here because this is the only place both layouts are\n\
         // known; a mirror that disagrees does not compile.\n\n\
         #include <cstddef>\n\
         #include <cstdint>\n\n",
    );
    for inc in includes {
        out.push_str(&format!("#include \"{inc}\"\n"));
    }
    out.push('\n');

    for r in records {
        let tag = r.cpp.rsplit("::").next().unwrap_or(r.cpp);
        out.push_str(&format!(
            "static_assert(sizeof({0}) == {1},\n    \
             \"{0}: the mirror is {1} bytes\");\n\
             static_assert(alignof({0}) == {2},\n    \
             \"{0}: the mirror aligns to {2}\");\n",
            r.cpp, r.size, r.align
        ));
        for (name, off) in &r.fields {
            out.push_str(&format!(
                "static_assert(offsetof({0}, {1}) == {2},\n    \
                 \"{0}::{1} is not at {2}\");\n",
                r.cpp, name, off
            ));
        }
        let binds = r
            .fields
            .iter()
            .map(|(n, _)| format!("f_{n}"))
            .collect::<Vec<_>>();
        out.push_str(&format!(
            "\n// Exactly {} members, and no more.\nnamespace {{\ninline void \
             abi_member_count_{tag}() {{\n    {} v{{}};\n    auto& [{}] = v;\n{}}}\n}}\n\n",
            binds.len(),
            r.cpp,
            binds.join(", "),
            binds
                .iter()
                .map(|b| format!("    (void){b};\n"))
                .collect::<String>(),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use kernels::Ty;

    /// The two emitters must describe the same operands in the same order, or
    #[test]
    fn both_halves_are_emitted_from_the_same_rows() {
        let tables: &[&'static [KernelSig]] = &[crate::table::attn::KERNELS];
        let c = emit_c_shim(tables, &["attn/attn.hpp"], &[]).expect("no collisions");
        let rs = emit_rust_bindings(tables);
        for k in stated(tables)
            .into_iter()
            .filter(|k| !crate::execution::RUST_SERVED.contains(&k.symbol))
        {
            let entry = entry_name(k.symbol);
            assert!(c.contains(&entry), "{entry} missing from the shim");
            assert!(rs.contains(&entry), "{entry} missing from the bindings");
            for o in k.operands {
                assert!(c.contains(o.name), "{entry}: {} missing", o.name);
            }
        }
    }

    /// An unstated row is skipped rather than emitted as a nullary call.
    #[test]
    fn rows_that_have_not_stated_their_operands_are_not_emitted() {
        static UNSTATED: &[KernelSig] = &[kernels::kernel!(nothing "fam::not_yet_stated")];
        let c = emit_c_shim(&[UNSTATED], &[], &crate::device::jit_dispatched()).expect("no collisions");
        assert!(!c.contains("not_yet_stated"));
        assert!(!emit_rust_bindings(&[UNSTATED]).contains("not_yet_stated"));
    }

    /// `::` flattens to a single underscore -- `__` is reserved in C++.
    #[test]
    fn entry_points_avoid_the_reserved_double_underscore() {
        let name = entry_name("rope::rope_bf16");
        assert_eq!(name, "pie_k_rope_rope_bf16");
        assert!(!name.contains("__"));
    }

    /// Which makes a collision possible in principle, so it is refused.
    #[test]
    fn two_rows_may_not_claim_one_entry_point() {
        static CLASH: &[KernelSig] = &[
            kernels::kernel!(a "rope::a_b", operands = kernels::operands![stream: Stream]),
            kernels::kernel!(b "rope_a::b", operands = kernels::operands![stream: Stream]),
        ];
        let err = emit_c_shim(&[CLASH], &[], &crate::device::jit_dispatched()).expect_err("a collision is an error");
        assert!(err.contains("pie_k_rope_a_b"), "{err}");
    }

    /// `bool` is one byte in C++ and `int` is four. A binding that renders a
    #[test]
    fn a_flag_stays_one_byte_wide_on_both_sides() {
        assert_eq!(Ty::Bool.cpp(), "bool");
        assert_eq!(Ty::Bool.rust(), "bool");
        assert_ne!(Ty::Bool.rust(), Ty::I32.rust());
    }
}

use kernels::{Lit, Source};

/// An element count, spelled the width the row declares — or `None`,
fn elem_count(e: &str, ty: kernels::Ty) -> Option<String> {
    Some(match ty {
        kernels::Ty::Usize => e.to_string(),
        kernels::Ty::I32 => format!("i32::try_from({e}).unwrap_or(0)"),
        kernels::Ty::U32 => format!("u32::try_from({e}).unwrap_or(0)"),
        kernels::Ty::I64 => format!("i64::try_from({e}).unwrap_or(0)"),
        _ => return None,
    })
}

/// The Rust expression that binds one operand.
fn for_each_leaf(s: &Source, f: &mut impl FnMut(&Source)) {
    match *s {
        Source::Width(ref a) | Source::Isqrt(ref a) => for_each_leaf(a, f),
        Source::Mul(ref a, ref b)
        | Source::Sub(ref a, ref b)
        | Source::Div(ref a, ref b)
        | Source::Ne(ref a, ref b) => {
            for_each_leaf(a, f);
            for_each_leaf(b, f);
        }
        Source::IfPresent(ref p, ref a, ref b) => {
            for_each_leaf(p, f);
            for_each_leaf(a, f);
            for_each_leaf(b, f);
        }
        Source::Or(..) => f(s),
        _ => f(s),
    }
}

/// Whether a kernel MENTIONS a leaf anywhere, `Or` branches included.
fn mentions(k: &kernels::KernelSig, mut pred: impl FnMut(&Source) -> bool) -> bool {
    fn walk(s: &Source, f: &mut impl FnMut(&Source) -> bool) -> bool {
        if f(s) {
            return true;
        }
        match *s {
            Source::Width(ref a) | Source::Isqrt(ref a) => walk(a, f),
            Source::Mul(ref a, ref b)
            | Source::Div(ref a, ref b)
            | Source::Ne(ref a, ref b)
            | Source::Sub(ref a, ref b)
            | Source::Or(ref a, ref b) => walk(a, f) || walk(b, f),
            Source::IfPresent(ref p, ref a, ref b) => walk(p, f) || walk(a, f) || walk(b, f),
            _ => false,
        }
    }
    k.operands.iter().any(|o| walk(&o.source, &mut pred))
}

/// Whether any of a kernel's sources reaches a leaf the predicate likes.
fn any_leaf(k: &kernels::KernelSig, mut pred: impl FnMut(&Source) -> bool) -> bool {
    let mut hit = false;
    for o in k.operands {
        for_each_leaf(&o.source, &mut |s| hit |= pred(s));
    }
    hit
}

/// The presence test for the first SLOT a source reaches.
fn slot_presence(s: &Source) -> Option<String> {
    match *s {
        Source::In(i) => Some(format!("n_in > {i}")),
        Source::Out(i) => Some(format!("n_out > {i}")),
        Source::Weight(i) => Some(format!("b.args.len() > n_in + n_out + {i}")),
        Source::Param(i) | Source::ParamF32(i) => Some(format!("spec.params.len() > {i}")),
        Source::Width(ref a) | Source::Isqrt(ref a) => slot_presence(a),
        Source::Mul(ref a, ref b)
        | Source::Sub(ref a, ref b)
        | Source::Div(ref a, ref b)
        | Source::Ne(ref a, ref b) => slot_presence(a).or_else(|| slot_presence(b)),
        _ => None,
    }
}

/// The [`ArgValue`] variant a `Ty` crosses as, for the JIT dispatch arm.
fn arg_value_variant(ty: kernels::Ty) -> Option<&'static str> {
    Some(match ty {
        kernels::Ty::I32 => "crate::bind::device::ArgValue::I32",
        kernels::Ty::U32 => "crate::bind::device::ArgValue::U32",
        kernels::Ty::F32 => "crate::bind::device::ArgValue::F32",
        kernels::Ty::Usize => "crate::bind::device::ArgValue::Usize",
        kernels::Ty::I64 => "crate::bind::device::ArgValue::I64",
        kernels::Ty::Bool => "crate::bind::device::ArgValue::Bool",
        kernels::Ty::KvScheme | kernels::Ty::KvDType => "crate::bind::device::ArgValue::U8",
        kernels::Ty::Fp8Kind => "crate::bind::device::ArgValue::U32",
        kernels::Ty::Buf
        | kernels::Ty::BufMut
        | kernels::Ty::I32s
        | kernels::Ty::I32sMut
        | kernels::Ty::I64s
        | kernels::Ty::U32s
        | kernels::Ty::U32sMut
        | kernels::Ty::U8s
        | kernels::Ty::U8sMut
        | kernels::Ty::U16s
        | kernels::Ty::U16sMut
        | kernels::Ty::I8s
        | kernels::Ty::I8sMut
        | kernels::Ty::Bf16s
        | kernels::Ty::F16s
        | kernels::Ty::Bf16sMut
        | kernels::Ty::F16sMut
        | kernels::Ty::F32s
        | kernels::Ty::F32sMut
        | kernels::Ty::BufArray
        | kernels::Ty::BufArrayMut
        | kernels::Ty::BufArrayOut
        | kernels::Ty::BufArrayOutMut
        | kernels::Ty::U8Array
        | kernels::Ty::I32Array => "crate::bind::device::ArgValue::Ptr",
        _ => return None,
    })
}

fn rust_bind_expr(op: &kernels::Operand) -> Option<String> {
    let e = rust_bind_expr_of(&op.source, op.ty)?;
    if matches!(op.source, Source::Lit(Lit::Null) | Source::OutElements(_) | Source::InElements(_))
    {
        return Some(e);
    }
    cast_for(&e, op.ty)
}

/// Whether a source reads a DRIVER-DECLARED field, so its Rust type is
const fn reads_a_declared_field(source: &Source) -> bool {
    matches!(
        *source,
        Source::Ctx(_)
            | Source::CtxNonZero(_)
            | Source::CtxByLayer(_)
            | Source::Gdn(_)
            | Source::Attn(_)
            | Source::AttnNonZero(_)
            | Source::KvLayerField(_)
            | Source::RequestCount
    )
}

/// One ARITHMETIC operand, in this grammar's integer type.
fn rust_arith_of(source: &Source, ty: kernels::Ty) -> Option<String> {
    let e = rust_bind_expr_of(source, ty)?;
    let integral = matches!(
        ty,
        kernels::Ty::I32
            | kernels::Ty::U32
            | kernels::Ty::I64
            | kernels::Ty::Usize
            | kernels::Ty::Bool
    );
    if integral && reads_a_declared_field(source) {
        return cast_for(&e, kernels::Ty::I32);
    }
    Some(e)
}

/// One SOURCE's expression, without the operand's cast.
fn rust_bind_expr_of(source: &Source, ty: kernels::Ty) -> Option<String> {
    let e = match *source {
        Source::Unbound => return None,
        Source::In(i) => format!("b.args[{i}].ptr"),
        Source::Out(i) => format!("b.args[n_in + {i}].ptr"),
        Source::Weight(i) => format!("b.args[n_in + n_out + {i}].ptr"),
        Source::WeightNamed => "w_named".to_string(),
        Source::WeightNamed2 => "w_named2".to_string(),
        Source::Param(i) => format!("i32::try_from(spec.params[{i}]).unwrap_or(0)"),
        Source::ParamF32(i) => format!("f32::from_bits(spec.params[{i}])"),
        Source::RoutesOfParam(i) => format!(
            "rows.saturating_mul(i32::try_from(spec.params[{i}]).unwrap_or(0))"
        ),
        Source::Rows => "rows".to_string(),
        Source::OutRows(i) => format!("rows_of(b, n_in + {i}, rows)"),
        Source::InRows(i) => format!("rows_of(b, {i}, rows)"),
        Source::OutWidth(i) => format!("width_of(b, n_in + {i})"),
        Source::InWidth(i) => format!("width_of(b, {i})"),
        Source::CtxByLayer(f) => format!("ctx.{f}(b.layers.start as usize)"),
        Source::OutElements(i) => {
            elem_count(&format!("elems_of(b, n_in + {i}, rows)"), ty)?
        }
        Source::InElements(i) => {
            elem_count(&format!("elems_of(b, {i}, rows)"), ty)?
        }
        Source::InDim(..) | Source::OutDim(..) => return None,
        Source::Positions => "ctx.positions".to_string(),
        Source::ResultOrRegion(i) => format!(
            "join_out(spec, {i}, frame, resolver).map_or(core::ptr::null_mut(), |a| a.ptr)"
        ),
        Source::Aux(i) => format!(
            "join_aux(spec, {i}, frame, resolver).map_or(core::ptr::null_mut(), |a| a.ptr)"
        ),
        Source::KvKeys => format!(
            "kv_view(attn, b.layers.start as usize).k_bf16_pages"
        ),
        Source::KvValues => format!(
            "kv_view(attn, b.layers.start as usize).v_bf16_pages"
        ),
        Source::TokenIds
        | Source::RequestOfToken
        | Source::KvPageIndices
        | Source::KvPageIndptr
        | Source::AttentionMask
        | Source::AttentionMaskEnabled
        | Source::KvHeadStride
        | Source::KvSeqStride
        | Source::KvPageSize
        | Source::KvWritePage
        | Source::KvWriteOffset
        | Source::RopeFrequencies => return None,
        Source::SamplingIndices => "ctx.sampling_indices".to_string(),
        Source::RequestCount => "ctx.sampled_rows".to_string(),
        Source::Ctx(f) | Source::CtxNonZero(f) => format!("ctx.{f}"),
        Source::Gdn(f) => format!("g_of(gdn).{f}"),
        Source::GdnSlab(f) => format!(
            "gdn_slab(gdn, spec.state, \"{f}\").unwrap_or(core::ptr::null_mut())"
        ),
        Source::WeightSuffix(suffix) => format!(
            "spec.weight.as_deref()\n            .and_then(|n| resolver.weight(&format!(\"{{n}}{suffix}\")))\n            .unwrap_or(core::ptr::null())"
        ),
        Source::Attn(f) | Source::AttnNonZero(f) => format!("a_of(attn).{f}"),
        Source::AttnWindow => {
            "window_of(spec, a_of(attn), u32::from(b.layers.start))".to_string()
        }
        Source::AttnPlan(family) => {
            format!("attn_plan(a_of(attn), spec, u32::from(b.layers.start), \"{family}\")")
        }
        Source::KvLayerView => "kv_view(attn, b.layers.start as usize)".to_string(),
        Source::KvLayerField(f) => {
            format!("kv_view(attn, b.layers.start as usize).{f}")
        }
        Source::Lit(Lit::Null) => {
            let rust = ty.rust();
            return Some(match rust.strip_prefix("*mut ") {
                Some(p) => format!("core::ptr::null_mut::<{p}>()"),
                None => format!("core::ptr::null::<{}>()", rust.strip_prefix("*const ")?),
            });
        }
        Source::Width(s) => match *s {
            Source::In(i) => format!("width_of(b, {i})"),
            Source::Out(i) => format!("width_of(b, n_in + {i})"),
            _ => return None,
        },
        Source::Mul(a, c) => {
            format!("({}) * ({})", rust_arith_of(a, ty)?, rust_arith_of(c, ty)?)
        }
        Source::Sub(a, c) => format!(
            "({}).saturating_sub({})",
            rust_arith_of(a, ty)?,
            rust_arith_of(c, ty)?
        ),
        Source::Div(a, c) => {
            format!("({}) / ({}).max(1)", rust_arith_of(a, ty)?, rust_arith_of(c, ty)?)
        }
        Source::Isqrt(s) => format!("isqrt_exact_i32({})", rust_arith_of(s, ty)?),
        Source::Ne(a, c) => {
            format!("({}) != ({})", rust_arith_of(a, ty)?, rust_arith_of(c, ty)?)
        }
        Source::Or(a, c) => {
            let present = slot_presence(a)?;
            let left = rust_bind_expr_of(a, ty)?;
            let fallback = rust_bind_expr_of(c, ty)?;
            let fallback = if matches!(*c, Source::Lit(Lit::Null)) {
                "core::ptr::null_mut()".to_string()
            } else if ty.rust().starts_with('*') {
                format!("{fallback} as *mut _")
            } else {
                fallback
            };
            format!("if {present} {{ {left} }} else {{ {fallback} }}")
        }
        Source::IfPresent(probe, then, other) => match *probe {
            Source::PerHeadDim => format!(
                "if spec.per_head_dim.is_some() {{ {} }} else {{ {} }}",
                rust_bind_expr_of(then, ty)?,
                rust_bind_expr_of(other, ty)?
            ),
            _ => return None,
        },
        Source::PerHeadDim => "spec.per_head_dim.map_or(0, |d| d as i32)".to_string(),
        Source::NamedScale => "named_scale(ctx, spec).unwrap_or(0.0)".to_string(),
        Source::LayerScale => "layer_scale(ctx, spec)".to_string(),
        Source::Beta => "if spec.beta_one { 1.0f32 } else { 0.0f32 }".to_string(),
        Source::RotaryWidth => {
            "rotary_width(ctx, spec, b.layers.start as usize).unwrap_or(0)".to_string()
        }
        Source::Lit(Lit::Bool(v)) => v.to_string(),
        Source::Lit(Lit::F32(v)) => format!("{v}f32"),
        Source::Lit(Lit::I32(v)) => format!("{v}i32"),
    };
    Some(e)
}

/// The cast an operand's TYPE puts on its source expression.
fn cast_for(e: &str, ty: kernels::Ty) -> Option<String> {
    let e = e.to_string();
    Some(match ty {
        kernels::Ty::Buf => format!("({e}).cast_const()"),
        kernels::Ty::BufMut => e,
        kernels::Ty::I32s => format!("({e}).cast_const().cast::<i32>()"),
        kernels::Ty::U32s => format!("({e}).cast_const().cast::<u32>()"),
        kernels::Ty::U8s => format!("({e}).cast_const().cast::<u8>()"),
        kernels::Ty::I64s => format!("({e}).cast_const().cast::<i64>()"),
        kernels::Ty::F32s => format!("({e}).cast_const().cast::<f32>()"),
        kernels::Ty::I32sMut => format!("({e}).cast::<i32>()"),
        kernels::Ty::U32sMut => format!("({e}).cast::<u32>()"),
        kernels::Ty::U8sMut => format!("({e}).cast::<u8>()"),
        kernels::Ty::F32sMut => format!("({e}).cast::<f32>()"),
        kernels::Ty::U16s => format!("({e}).cast_const().cast::<u16>()"),
        kernels::Ty::U16sMut => format!("({e}).cast::<u16>()"),
        kernels::Ty::I8s => format!("({e}).cast_const().cast::<i8>()"),
        kernels::Ty::I8sMut => format!("({e}).cast::<i8>()"),
        kernels::Ty::Bf16s | kernels::Ty::F16s => {
            format!("({e}).cast_const().cast::<u16>()")
        }
        kernels::Ty::Bf16sMut | kernels::Ty::F16sMut => format!("({e}).cast::<u16>()"),
        kernels::Ty::BufArray => format!("({e}).cast_const().cast::<*const ::core::ffi::c_void>()"),
        kernels::Ty::BufArrayMut => format!("({e}).cast_const().cast::<*mut ::core::ffi::c_void>()"),
        kernels::Ty::BufArrayOut => format!("({e}).cast::<*const ::core::ffi::c_void>()"),
        kernels::Ty::BufArrayOutMut => format!("({e}).cast::<*mut ::core::ffi::c_void>()"),
        kernels::Ty::U8Array => format!("({e}).cast_const().cast::<*const u8>()"),
        kernels::Ty::I32Array => format!("({e}).cast_const().cast::<*const i32>()"),
        kernels::Ty::I32 => format!("i32::try_from({e}).unwrap_or(i32::MAX)"),
        kernels::Ty::KvScheme | kernels::Ty::KvDType => format!("({e}) as u8"),
        kernels::Ty::Fp8Kind => format!("({e}) as u32"),
        _ => e,
    })
}

/// One `match` arm per row whose operands are fully sourced, for the Rust
pub fn emit_rust_dispatch(
    tables: &[&'static [KernelSig]],
    jit: &[&'static crate::device::DeviceKernel],
) -> String {
    emit_dispatch(tables, jit, Arms::Whole)
}

/// The SAME arms, JIT ONLY — the half a parity harness needs before a row is
#[must_use]
pub fn emit_rust_dispatch_probe(
    tables: &[&'static [KernelSig]],
    jit: &[&'static crate::device::DeviceKernel],
) -> String {
    emit_dispatch(tables, jit, Arms::JitOnly)
}

/// Which arms [`emit_dispatch`] writes.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Arms {
    /// The dispatcher: a JIT arm for a routed row, the `pie_k_*` arm for
    Whole,
    /// The probe: the JIT arm and nothing else.
    JitOnly,
}

fn emit_dispatch(
    tables: &[&'static [KernelSig]],
    jit: &[&'static crate::device::DeviceKernel],
    arms: Arms,
) -> String {
    let mut out = String::from(match arms {
        Arms::Whole => "// GENERATED by `kernels_cuda_new::abi::emit_rust_dispatch` — DO NOT EDIT.\n",
        Arms::JitOnly => {
            "// GENERATED by `kernels_cuda_new::abi::emit_rust_dispatch_probe` — DO NOT EDIT.\n\
             //\n\
             // THE PROBE, not the dispatcher: every row with a device twin\n\
             // takes its JIT arm here whether or not it is routed, and a row\n\
             // without one is absent rather than sent to `pie_k_*`. Nothing\n\
             // in a shipping build includes this file.\n"
        }
    });
    out.push_str(
        "//\n\
         // One branch per kernel! row that states both its operand types\n\
         // and where each argument comes from. A row missing either is\n\
         // absent here and belongs to a hand-written arm until it states\n\
         // them — which is a row's work, not the driver's.\n\
         //\n\
         // Keyed by the SYMBOL, like the C++ twin: the statement carries\n\
         // it, so there is no derived handle for the two to disagree on.\n\
         //\n\
         // A whole `match` EXPRESSION, not a run of arms: `include!` takes\n\
         // an expression or an item and never a pattern, so a file of bare\n\
         // arms has nowhere to be included from.\n\
         match b.kernel {\n",
    );
    for k in stated(tables) {
        let binds: Option<Vec<String>> =
            k.operands.iter().map(rust_bind_expr).collect();
        let Some(binds) = binds else { continue };

        let device = jit.iter().find(|d| d.sig.symbol == k.symbol);
        if arms == Arms::JitOnly && device.is_none() {
            continue;
        }
        let g: &'static KernelSig = device.map_or(k, |d| d.sig);

        let (mut need_in, mut need_out, mut need_w, mut need_ps) = (0u8, 0u8, 0u8, 0u8);
        fn reach(s: &Source, i: &mut u8, o: &mut u8, w: &mut u8, p: &mut u8) {
            match *s {
                Source::In(x)
                | Source::InRows(x)
                | Source::InElements(x)
                | Source::InWidth(x) => *i = (*i).max(x + 1),
                Source::Out(x)
                | Source::OutRows(x)
                | Source::OutWidth(x)
                | Source::OutElements(x) => *o = (*o).max(x + 1),
                Source::Weight(x) => *w = (*w).max(x + 1),
                Source::Param(x) | Source::ParamF32(x) | Source::RoutesOfParam(x) => {
                    *p = (*p).max(x + 1)
                }
                Source::Or(_, ref b) => reach(b, i, o, w, p),
                Source::Width(ref a) | Source::Isqrt(ref a) => reach(a, i, o, w, p),
                Source::Mul(ref a, ref b)
                | Source::Sub(ref a, ref b)
                | Source::Div(ref a, ref b)
                | Source::Ne(ref a, ref b) => {
                    reach(a, i, o, w, p);
                    reach(b, i, o, w, p);
                }
                Source::IfPresent(ref q, ref a, ref b) => {
                    reach(q, i, o, w, p);
                    reach(a, i, o, w, p);
                    reach(b, i, o, w, p);
                }
                _ => {}
            }
        }
        for o in g.operands {
            reach(&o.source, &mut need_in, &mut need_out, &mut need_w, &mut need_ps);
        }
        let mut stage = String::new();
        for (out, inp) in k.in_place {
            stage.push_str(&format!(
                "    if n_in > {inp} && n_out > {out} {{\n        \
                 stage_d2d(ctx, &b.rows, b.args[n_in + {out}], b.args[{inp}]);\n    }}\n"
            ));
        }
        let mut guard = String::new();
        let mut first = true;
        for clause in [
            (need_in > 0).then(|| format!("n_in >= {need_in}")),
            (need_out > 0).then(|| format!("n_out >= {need_out}")),
            (need_w > 0).then(|| format!("b.args.len() >= n_in + n_out + {need_w}")),
        ]
        .into_iter()
        .flatten()
        {
            guard.push_str(if first { " if " } else { " && " });
            first = false;
            guard.push_str(&clause);
        }
        if first {
            guard.push_str(" if true");
        }
        if need_ps > 0 {
            guard.push_str(&format!(" && spec.params.len() >= {need_ps}"));
        }
        for _o in g.operands {
        }
        if any_leaf(g, |s| *s == Source::WeightNamed2) {
            guard.push_str(" && !w_named2.is_null()");
        }
        if any_leaf(g, |s| *s == Source::WeightNamed) {
            guard.push_str(" && !w_named.is_null()");
        }
        if any_leaf(g, |s| {
            matches!(
                *s,
                Source::Gdn(_) | Source::GdnSlab(_)
            )
        }) {
            guard.push_str(" && gdn.is_some()");
        }
        for o in g.operands {
            if let Source::GdnSlab(f) = o.source {
                guard.push_str(&format!(" && gdn_slab(gdn, spec.state, \"{f}\").is_some()"));
            }
        }
        if any_leaf(g, |s| {
            matches!(
                *s,
                Source::Attn(_)
                    | Source::AttnNonZero(_)
                    | Source::AttnWindow
                    | Source::AttnPlan(_)
            )
        }) {
            guard.push_str(" && attn.is_some()");
        }
        for o in g.operands {
            if let Source::AttnPlan(family) = o.source {
                guard.push_str(&format!(
                    " && !attn_plan(a_of(attn), spec, u32::from(b.layers.start), \"{family}\").is_null()"
                ));
            }
        }
        for o in g.operands {
        if let Source::Or(a, b) = o.source {
            let Some(present) = slot_presence(a) else { continue };
            let resolves = match *b {
                Source::NamedScale => "named_scale(ctx, spec).is_some()".to_string(),
                Source::Lit(Lit::Null) => "true".to_string(),
                _ if o.ty.rust().starts_with('*') => {
                    match rust_bind_expr_of(b, o.ty) {
                        Some(e) => format!("!({e}).is_null()"),
                        None => continue,
                    }
                }
                _ => "true".to_string(),
            };
            guard.push_str(&format!(" && ({present} || {resolves})"));
        }
        }

        for o in g.operands {
            if let Source::AttnNonZero(f) = o.source {
                guard.push_str(&format!(" && is_set(a_of(attn).{f})"));
            }
        }
        for o in g.operands {
            match o.source {
                Source::ResultOrRegion(i) => {
                    guard.push_str(&format!(" && join_out(spec, {i}, frame, resolver).is_some()"));
                }
                Source::Aux(i) => {
                    guard.push_str(&format!(" && join_aux(spec, {i}, frame, resolver).is_some()"));
                }
                _ => {}
            }
        }
        if !mentions(k, |s| matches!(*s, Source::Aux(_))) {
            guard.push_str(" && spec.aux.is_empty()");
        }
        if !mentions(k, |s| *s == Source::PerHeadDim) {
            guard.push_str(" && spec.per_head_dim.is_none()");
        }
        if any_leaf(g, |s| *s == Source::RotaryWidth) {
            guard.push_str(" && rotary_width(ctx, spec, b.layers.start as usize).is_some()");
        }
        if any_leaf(g, |s| {
            matches!(
                *s,
                Source::KvLayerView
                    | Source::KvKeys
                    | Source::KvValues
                    | Source::KvLayerField(_)
            )
        }) {
            guard.push_str(" && has_kv_layer(attn, b.layers.start as usize)");
        }
        let mut guarded: Vec<&str> = Vec::new();
        let mut fields: Vec<&'static str> = Vec::new();
        for o in g.operands {
            for_each_leaf(&o.source, &mut |s| {
                if let Source::CtxNonZero(f) = *s {
                    fields.push(f);
                }
            });
        }
        for f in fields {
            {
                if guarded.contains(&f) {
                    continue;
                }
                guarded.push(f);
                guard.push_str(&format!(" && is_set(ctx.{f})"));
            }
        }

        let lowered_as = crate::x::contract(k.symbol).and_then(|c| c.lowered_as);
        let pattern = match lowered_as {
            Some(also) => format!("\"{}\" | \"{also}\"", k.symbol),
            None => format!("\"{}\"", k.symbol),
        };
        if let Some(device) = device {
            let Some(values): Option<Vec<String>> = device
                .sig
                .operands
                .iter()
                .map(|o| {
                    let variant = arg_value_variant(o.ty)?;
                    let expr = if variant.ends_with("::Ptr") {
                        rust_bind_expr_of(&o.source, o.ty)?
                    } else {
                        rust_bind_expr(o)?
                    };
                    let expr = if variant.ends_with("::Ptr") {
                        format!("({expr}) as *mut ::core::ffi::c_void")
                    } else {
                        expr
                    };
                    Some(format!("{variant}({expr})"))
                })
                .collect()
            else {
                continue;
            };
            let mut call = vec![
                "    unsafe { crate::bind::jit::fire(".to_string(),
                format!("        \"{}\",", device.sig.symbol),
                "        jit_dims(".to_string(),
                "            b, spec, ctx, attn, rows,".to_string(),
                "            width_of(b, n_in + 0),".to_string(),
                "            width_of(b, 0),".to_string(),
                "        ),".to_string(),
                "        &[".to_string(),
            ];
            call.extend(values.iter().map(|v| format!("            {v},")));
            call.push("        ],".to_string());
            call.push("        ctx.stream,".to_string());
            call.push("    ) };".to_string());
            call.push("    true".to_string());
            out.push_str(&format!(
                "{pattern}{guard} => {{\n{stage}{}\n}}\n",
                call.join("\n")
            ));
            continue;
        }
        if crate::execution::RUST_SERVED.contains(&k.symbol) {
            let served = entry_name(k.symbol);
            let served = served.strip_prefix(PREFIX).unwrap_or(&served);
            out.push_str(&format!(
                "{pattern}{guard} => {{\n{stage}    unsafe {{ crate::bind::service::{served}(\n        ctx,\n        {},\n    ) }};\n    true\n}}\n",
                binds.join(",\n        "),
            ));
            continue;
        }
        out.push_str(&format!(
            "{}{} => {{\n{}    unsafe {{ {}(\n        {},\n    ) }};\n    true\n}}\n",
            pattern,
            guard,
            stage,
            format!("crate::bind::abi::ffi::{}", entry_name(k.symbol)),
            binds.join(",\n        "),
        ));
    }
    out.push_str("_ => false,\n}\n");
    out
}

#[cfg(test)]
mod stated_rows {
    /// EVERY fully-stated row emits a branch, and the failure names the

    /// EVERY DIRECT INDEX IS COVERED BY A GUARD IT CANNOT OUTRUN.

    /// A CLAUSE THAT UNWRAPS SITS BEHIND THE TEST THAT MAKES IT TOTAL.
    #[test]
    fn nothing_unwraps_the_attention_context_before_testing_it() {
        let text = super::emit_rust_dispatch(crate::table::TABLES, &crate::device::jit_dispatched());
        let mut early = Vec::new();
        for arm in text.split("\n\"").skip(1) {
            let Some(end) = arm.find(" => {") else { continue };
            let guard = &arm[..end];
            let (unwrap, test) = (guard.find("a_of(attn)"), guard.find("attn.is_some()"));
            if let Some(u) = unwrap {
                if test.is_none_or(|t| u < t) {
                    early.push(guard.split('"').next().unwrap_or(guard).to_string());
                }
            }
        }
        assert!(
            early.is_empty(),
            "these guards call `a_of(attn)` before `attn.is_some()`, which is \
             a panic on a fire with no attention:\n  {}",
            early.join("\n  ")
        );
    }

    /// A DIVISION BY A CONTEXT FIELD CARRIES THAT FIELD'S `is_set`.
    ///
    /// `CtxNonZero` exists to be a divisor — a family zeroes the field to
    /// say "this launch is not mine" — so it is almost always nested
    /// inside a `Div`, and the guard loop that collected it matched only
    /// the TOP-LEVEL source. Seven arms divided by a context field with
    /// no refusal beside it, which is the regression the variant's own
    /// doc describes: gemma-4's per-layer theta, where "it would have
    /// rotated half of gemma-4 by nothing, silently".
    #[test]
    fn a_division_by_a_context_field_is_guarded_on_it() {
        let text = super::emit_rust_dispatch(crate::table::TABLES, &crate::device::jit_dispatched());
        let mut naked = Vec::new();
        for arm in text.split("\n\"").skip(1) {
            let Some(end) = arm.find(" => {") else { continue };
            let (guard, body) = arm.split_at(end);
            let bytes = body.as_bytes();
            for (i, _) in body.match_indices(").max(1)") {
                let mut depth = 0i32;
                let mut open = None;
                for j in (0..=i).rev() {
                    match bytes[j] {
                        b')' => depth += 1,
                        b'(' => {
                            depth -= 1;
                            if depth == 0 {
                                open = Some(j);
                                break;
                            }
                        }
                        _ => {}
                    }
                }
                let Some(open) = open else { continue };
                let divisor = &body[open + 1..i];
                for (k, _) in divisor.match_indices("ctx.") {
                    let field: String = divisor[k + "ctx.".len()..]
                        .chars()
                        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                        .collect();
                    if field.is_empty() {
                        continue;
                    }
                    if !guard.contains(&format!("is_set(ctx.{field})")) {
                        naked.push(format!(
                            "{}: divides by ctx.{field} with no is_set",
                            guard.split('"').next().unwrap_or(guard).trim()
                        ));
                    }
                }
            }
        }
        assert!(
            naked.is_empty(),
            "a family that zeroed one of these fields would divide by one \
             and launch instead of declining:\n  {}",
            naked.join("\n  ")
        );
    }

    /// THE TEST ABOVE CAN SEE THROUGH THE WRAPPER.
    ///
    /// Its scan is textual, so nothing but this says it still finds a
    /// field the narrowing hid. A divisor spelled the wrapped way must
    /// still be reported when its guard is missing — the assertion is on
    /// the SCANNER, with a body written here rather than emitted.
    #[test]
    fn the_divisor_scan_finds_a_field_inside_its_narrowing() {
        // Shaped exactly like an emitted arm: guard, ` => {`, body.
        let arm = "\nlayout::x\" if n_in >= 1 => {\n  \
            i32::try_from((width_of(b, 0)) / (i32::try_from(ctx.ple_dim)\
            .unwrap_or(i32::MAX)).max(1)).unwrap_or(i32::MAX),\n}";
        let (guard, body) = arm.split_at(arm.find(" => {").expect("shaped like an arm"));
        let bytes = body.as_bytes();
        let mut found = Vec::new();
        for (i, _) in body.match_indices(").max(1)") {
            let mut depth = 0i32;
            let mut open = None;
            for j in (0..=i).rev() {
                match bytes[j] {
                    b')' => depth += 1,
                    b'(' => {
                        depth -= 1;
                        if depth == 0 {
                            open = Some(j);
                            break;
                        }
                    }
                    _ => {}
                }
            }
            let Some(open) = open else { continue };
            let divisor = &body[open + 1..i];
            for (k, _) in divisor.match_indices("ctx.") {
                let field: String = divisor[k + "ctx.".len()..]
                    .chars()
                    .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                    .collect();
                if !field.is_empty() {
                    found.push(field);
                }
            }
        }
        assert_eq!(found, vec!["ple_dim".to_string()], "the scan lost the wrapped field");
        assert!(!guard.contains("is_set(ctx.ple_dim)"), "the fixture must be the unguarded shape");
    }

    /// A DECLARED FIELD REACHED THROUGH AN OPERATOR IS NARROWED FIRST.
    #[test]
    fn a_declared_field_under_an_operator_is_narrowed_first() {
        use kernels::Source;

        /// Arithmetic operands, and the conditionals that can hold one.
        fn operands_of(s: &'static Source, out: &mut Vec<&'static Source>) {
            match *s {
                Source::Mul(a, c) | Source::Sub(a, c) | Source::Div(a, c) | Source::Ne(a, c) => {
                    out.push(a);
                    out.push(c);
                    operands_of(a, out);
                    operands_of(c, out);
                }
                Source::Isqrt(a) => {
                    out.push(a);
                    operands_of(a, out);
                }
                Source::Or(a, c) => {
                    operands_of(a, out);
                    operands_of(c, out);
                }
                Source::IfPresent(p, t, o) => {
                    operands_of(p, out);
                    operands_of(t, out);
                    operands_of(o, out);
                }
                Source::Width(a) => operands_of(a, out),
                _ => {}
            }
        }

        let mut bare = Vec::new();
        for table in crate::table::TABLES {
            for row in *table {
                for op in row.operands {
                    let mut kids = Vec::new();
                    operands_of(&op.source, &mut kids);
                    for kid in kids {
                        if !super::reads_a_declared_field(kid) {
                            continue;
                        }
                        let Some(narrowed) = super::rust_arith_of(kid, op.ty) else { continue };
                        if !narrowed.contains("i32::try_from(") {
                            bare.push(format!("{} operand `{}`: {narrowed}", row.symbol, op.name));
                        }
                    }
                }
            }
        }
        assert!(
            bare.is_empty(),
            "these compose a driver-declared field into arithmetic without \
             narrowing it to the grammar's i32, so the generated file will \
             not compile the day the driver declares one of them `u32`:\n  {}",
            bare.join("\n  ")
        );
    }

    #[test]
    fn every_index_the_body_writes_is_inside_its_guard() {
        let text = super::emit_rust_dispatch(crate::table::TABLES, &crate::device::jit_dispatched());
        let mut unguarded: Vec<String> = Vec::new();

        for arm in text.split("\n\"").skip(1) {
            let Some(head_end) = arm.find(" => {") else { continue };
            let (head, rest) = arm.split_at(head_end);
            let guard = head;
            let body = &rest[" => {".len()..];

            let promise = |needle: &str| -> usize {
                guard
                    .match_indices(needle)
                    .filter_map(|(i, _)| {
                        guard[i + needle.len()..]
                            .split(|c: char| !c.is_ascii_digit())
                            .next()
                            .and_then(|d| d.parse::<usize>().ok())
                    })
                    .max()
                    .unwrap_or(0)
            };
            let base = [
                promise("n_in >= "),
                promise("n_out >= "),
                promise("b.args.len() >= n_in + n_out + "),
            ];

            let bytes: Vec<char> = body.chars().collect();
            let (mut stack, mut cur) = (Vec::new(), base);
            let mut at: Vec<[usize; 3]> = Vec::with_capacity(bytes.len());
            for (i, &c) in bytes.iter().enumerate() {
                if c == '{' {
                    let from = i.saturating_sub(300);
                    let seg: String = bytes[from..i].iter().collect();
                    let cond = seg.rsplit("if ").next().unwrap_or("").to_string();
                    let mut add = cur;
                    for (k, needle) in
                        [(0usize, "n_in > "), (1, "n_out > "), (2, "b.args.len() > n_in + n_out + ")]
                    {
                        for (j, _) in cond.match_indices(needle) {
                            if let Some(d) = cond[j + needle.len()..]
                                .split(|c: char| !c.is_ascii_digit())
                                .next()
                                .and_then(|d| d.parse::<usize>().ok())
                            {
                                add[k] = add[k].max(d + 1);
                            }
                        }
                    }
                    stack.push(cur);
                    cur = add;
                } else if c == '}' {
                    cur = stack.pop().unwrap_or(base);
                }
                at.push(cur);
            }

            let body_s: String = bytes.iter().collect();
            for (i, _) in body_s.match_indices("b.args[") {
                let Some(end) = body_s[i..].find(']') else { continue };
                let idx = body_s[i + "b.args[".len()..i + end].trim().to_string();
                let scope = at.get(body_s[..i].chars().count()).copied().unwrap_or(base);
                let mut want = |k: usize, n: usize| {
                    if n >= scope[k] {
                        unguarded.push(format!(
                            "{}: b.args[{idx}] needs {} > {n}, guard gives {}",
                            guard.split('"').next().unwrap_or(guard).trim(),
                            ["n_in", "n_out", "len-n_in-n_out"][k],
                            scope[k]
                        ));
                    }
                };
                if let Ok(n) = idx.parse::<usize>() {
                    want(0, n);
                } else if let Some(k) = idx.strip_prefix("n_in + n_out + ") {
                    if let Ok(n) = k.trim().parse::<usize>() {
                        want(2, n);
                    }
                } else if let Some(k) = idx.strip_prefix("n_in + ") {
                    if let Ok(n) = k.trim().parse::<usize>() {
                        want(1, n);
                    }
                }
            }
        }

        assert!(
            unguarded.is_empty(),
            "these generated indexes can run past the argument list:\n  {}",
            unguarded.join("\n  ")
        );
    }

    /// A row whose `elem` is a template ARGUMENT LIST still produces C++.
    ///
    /// # The silent failure this pins
    ///
    /// `DeviceKernel::instantiation` pastes `elem` between angle brackets, so
    /// a row for `template <class T, int BLOCK>` may spell
    /// `"device::bf16, 256"` — measured under NVRTC 13.0, and eight rows in
    /// the tree do it today. This emitter builds a POINTER type from the same
    /// string, and `const ::pie_cuda_driver::kernels::device::bf16, 256*` is
    /// not one.
    ///
    /// Nothing caught that, because the generated file is only compiled when a
    /// build wires this emitter in — so the effect was that the eight rows
    /// most likely to drift were the eight this check silently stopped
    /// covering. The head of the list is the storage type WHEN the element
    /// type is the first template parameter; when it is not, the head is a
    /// value and the row is refused rather than mis-spelled — see
    /// `an_elem_whose_head_is_a_value_is_refused`.
    #[test]
    fn a_multi_argument_elem_still_spells_a_pointer() {
        use super::emit_device_typecheck;
        use crate::device::DeviceKernel;
        let rows: Vec<DeviceKernel> = crate::device::ALTUP_AUX
            .iter()
            .take(1)
            .map(|k| DeviceKernel {
                sig: k.sig,
                template_path: k.template_path,
                elem: "device::bf16, 256",
            })
            .collect();

        let text = emit_device_typecheck(&rows).expect("a listed elem is emitted");
        assert!(
            text.contains("const ::pie_cuda_driver::kernels::device::bf16*"),
            "the operand type took the whole list rather than its head:\n{text}"
        );
        assert!(
            !text.contains("bf16, 256*"),
            "a comma reached a pointer declarator, which is not C++:\n{text}"
        );
        // The INSTANTIATION keeps the whole list -- that is the half that has
        // to name the kernel, and it is why the two cannot share a string.
        assert!(
            text.contains("device::bf16, 256>"),
            "the instantiation lost its second argument:\n{text}"
        );
    }

    /// An `elem` whose head is empty leaves its row UNCHECKED and says so.
    ///
    /// It used to refuse the whole set, and that was the wrong verb for the
    /// wrong reason. An unspellable `elem` is not drift in the row — the row
    /// may be entirely correct — it is a limit of an emitter that spells a
    /// buffer operand as a pointer to the head of `elem`. Refusing the set
    /// meant one such row took every OTHER row's assertion with it, and in a
    /// population as mixed as `unit::rows()` that is the difference between a
    /// unit that checks nineteen rows and a unit that checks none.
    ///
    /// So the row is skipped, counted, and named — in the returned
    /// [`super::DeviceTypecheck::skipped`] and in the generated text, because
    /// the reader of the file is who needs to know what it is not telling
    /// them.
    #[test]
    fn an_elem_with_no_head_is_not_checked() {
        use super::{Elem, Site, device_typecheck};
        use crate::device::DeviceKernel;
        let rows: Vec<DeviceKernel> = crate::device::ALTUP_AUX
            .iter()
            .take(1)
            .map(|k| DeviceKernel { sig: k.sig, template_path: k.template_path, elem: ", 256" })
            .collect();
        let refs: Vec<&DeviceKernel> = rows.iter().collect();
        let tu = device_typecheck(&refs, Site::Standalone, Elem::Resolve)
            .expect("an unspellable elem is a skip rather than a refusal");
        assert_eq!(tu.checked, 0, "an empty head was spelled:\n{}", tu.text);
        assert_eq!(tu.skipped.len(), 1);
        assert!(tu.skipped[0].1.contains("empty"), "{}", tu.skipped[0].1);
        assert!(
            tu.text.contains(rows[0].sig.symbol) && tu.text.contains("is not FULLY checked"),
            "the skipped row is not named in the file:\n{}",
            tu.text
        );
        // The ARITY is still asserted, and the scalars beside the buffer are
        // still asserted in their own positions. An `elem` this emitter
        // cannot spell costs the row one POSITION, not the row.
        assert!(tu.asserted > 0, "an unspellable elem silenced the whole row:\n{}", tu.text);
        assert!(
            tu.text.contains("::arity == "),
            "the arity of an unspellable row is not asserted:\n{}",
            tu.text
        );
    }

    /// An `elem` whose head is a VALUE leaves its row unchecked by name, and
    /// is not pasted into a declarator.
    ///
    /// The five spellings below are ones the tree actually carries, and every
    /// one leads a template argument list with something that is not a type:
    /// `device::i32(256)` and `device::i32(128)` are functional casts,
    /// `device::true_type::value` is a static data member, and `true` and `8`
    /// are literals. Pasted into `const ::…::{head}*` they produce a
    /// declarator the compiler rejects INSIDE THE GENERATED FILE — a
    /// diagnostic naming a line no one wrote and not naming the row that
    /// caused it, which is the failure mode this emitter exists to avoid. The
    /// row is named here instead.
    #[test]
    fn an_elem_whose_head_is_a_value_is_not_checked() {
        use super::{Elem, Site, device_typecheck};
        use crate::device::DeviceKernel;
        for elem in [
            "device::i32(256), false, false",
            "device::i32(128)",
            "device::true_type::value",
            "true, 8",
            "8",
        ] {
            let rows: Vec<DeviceKernel> = crate::device::ALTUP_AUX
                .iter()
                .take(1)
                .map(|k| DeviceKernel { sig: k.sig, template_path: k.template_path, elem })
                .collect();
            let refs: Vec<&DeviceKernel> = rows.iter().collect();
            let tu = device_typecheck(&refs, Site::Standalone, Elem::Resolve)
                .unwrap_or_else(|why| panic!("`{elem}` is a skip rather than a refusal: {why}"));
            assert_eq!(tu.checked, 0, "`{elem}` was spelled:\n{}", tu.text);
            assert!(
                tu.skipped[0].1.contains("VALUE rather than a type"),
                "`{elem}` was skipped for the wrong reason: {}",
                tu.skipped[0].1
            );
        }
    }

    /// A specialisation-suffixed symbol yields a C++ IDENTIFIER.
    ///
    /// `check_{symbol}` replaced `::` and nothing else, so
    /// `rmsnorm_strided_bf16#vec8` — a spelling the tree already carries —
    /// emitted `check_rmsnorm_strided_bf16#vec8`, and a `#` in a declarator is
    /// a parse error. The generated file is the one place a reader cannot fix
    /// what they find, so the sanitisation belongs here rather than in a
    /// convention about how a row may be named.
    #[test]
    fn a_specialisation_suffix_is_not_in_the_checker_name() {
        use super::emit_device_typecheck;
        use crate::device::DeviceKernel;
        let rows: Vec<DeviceKernel> = crate::device::ALTUP_AUX
            .iter()
            .take(1)
            .map(|k| DeviceKernel { sig: k.sig, template_path: k.template_path, elem: k.elem })
            .collect();
        let text = emit_device_typecheck(&rows).expect("the row is emitted");
        let checker = text
            .lines()
            .find_map(|l| Some(l.strip_prefix("using ")?.split(" = pie_sig<").next()?))
            .expect("a checker is declared");
        assert!(
            checker.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'),
            "`{checker}` is not a C++ identifier"
        );
        assert!(
            !checker.contains("::"),
            "a scope separator survived into `{checker}`"
        );
    }

    /// The assertion is UNEVALUATED, and that is not a style choice.
    ///
    /// The old form declared `[[maybe_unused]] void (*const check_x)(…) =
    /// &instantiation;` at namespace scope. Three units in this tree —
    /// `families::fa2`, `families::cascade` and `x::attn::mla_fa2` — pass
    /// `--device-as-default-execution-space`, under which an unannotated
    /// namespace-scope variable IS a `__device__` variable and `&__global__`
    /// is not a constant initialiser for one. The instrument would have been
    /// red on every FlashInfer unit for a reason no row could fix, and a red
    /// instrument that is red about the wrong thing gets deleted by the first
    /// person who meets it.
    ///
    /// `static_assert(is_same_v<…, decltype(&…)>)` compares the same two
    /// types in an unevaluated operand: nothing is declared, nothing is
    /// odr-used, and no execution space applies. This pins the form so that
    /// putting the definition back is a failing test rather than a discovery
    /// on a GPU.
    #[test]
    fn no_assertion_defines_an_entity() {
        use super::{Elem, Site, device_typecheck};
        let rows: Vec<_> = crate::device::ALTUP_AUX.iter().collect();
        let tu = device_typecheck(&rows, Site::Standalone, Elem::Resolve).expect("emitted");
        assert!(tu.checked > 0, "nothing was checked:\n{}", tu.text);
        assert!(
            !tu.text.contains("= &"),
            "an assertion takes an address in an EVALUATED context:\n{}",
            tu.text
        );
        assert_eq!(
            tu.text.matches("static_assert(::std::is_same_v<").count(),
            tu.asserted,
            "the assertion count and the asserted-position count disagree:\n{}",
            tu.text
        );
        assert_eq!(
            tu.text.matches("::arity == ").count(),
            crate::device::ALTUP_AUX.len(),
            "arity is not asserted once per row:\n{}",
            tu.text
        );
    }

    /// An `Appendix` does not include the file it is appended to.
    ///
    /// Every file under `csrc/src` uses `#pragma once`, and a unit's root
    /// reaches `nvrtcCreateProgram` under `unit.name` while the carried header
    /// set answers `{unit.name}.cuh` — two names for one text, which
    /// `#pragma once` cannot collapse. So an appendix that included its own
    /// templates would give NVRTC a second definition of every `__global__` in
    /// the unit, and the typecheck would break the compile it rides on.
    #[test]
    fn an_appendix_includes_no_templates() {
        use super::{Elem, Site, device_typecheck};
        let rows: Vec<_> = crate::device::ALTUP_AUX.iter().collect();
        let tu = device_typecheck(&rows, Site::Appendix, Elem::Opaque).expect("emitted");
        assert!(
            !tu.text.contains("#include \""),
            "the appendix includes a template header:\n{}",
            tu.text
        );
        assert!(tu.text.contains("#include <type_traits>"), "{}", tu.text);
        let standalone =
            device_typecheck(&rows, Site::Standalone, Elem::Resolve).expect("emitted").text;
        assert!(
            standalone.contains("#include \"norm/altup_aux.cuh\""),
            "a standalone TU must include its templates:\n{standalone}"
        );
    }

    /// `Elem::Opaque` does not GUESS a `Ty::Buf`'s pointee — it declines it.
    #[test]
    fn opaque_declines_a_buffer_rather_than_spelling_it() {
        use super::{Elem, Site, device_typecheck};
        let rows: Vec<_> = crate::device::ALTUP_AUX.iter().collect();
        let resolved = device_typecheck(&rows, Site::Standalone, Elem::Resolve).expect("emitted");
        let opaque = device_typecheck(&rows, Site::Standalone, Elem::Opaque).expect("emitted");
        assert!(
            resolved.checked > opaque.checked,
            "`Resolve` must check strictly more of a buffer-carrying row set \
             than `Opaque`: {} vs {}",
            resolved.checked,
            opaque.checked
        );
        assert!(
            opaque.skipped.iter().all(|(_, why)| why.contains("NOT in the tag")),
            "a row was skipped for an unstated reason: {:?}",
            opaque.skipped
        );
        assert!(
            !opaque.text.contains("device::bf16*"),
            "`Opaque` spelled a pointee from `elem`:\n{}",
            opaque.text
        );
        assert!(
            opaque.asserted > 0 && opaque.asserted < opaque.positions,
            "`Opaque` asserted {} of {} positions, which is all or nothing -- \
             the per-operand split is not doing anything:\n{}",
            opaque.asserted,
            opaque.positions,
            opaque.text
        );
        assert_eq!(
            resolved.positions, opaque.positions,
            "the two policies disagree about how many operands there are"
        );
        assert!(
            resolved.asserted > opaque.asserted,
            "`Resolve` asserted no more positions than `Opaque`: {} vs {}",
            resolved.asserted,
            opaque.asserted
        );
    }

    /// The whole thing is FALSIFIABLE: a wrong row produces different text.
    #[test]
    fn a_drifted_operand_changes_the_assertion() {
        use super::{Elem, Site, device_typecheck};
        use crate::device::DeviceKernel;
        use kernels::{KernelSig, LaunchRule, Ty, kernel, operands};

        let row = crate::unit::rows()
            .find(|k| k.sig.symbol == "norm::compute_rms_bf16")
            .expect("`norm::compute_rms_bf16` is in some unit");
        let truth = device_typecheck(&[row], Site::Standalone, Elem::Resolve)
            .expect("the real row is checked");
        assert_eq!(truth.checked, 1, "the control row was not checked:\n{}", truth.text);

        static DRIFTED: KernelSig = kernel!(compute_rms "norm::compute_rms_bf16",
            file = Some("norm/altup_aux.cuh"),
            launch = LaunchRule::Rms,
            operands = operands![
                reference: Bf16s,
                out: F32sMut,
                h: F32,
                eps: F32,
            ]);
        assert!(
            row.sig
                .operands
                .iter()
                .zip(DRIFTED.operands)
                .any(|(a, b)| a.ty != b.ty),
            "the mutant has drifted back into agreement with the row: this \
             test is now checking nothing"
        );
        assert_eq!(
            row.sig.operands.len(),
            DRIFTED.operands.len(),
            "the mutant differs in ARITY as well, which any emitter would \
             catch -- the point is a same-shape, same-width substitution"
        );
        assert!(
            row.sig.operands.iter().any(|o| o.ty == Ty::I32),
            "the control row no longer carries the operand the mutant swaps"
        );

        let wrong = DeviceKernel {
            sig: &DRIFTED,
            template_path: row.template_path,
            elem: row.elem,
        };
        let red = device_typecheck(&[&wrong], Site::Standalone, Elem::Resolve)
            .expect("the drifted row is still emitted -- it fails at the COMPILER");
        assert_eq!(red.checked, 1, "the drifted row was skipped, not checked");
        assert_ne!(
            truth.text, red.text,
            "a drifted operand produced IDENTICAL text: this emitter cannot \
             tell a right row from a wrong one, and every green it has ever \
             shown is worthless"
        );
        let at2 = |t: &str| {
            t.lines()
                .find(|l| l.contains("::at<2>,"))
                .map(str::to_string)
                .unwrap_or_else(|| panic!("no assertion for operand 2:\n{t}"))
        };
        assert!(
            at2(&truth.text).contains(" int>"),
            "the control's third operand is not asserted as `int`:\n{}",
            truth.text
        );
        assert!(
            at2(&red.text).contains(" float>"),
            "the drift did not reach the assertion for the operand it \
             changed:\ncontrol:\n{}\nmutant:\n{}",
            truth.text,
            red.text
        );
        let moved: Vec<(&str, &str)> = truth
            .text
            .lines()
            .zip(red.text.lines())
            .filter(|(a, b)| a != b)
            .collect();
        assert_eq!(
            moved.len(),
            2,
            "one operand drifted and {} lines changed -- the assertions are \
             not positional: {moved:?}",
            moved.len()
        );
        assert!(
            moved.iter().all(|(a, _)| a.contains("at<2>") || a.contains("operand 2 ")),
            "a line other than operand 2's assertion moved: {moved:?}"
        );
    }

    /// The real population is not empty, and `Ty::Fp8Kind` reaches an
    #[test]
    fn the_real_population_reaches_the_fp8_assertion() {
        use super::{Elem, Site, device_typecheck};
        use crate::unit::UNITS;

        let mut checked = 0usize;
        let mut row_count = 0usize;
        let mut asserted = 0usize;
        let mut positions = 0usize;
        let mut fp8_units = 0usize;
        let mut fp8_rows_checked = 0usize;
        for unit in UNITS {
            let rows: Vec<_> = unit.rows.iter().collect();
            let tu = device_typecheck(&rows, Site::Appendix, Elem::Opaque)
                .unwrap_or_else(|why| panic!("unit `{}` refuses its own rows: {why}", unit.name));
            assert_eq!(
                tu.checked + tu.skipped.len() + tu.aliased,
                unit.rows.len(),
                "unit `{}` lost rows: {} checked + {} skipped != {}",
                unit.name,
                tu.checked,
                tu.skipped.len(),
                unit.rows.len()
            );
            checked += tu.checked;
            row_count += unit.rows.len();
            asserted += tu.asserted;
            positions += tu.positions;
            assert_eq!(
                tu.text.matches("::arity == ").count(),
                unit.rows.len() - tu.aliased,
                "unit `{}` does not assert the arity of every row it holds",
                unit.name
            );
            if unit
                .rows
                .iter()
                .any(|k| k.sig.operands.iter().any(|o| o.ty == kernels::Ty::Fp8Kind))
            {
                fp8_units += 1;
                assert!(
                    tu.text.contains("sizeof(::__nv_fp8_interpretation_t) == 4"),
                    "unit `{}` names `Ty::Fp8Kind` and asserts nothing about \
                     its width:\n{}",
                    unit.name,
                    tu.text
                );
                if let Some(row) = unit
                    .rows
                    .iter()
                    .find(|k| k.sig.symbol == "attn::write_kv_fp8_per_tensor")
                {
                    assert!(
                        tu.skipped.iter().all(|(s, _)| *s != row.sig.symbol),
                        "`{}` is `PLAIN`, carries the operand this whole file \
                         is about, and is still NOT checked -- which is the \
                         state this change exists to end:\n{:?}",
                        row.sig.symbol,
                        tu.skipped
                    );
                    fp8_rows_checked += 1;
                }
            }
        }
        assert!(
            checked > 0,
            "no row in any unit produced an assertion: a file with nothing in \
             it compiles exactly like one that checks everything"
        );
        assert!(
            row_count >= 200 && positions >= row_count,
            "the population collapsed: {row_count} rows, {positions} operand positions"
        );
        assert!(
            asserted * 2 > positions,
            "fewer than half the operand positions in the tree are asserted \
             ({asserted} of {positions}). The instrument is a decoration again."
        );
        assert!(
            checked >= 40,
            "only {checked} of {row_count} rows are FULLY checked, down from the \
             56 measured when this consumer was written"
        );
        assert!(
            fp8_units > 0,
            "no unit names `Ty::Fp8Kind`, so the assertion this emitter orders \
             FIRST is unreachable and this test is a decoration"
        );
        assert_eq!(
            fp8_rows_checked, 1,
            "`attn::write_kv_fp8_per_tensor` is the `PLAIN` fp8 row the \
             widening was measured against; if it has moved or been renamed \
             this test stopped checking what it says it checks"
        );
    }
}
